### ISSUE TITLE
Information about the experience required to get to a certain level. 

### ISSUE THREAD

**Issue by TimotheeJeannin** [skadistats/clarity#100]
Hi @spheenik, 

Do you know how I can get information about the amount of experience required to reach a certain hero level ? 

I know I can have the **total earned experience** of a hero using `m_vecDataTeam.0000.m_iTotalEarnedXp` property and the **hero level** using `m_vecPlayerTeamData.0000.m_iLevel` but I would like to build a table like the following one:

|Level	| Experience Required |
| ----- | ------------------- |
|1	| 0 |
|2	| 200 |
|3	| 300 |
|4	| 400 |
|5	| 500 |
|6	| 600 |
|7	| 600 |
|8	| 800 |
|9	| 1000 |
|10	| 1000 |
|11	| 600 |
|12	| 2200 |
|13	| 800 |
|14	| 1400 |
|15	| 1500 |
|16	| 1600 |
|17	| 1700 |
|18	| 1800 |
|19	| 1900 |
|20	| 2000 |
|21	| 2100 |
|22	| 2200 |
|23	| 2300 |
|24	| 2400 |
|25	| 2500 |

This table can change with dota updates so it would be great to be able to have this information directly from a replay. :)

Thank you for this amazing parser! 

Tim

**Comment by spheenik** [comment]
Hi,
afaik this is not contained in the replay.
