### ISSUE TITLE
getting tick for given event?

### ISSUE THREAD

**Issue by sosso** [skadistats/clarity#101]
Hi,

I'm trying to follow the lines, but having a hard time figuring out how to go from an event to the replay tick.  Any pointers?

**Comment by spheenik** [comment]
`ctx.getTick()`?

**Comment by sosso** [comment]
Ah, sorry!  I worded my question poorly.  I was going to use a different source of event data to give in-game timestamps of ability uses, and then was hoping to go from timestamp -> tick, but it's probably best to just use Clarity to find the event in the first place?

**Comment by spheenik** [comment]
Do you have an example of a timestamp from that different source? What exactly is that different source?

**Comment by sosso** [comment]
When I play games, I'll write down timestamps of good teamfights or happenings (usually after I'm dead or there is a lull) so it'll just be something like 20min35sec.  That's post-horn time (or post start time, if I'm using the term correctly) but none of the console commands support jumping to time in that manner.

**Comment by spheenik** [comment]
There cannot be a direct mapping without going through the replay, since the replay tick also rises when gametime is paused. So the only thing you can do (I can think of right now) is load the replay with clarity, and run it until game time is where you want, and then just use `ctx.getTick()` to get the tick.

**Comment by sosso** [comment]
Thanks for thinking on it; I was hoping that there was something easy I may have missed.  My long term, scalable solution would require a similar approach, so I'll just implement it now.  Thanks!
