### ISSUE TITLE
2.1 Snapshot missing?

### ISSUE THREAD

**Issue by bwarren2** [skadistats/clarity#104]
The Readme implies that 2.1 is stable and preferred, but it is not at the listed uri.

![screenshot from 2016-09-05 20-37-15](https://cloud.githubusercontent.com/assets/1693541/18260192/ae19a70a-73a8-11e6-91cd-bb674d15d5b0.png)

Is 2.1 deprecated for 2.2?  What are the changes in 2.2 to be aware of?

**Comment by ChrisE87** [comment]
Snapshots are not stable, but experimental versions. You don't need to add this repository if you just want the stable version. Use the dependency shown above instead.

**Comment by bwarren2** [comment]
Great, thanks!
