### ISSUE TITLE
How to distinguish the ward is destroyed by which hero?

### ISSUE THREAD

**Issue by MFamilys** [skadistats/clarity#109]
Hi,boys.I want to distinguish the wards is be destroyed by which hero.

Here i use is the DOTA_COMBATLOG_DEATH to get the name of the hero and the OnEntityLeft to get the location of the wards.But i can't combinate this two info.

**Q1:** Firstly,the time of the ward be destroyed is different with the time of the ward Entity left.That seem have some random delays of it.Have any other way to overcome it?

**Q2:**Second,The location is effective mark of ward and I see the DOTA_COMBATLOG_DEATH event have a field names of "eventlocation" in the range between 0-16.Maybe i can use it?

Thanks a lot,Code for fun! :）

**Comment by MFamilys** [comment]
Oh,buddy.I meet the other question that how to get the item pickup event?I want to get the carry time of the  gems.Thanks very much.

**Comment by spheenik** [comment]
Q1: A ward dies at least 8 seconds before it leaves. It would be much better to look at `m_lifeState` of the ward. It dies in the moment this changes from 0 to 1. You can then try to correlate that with the combat log. See [a recent yasp change](https://github.com/odota/parser/pull/3) for discussion and code related to the topic.

Q2: idk

Q3: idk

**Comment by MFamilys** [comment]
OK.Thanks of lot.: ）
