### ISSUE TITLE
Propagating Exceptions in ControllableRunner

### ISSUE THREAD

**Issue by fischerq** [skadistats/clarity#112]
It would be good to get some exception handling for the processing thread of ControllableRunner. 

I was using a slightly out-of-date version of clarity and my parsing thread crashed with a runtime exception, keeping the main thread locked up waiting for the next tick. 

The exception was caused by some non-existing Protobuf fields and disappeared after updating, something I guess this will happen again with Valve making changes to the replays. It would be good to propagate the crash somehow, so that the main program can close down and return an error.

**Comment by spheenik** [comment]
Finally came around to implement this. 

ControllableRunner.seek() and ControllableRunner.tick() now throw a checked InterruptedException when the runner thread dies prematurely. Pushed a new 2.2-SNAPSHOT.
