### ISSUE TITLE
Annotation attributes for event-driven functions

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#114]
I was wondering if there was a list of attributes to filter some of the onEvent functions, specifically for `@onEntityUpdated`. I noticed in Clarity Examples with `@OnEntityPropertyChanged` you could filter by entity name and property with `classPattern `and `propertyPattern`, but it seems that this annotation was removed because I wasn't able to import it. Is there a list of annotation attributes for event functions? Thank you!

**Comment by TodorovicF** [comment]
Seems I answered my own question. The new OnEntityPropertyChanged annotation is in the work-in-progress 2.2-SNAPSHOT but I was using 2.1. Problem solved :)

**Comment by spheenik** [comment]
Exactly ;-)
