### ISSUE TITLE
About map coodinates and scale

### ISSUE THREAD

**Issue by JorgeZa** [skadistats/clarity#115]
Hi everybody.
I am trying to work with the movement of players extracted from replays, but allthe coodinates seems to be positives and none under 9k (I was told that coord = CBodyComponent.m_cell[XY] * 128 + CBodyComponent.m_vec[XY]).
So maybe the scale of the map is diferent than the used by the getLiveLeagueGames API or I am doing something wrong.

**Comment by spheenik** [comment]
m_cell[XY] is a positive value, from 0 to 255 iirc.
m_vec[XY] seem to be in the range from 0 to 255.999, so it seems the "times 128" is incorrect.

Now if you would do  CBodyComponent.m_cell[XY] * 256 + CBodyComponent.m_vec[XY]), you would get values ranging from 0 to 64k on both axes. If there are none under 9k, you are definitely doing something wrong. 

I think the rest must be a scaling / translation issue. What is the range of values in getLiveLeagueGames()?

**Comment by spheenik** [comment]
I implemented a basic map view in clarity analyzer today, to check this once and for all:

CBodyComponent.m_cell[XY] * 256 + CBodyComponent.m_vec[XY] - 32768.0

calculates everything correctly and sets the origin (0/0) to the middle of the map.
Dota only uses around a quarter of the available space, it's map is around 29000 units high/wide.

**Comment by JorgeZa** [comment]
Thanks for your help.
Also, the scale in getliveLeague games the map seem to be around 16000 units high and wide

**Comment by spheenik** [comment]
Then I think halving what you get from my calculation should give you what you want.

**Comment by spheenik** [comment]
Hey, quick heads up: Cells are only 128 units wide/high, even if the vector is sometimes more than 128^2 in length, so the computation is:

CBodyComponent.m_cell[XY] * 128 + CBodyComponent.m_vec[XY] 

with the origin being in the bottom left of the map.

**Comment by JorgeZa** [comment]
So,everything is going to be in positive range right?

**Comment by spheenik** [comment]
Yes, but you can also translate the coords to have the origin in the middle of the map, no problem.
There's a CWorld entity, which contains properties for the min/max extent of the world, which goes from approximately -9000 to 8200 (for X), so I guess Valve also do translate.
