### ISSUE TITLE
How to detect/record pauses in the game?

### ISSUE THREAD

**Issue by jyulin2000** [skadistats/clarity#116]
Hi, was wondering how/where to find information pertaining to the game being paused in the game file. Related to that, how exactly does the timing system in relation to the actual in-game time and the ticks work? I know that 30 ticks correspond to one second, but how would I get the actual in-game time given the tick of an event? Sorry if this seems very simple, I'm new to this parser and the actual game itself too (but it's been really useful so far!)

**Comment by spheenik** [comment]
You can't compute the ingame time from the tick, since ticking continues even when the game is paused.

What you can compute is "replay time", there's 30 ticks per second.

Game time can be retrieved from the entity "CDOTAGamerulesProxy", property "m_pGameRules.m_fGameTime". There's also a property "m_pGameRules.m_bGamePaused" which indicates whether the games is paused at the moment or not.

**Comment by jyulin2000** [comment]
Thanks so much for the reply, but I'm still kind of lost (Sorry, I don't really know what I'm doing). Specifically, in the allchat example you have in the examples repository, how would I get the in game time stamp for a specific chat? And how would I be able to record pauses in a program? Thanks again.

**Comment by spheenik** [comment]
You need to understand how to get entity data out of the replay. [Here is a small example](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/dumpmana/Main.java). It works a bit with entity data. Another one is the [matchend example](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/matchend/Main.java).

Also, please have a look at [Clarity Analyzer](https://github.com/spheenik/clarity-analyzer) to see what data you can expect.

I'm sorry, but I can't write the code for you. Gotta work yourself ;-)
