### ISSUE TITLE
How to get Cosmetic item names

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#117]
I've been looking through the `CDOTAWearableItem` entities and trying to figure out how to get a name for the cosmetic item in question. The `StringTableIndex` for all of them is always -1 so it's not there, but there's another number, `m_iItemDefinitionIndex`, which seems like a unique identifier for each item and may point to a name. I'm just not sure if there's a specific StringTable or container that has these cosmetic names.

**Comment by spheenik** [comment]
Do you have some kind of strong handle in the CDOTAWearableItem? It's a 64 bit value that seems random (like a hash). If so, use the [Resources processor](https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/processor/resources/Resources.java) by annotating your processor with @UseResources and querying by ctx.getProcessor(Resources.class).getEntryForResourceHandle(yourHandle).

Good luck!

**Comment by spheenik** [comment]
Here's an [example for using the Resource processor](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/resources/Main.java).

**Comment by TodorovicF** [comment]
Thank you, I'll look into that!
