### ISSUE TITLE
Difference between getting a Property with a FieldPath and getProperty

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#118]
Is there any difference between getting a Property for an Entity via `Entity.getProperty("some_property")` and first getting a FieldPath for the Property with 
`FieldPath fp =  Entity.getDtClass().getFieldPathForName("some_property")` and then retrieving the Property with `Entity.getPropertyForFieldPath(fp)`. I can't seem to notice any performance difference between the two so I'm guessing getting the FieldPath is simply safer because getProperty can throw an error if the Property doesn't exist, while with a FieldPath it will be null and can be checked against to avoid a crash. Is there any other difference? Thank you!

**Comment by spheenik** [comment]
There is a difference in speed.
Converting a property name to a fieldpath is time consuming, so if you
want to look up the same property often, it's faster ;-)

**Comment by TodorovicF** [comment]
Ah thanks a lot! That's what I had initially thought :)
