### ISSUE TITLE
Missing Purchaser for items in 7.0 replays

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#121]
Thank you for updating the parser for the new patch! I've only come across one problem so far and that CDOTA_Item_* entities don't contain the m_hPurchaser property anymore. I'm not sure if this is how it should be, but if it is, is there another way to get the purchaser of the item? I know m_hOwnerEntity gets the current holder of the item, but if the item changes hands, is dropped, or is on the courier, the player who initially purchased the item is lost. Thanks!

**Comment by TodorovicF** [comment]
Just to add, I'm using the 2.1.1-SNAPSHOT and the replay I tested was 2847563476. There's also a new property m_iPlayerOwnerID, so testing to see if this is different from m_hOwnerEntity or if they always point to the same hero.

**Comment by TodorovicF** [comment]
I tested with m_iPlayerOwnerID and this seems to be now tied to the purchaser of the item (m_iPlayerOwnerID and m_hOwnerEntity are sometimes different, with m_iPlayerOwnerID never changing for the same item) and perhaps replaced m_hPurchaser.

**Comment by spheenik** [comment]
I have not looked at changes in the data yet, so I can't help.
