### ISSUE TITLE
how to get hero damage from replay

### ISSUE THREAD

**Issue by yangboben** [skadistats/clarity#122]
Hello, I have a question, is there any way to get hero damage from replay or I can only get that from counting all damage information?

**Comment by spheenik** [comment]
I had a look, doesn't seem to be in the replay. So yes, I think you have to count.

But: Check for yourself, you can run [the serializers example](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/serializers/Main.java), which will put a text file into the current directory which contains a dump of all serializers. 

Maybe I overlooked something.

**Comment by yangboben** [comment]
oh,  I got it ,thank you very much for your reply , I will have a try by myself.
