### ISSUE TITLE
Is it possible to use clarity to parse dota2 .meta file ?

### ISSUE THREAD

**Issue by Raikiree** [skadistats/clarity#123]
the meta extension file from the api, could we use clarity to decode it?
Thanks!

**Comment by spheenik** [comment]
I do not know anything about this file.
What does it contain?

**Comment by Raikiree** [comment]
It contains encrypted data, but if you open it with txt editor, some characters will be decrypted as the key words from clarity, such as npc_dota_hero. So I am wondering whether can we use clarity to decode the rest of the file.

**Comment by gerlaic** [comment]
I think here is one example of .meta file, it another file located on the same server of replays. It's said to contain the new Post Game Details that published in last autumn. 


[2762708752_900104790.zip](https://github.com/skadistats/clarity/files/686288/2762708752_900104790.zip)

**Comment by spheenik** [comment]
I added functionality to parse it in 2.2-SNAPSHOT. [Example of how to use.](https://github.com/skadistats/clarity-examples/blob/77acfd2249a537593eb3c35fd87b398fe8c106ec/src/main/java/skadistats/clarity/examples/metadata/Main.java)

Note that if you do not use 2.2-SNAPSHOT yet, you can it via the following code:
```java
meta = Packet.parse(S2DotaMatchMetadata.CDOTAMatchMetadataFile.class, ByteString.readFrom(stream));
`

**Comment by Raikiree** [comment]
Thanks! Really helpful!!!

**Comment by TimotheeJeannin** [comment]
Hi @gerlaic 

How do you download meta files ? 

Somthing like `http://replay<cluster>.valve.net/570<match_id>_<replay_salt>.meta.bz2` I suppose ?

Tim
