### ISSUE TITLE
Entity parse fails on Win, works on Mac

### ISSUE THREAD

**Issue by jiricapek** [skadistats/clarity#124]
Hi,
I am parsing demo/replay file recorded with console in Dota by "_record" command. It works great when recorded on my development Mac OS X Sierra, but when recorded by "_record" in Dota on Win 10 then same clarity code gives exception : 

Caused by: java.lang.RuntimeException: class for new entity 0 is 0, but no dtClass found!.
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:147)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
	at skadistats.clarity.event.Event.raise(Event.java:23)

I am using clarity version 2.1.1 and current Dota (build 1543414). 
Demo file from Win 10 : https://www.dropbox.com/s/5hpcjv7655vq2fj/demo.dem?dl=0

Do you have any idea why it is not working on Win 10 ? 
Thanks.

**Comment by jiricapek** [comment]
From debugging I found that DTClass map byClassId is empty in Win 10 demo file, but in Mac demo file in is not empty. But why is that I do not know, yet.

**Comment by spheenik** [comment]
What version of clarity are you using? If it's not 2.2-SNAPSHOT, could you try it? IIRC it has a fix for this.

**Comment by jiricapek** [comment]
I am using 2.1.1. Switched to 2.2 and made some changes on my part, but it looks like it runs under win 10. Thanks !

**Comment by spheenik** [comment]
Good to hear :)
