### ISSUE TITLE
Revive smoke?

### ISSUE THREAD

**Issue by austinmilt** [skadistats/clarity#128]
What would it take to get smoke back up and running? I use Python for 99% of what I do, and am currently working on a project (see issue #126) that partially uses Python, and where speed is not crucial (though it is potentially an issue). Is it, e.g. a matter of updating a few files, or would it need reprogramming from the ground up?

**Comment by spheenik** [comment]
Smoke is only capable of reading replays from the Source 1 Engine.
Making it fit for Source 2 borders on a complete rewrite, in fact, clarity is the only parser that is capable of parsing replays for both engines, the others (Dotabuff's yasha, invokr's alice, onethirtyfive's smoke) all are legacy now.
