### ISSUE TITLE
DOTA_MODIFIER_ENTRY_TYPE_REMOVED and time

### ISSUE THREAD

**Issue by inShu** [skadistats/clarity#129]
```
@OnModifierTableEntry()
public void onModifierEntry(Context ctx, DotaModifiers.CDOTAModifierBuffTableEntry e)
{
}
```

How we can measure time between **DOTA_MODIFIER_ENTRY_TYPE_ACTIVE** and **DOTA_MODIFIER_ENTRY_TYPE_REMOVED**?
For the first one we got **e.getCreationTime()**.
But for second we got nothing.

Should we note ticks from **ctx** and work with them? (In that case we assume that 1 second of time have 30 ticks ALWAYS). What is the true-way?

**Comment by inShu** [comment]
Ticks are not a good idea as I can see. Does anyone have any thoughts?

**Comment by spheenik** [comment]
While a tick's duration is always 1/30 of a second, ticking continues even when the game is paused. So I guess the best thing to do is grab the actual game time and use that (`m_pGameRules.m_fGameTime` on `CDOTA_GamerulesProxy`).

**Comment by inShu** [comment]
Thank you for suggestion.

Could you please be more specific of how to obtain that m_fGameTime?

```
Entities ent = ctx.getProcessor(Entities.class);
Iterator<Entity> en = ent.getAllByDtName("CDOTA_GamerulesProxy");

```

Leads to nothing.

**Comment by inShu** [comment]
Thank you very much!
Maybe you can clarify why time value is so strange? For example I got event on **02:53** of game time. And this time mark is equal to **401** of **m_pGameRules.m_fGameTime**
But 401 is 06:41, so we have a shift in 03:48 (228)

**Comment by spheenik** [comment]
I think it's because you have to subtract the actual game start time from `m_pGameRules.m_fGameTime`.

See [this comment](https://github.com/skadistats/clarity/issues/126#issuecomment-272269084), look for `getRealGameTimeSeconds()`

**Comment by inShu** [comment]
Got it. Thank you!

**Comment by STRATZ-Ken** [comment]
@inShu Are you able to get the Modifier name somehow?  See ticket #159
