### ISSUE TITLE
Visibility of hero

### ISSUE THREAD

**Issue by inShu** [skadistats/clarity#130]
For example I'm hooking someone from high ground (he's invisible for me). I got a moment when hook modifier applied. How I can understand status of visibility for this hooked victim?
I'm almost sure that I can't find such information in clarity, but want to be sure before moving with other decisions.
And by the way, thank you for your project and intense support. Great job!

**Comment by spheenik** [comment]
You're welcome.

I don't understand your question. What exactly do you want to archieve?

**Comment by inShu** [comment]
Does Dire team can see certain hero from radiant team at this moment. How I can figure that out?

**Comment by spheenik** [comment]
Hmm, there's a property `m_iTaggedAsVisibleByTeam` for every entity. It looks like it might be some kind of bitfield (or something), but I never had a closer look :)

**Comment by inShu** [comment]
How could I miss it?! Thank you very much! If I will get any details about these bits structure, I will report here.

**Comment by inShu** [comment]
Ok. 3 and 4 bits of that value controls visibility for certain teams. Other flags regulating difeirent situations with smoke and other I guess.

**Comment by darrensapalo** [comment]
Hi @inShu , would you happen to have more details about the property? I am also currently exploring hero visibility right now as well.
