### ISSUE TITLE
Parsing camera position

### ISSUE THREAD

**Issue by Lauler** [skadistats/clarity#133]
We're interested in doing some research on something called perception action cycles (defined as a shift in a player's point of view that exceeds a certain threshold in distance), as well as action latency (the time it takes them to perform an action after a shift in PoV). An earlier Starcraft II study found that these were good predictors of player skill and expertise. If you're interested in reading it the study can be found here: 

http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0075129 

We've looked through your examples, read through a fair amount of previous clarity issues, and built the clarity-analyzer to try and better understand the protobuf jungle. We're now easily able to get player positions. 

But from your clarity-analyzer we don't understand where exactly you're pulling the camera positions from (and it does seem like you are able to parse and visualize them). We'd appreciate it if you could help and save us some hours of trial and error by pointing us in the right direction :)

**Comment by spheenik** [comment]
Hey, don't have much time, so just a quick headsup:

Code is here:

https://github.com/spheenik/clarity-analyzer/blob/master/src/main/java/skadistats/clarity/analyzer/main/MapControl.java#L88-L89

There are `CDOTAPlayer'-entities, one for each player, that have coordinates of the player screen. These coordinates are somehow projected in the real game, and I don't know how exactly, and in clarity-analyzer I basically show a rectangle using this point as the center.

HTH, do not hesitate to ask if you have more questions ;-)

**Comment by Lauler** [comment]
Thanks for your help! We were able to get the camera positions.

My second question is whether you have any insight on which player actions go into a players "action per minute" calculation? Are they all contained in one place like dotaunitorder_t. Or do you think pings and addunitselections from ?EDotaUserMessages are also included in this? 

The actions per minute calculation itself is not of that great importannce. We'd simply like to be able to extract the tick for each player action in order to get a sense for a players average "action latency" (the time it takes them to perform an action after switching PoV).

We're thinking these relevant actions are the dotaunitorders and the addunitselections. But we'd like to double check with you whether there are any other player actions hidden somewhere in clarity that we don't know about.

**Comment by spheenik** [comment]
On the road and not much time. You have the mouse movement on `CDOTAPlayer` as well as `CDOTAUserMsg_SpectatorPlayerClick` and `CDOTAUserMsg_SpectatorPlayerUnitOrders` messages. Other than that, there's nothing iirc.

**Comment by Lauler** [comment]
Thanks for taking the time @spheenik , we really appreciate it! We made a huge 200mb dump of everything in a replay (about the time you posted) to figure things out and noticed the SpectatorPlayer orders were prominent. And the sequence number for them divided with timestamp in minutes seemed to match up with actions per minute.  

It's a bit difficult for us navigating around all this data without being familiar with it, but we're getting there. And I'm not the java dev among us so excuse me if the questions are not phrased as well as they could be :)
