### ISSUE TITLE
Baseline not found crash

### ISSUE THREAD

**Issue by howardchung** [skadistats/clarity#135]
Attempting to parse the following replay:
http://replay133.valve.net/570/2971672248_1845031426.dem.bz2

Crashes with error:
```
odota-parser | java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Baseline for class CDOTA_Ability_Alchemist_AcidSpray (29) not found.
odota-parser |  at skadistats.clarity.event.Event.raise(Event.java:25)
```

**Comment by spheenik** [comment]
I looked at this. It's very strange.
I can reproduce this with 2.1.1, but not with 2.2-SNAPSHOT. 

Strange thing is, there is no alchemist in this game. So the 2.1.1 code has read something wrong, but I can't seem to find it. 

Is this widespread or a single occurrence?

**Comment by howardchung** [comment]
A user reported it and I verified that it was causing a Java crash.  Don't have a second repro yet but I can ask people to look out for other matches that won't parse.

**Comment by howardchung** [comment]
Production OpenDota should be using 2.2 snapshot.

https://github.com/odota/parser/blob/master/pom.xml

Possibly my dev environment is out of date, I'll remake that container and see if it happens again

**Comment by spheenik** [comment]
Ok, gives a sense of relief you already use 2.2 in prod.
I looked over the diff between HEAD and 2.1.1 for half an hour, I just do not see why.

Maybe I'll have a look again in the near future.

**Comment by howardchung** [comment]
Are both versions using the same generated protobuf classes?

**Comment by spheenik** [comment]
yep

**Comment by howardchung** [comment]
confirmed fine with 2.2-SNAPSHOT.  I'll reopen if i find another repro.
