### ISSUE TITLE
Replacement of "m_vecOrigin"?

### ISSUE THREAD

**Issue by MrGONG0028** [skadistats/clarity#138]
Since "m_vecOrigin" is not available in Source 2, what attribute can be used to replace it?

**Comment by spheenik** [comment]
`CBodyComponent.m_cell[X,Y,Z]`

**Comment by spheenik** [comment]
Also read [this](https://github.com/skadistats/clarity/issues/115) and look at [this](https://github.com/spheenik/clarity-analyzer/blob/master/src/main/java/skadistats/clarity/analyzer/main/icon/EntityIcon.java)

**Comment by MrGONG0028** [comment]
I think I just calculate it as cellX*128+vecX.

**Comment by spheenik** [comment]
that's correct.
