### ISSUE TITLE
Get a Heros items at match end

### ISSUE THREAD

**Issue by shcizo** [skadistats/clarity#139]
Hi

A Hero entity (Entity entity = ctx.getProcessor(Entites.class).getByDtName("CDOTA_Unit_Hero_xx") have the property m_hItems.0007 returning some sort if ID. Is it possible in some way correlate this id to the name of the item?

**Comment by spheenik** [comment]
Did you solve it?

**Comment by shcizo** [comment]
Ye, I looked through the closed issues in clarity.examples and found a issue you responded to which got me on the right track.
https://github.com/skadistats/clarity-examples/issues/14
