### ISSUE TITLE
getProperty behaviour is kinda unsafe

### ISSUE THREAD

**Issue by bluepeppers** [skadistats/clarity#14]
Hi,

So `e.getProperty(prop)` is pretty much the same as `e.getState()[e.getDtClass().getPropertyIndex(prop)]`. However, `.getPropertyIndex` will return a `null` if the property does not exist. `getProperty` does not check for this, meaning that if you want to access a property that is not guaranteed to be there (i.e. all properties), then you cannot use `getProperty`. Instead you have to replace `e.getProperty(prop)` with `int propI = e.getDtClass().getPropertyIndex(prop); if (i == null) {return null;} else {return e.getState()[propI];}`

Anyway, it might be nice if getProperty explicitly checked for null indexes prior to doing the lookup, so it can propagate the null, instead of throwing a null pointer exception.

Alternatively, one could embrace the unsafe nature of `getProperty`, but if so, it would be nice to have a warning in the docs/a comment on the decl or something :)

Thanks,

Laurie

**Comment by spheenik** [comment]
fixed in 2.0-dev branch:

https://github.com/spheenik/clarity/commit/d843b901603362ba21e587a76ac99b68e147d175
