### ISSUE TITLE
Having trouble getting up-and-running

### ISSUE THREAD

**Issue by someantics** [skadistats/clarity#141]
Mac OS X Sierra 10.12.4, Java 1.8.0_13

Sorry for the silly question, but I'm no Java developer so I'm not familiar with Maven or anything. My issue looks a little similar to [this one](https://github.com/skadistats/clarity/issues/90) but I'm not sure.

Anyway, it seemed like the easiest way to get started is with running the combatlog example in clarity-examples. So with the pom.xml file in my directory, I run `mvn -P combatlog package` and get the following output:

`[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building clarity-examples 2.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ clarity-examples ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/ethompson/Documents/media/clarity examples/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ clarity-examples ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ clarity-examples ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/ethompson/Documents/media/clarity examples/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ clarity-examples ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ clarity-examples ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ clarity-examples ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /Users/ethompson/Documents/media/clarity examples/target/combatlog.jar
[INFO] 
[INFO] --- onejar-maven-plugin:1.4.4:one-jar (default) @ clarity-examples ---
[INFO] Using One-Jar to create a single-file distribution
[INFO] Implementation Version: 2.2-SNAPSHOT
[INFO] Using One-Jar version: 0.97
[INFO] More info on One-Jar: http://one-jar.sourceforge.net/
[INFO] License for One-Jar:  http://one-jar.sourceforge.net/one-jar-license.txt
[INFO] One-Jar file: /Users/ethompson/Documents/media/clarity examples/target/combatlog.one-jar.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.970 s
[INFO] Finished at: 2017-04-23T23:50:38-07:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------`

Now, if I run `java -jar target/combatlog.one-jar.jar rep.dem` (that is the correct name for my replay), I get the following error:

`Exception in thread "main" java.lang.ClassNotFoundException: skadistats.clarity.examples.combatlog.Main
at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:713)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:630)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at com.simontuffs.onejar.Boot.run(Boot.java:334)
at com.simontuffs.onejar.Boot.main(Boot.java:166)`

It looks like I'm missing something basic - the uber jar was created but the main class isn't being found? Why?

Thanks in advance for helping me get started. I'm guessing that once this is fixed I can just build all of the packages I need individually in the same way?

**Comment by spheenik** [comment]
The directory you issue the build command in seems to be empty (except for the pom.xml).

```
git clone http://github.com/skadistats/clarity-examples
cd clarity-examples
mvn -P combatlog package 
java -jar target/combatlog.one-jar.jar replay.dem
```

should yield a result.

No need to build clarity itself!

**Comment by someantics** [comment]
Awesome, thanks so much. For some reason I thought that Maven would do everything for me, with no need for the source from Github. Thanks!

**Comment by spheenik** [comment]
You're welcome!
