### ISSUE TITLE
Accessing length of array properties / bug in Entity.getPropertyForFieldPath()

### ISSUE THREAD

**Issue by fischerq** [skadistats/clarity#142]
I've run into a bug/unintended behavior of `Entity.getPropertyForFieldPath()`, which I believe is tied to the internal representation of FieldPaths.

I want to access the length of some array property, e.g `CDOTA_PlayerResource.m_vecPlayerTeamData`, which has index/FP `1`. Querying the Fieldpath for this and then calling `getValueForFieldPath()` returns the first leaf-level property `CDOTA_PlayerResource.m_vecPlayerData.0000.m_bIsValid` associated with FP `1/0/0`. 

It looks like the FieldPaths internally keep a fixed-length list padded with zeroes, e.g. `[0, 0, 0, 0, 0, 0]`, probably this is the cause of the bug?

**Comment by spheenik** [comment]
Thanks for the report. Indeed looks like a bug. I'll see when I have the time to look into it.

**Comment by spheenik** [comment]
should be fixed on latest 2.3-SNAPSHOT.
