### ISSUE TITLE
Net move speed

### ISSUE THREAD

**Issue by austinmilt** [skadistats/clarity#155]
Trying to pull a hero's move speed out of the replay files. Looks like the "m_iMoveSpeed" property for a "CDOTA_Unit_Hero_*" is only base move speed. Do I need to add up all additional move speed effects from auras and items to get the net move speed, or is this net value stored somewhere in the replay?

I know the answer is usually "go figure it out yourself," so consider this a post to see if anyone has already encountered and overcome this rather than a request to go figure it out for me.

**Comment by spheenik** [comment]
I certainly have not done any research in this area, so I can't help.

But my feeling is that the chance that the complete data to properly devise movespeed is in the replay is low. 

Maybe one way would be to look at hero positions in the different frames, and deducing the movespeed from that. You'd have to look that no slow modifiers are applied, and blinks would create "spikes", but you'd have long periods of constant speed when the hero is just walking...

**Comment by austinmilt** [comment]
I'm guessing this is a client responsibility, which would mean I'd need to parse every unit in the replay, searching for a list of abilities and items, cross-reference their data with the npc resources in the game files to get effect radii and magnitude, calculate distances between units to see if an aura overlaps, and finally add up everything that effects a hero. All for net move speed. Probably the same thing for armor. 

I will leave this open for a few more days to see if anyone has another thought. Thanks for the response.

**Comment by spheenik** [comment]
Nice idea, but it will fall apart since you do not know which client version the replay was recorded with, and since base movement speeds / speed buffs from items, and AOE of effect change during patches, it will not work.

**Comment by Noxville** [comment]
I've done the approach @spheenik mentions - looking at the frequency of tiles moved per second interval. Works pretty decently after you filter out zero-movements.
