### ISSUE TITLE
DOTA_COMBATLOG_PICKUP_RUNE never firing

### ISSUE THREAD

**Issue by dierke9** [skadistats/clarity#157]
When running several demo's trough the combatLogger it never gets the DOTA_COMBATLOG_PICKUP_RUNE. Is this not implemented yet?

**Comment by spheenik** [comment]
DOTA_COMBATLOG_PICKUP_RUNE is pretty old, so if it is not firing, there are no such events in the replay. I don't know if older replays maybe do contain the data, but I supect that would be of no help, anyway.
