### ISSUE TITLE
Video Game View - made with skadistats clarity

### ISSUE THREAD

**Issue by austinmilt** [skadistats/clarity#158]
This isnt an issue. I just wanted to give a holler of thanks to @spheenik for keeping clarity alive and show an example of [something a little different](https://www.youtube.com/watch?v=vosreYAUUug) that you can do with clarity.

[reddit release post](https://www.reddit.com/r/DotA2/comments/817ror/video_game_view_alpha_watch_dota_2_videos_on/)

**Comment by spheenik** [comment]
This is really cool!

**Comment by STRATZ-Ken** [comment]
It is.  I unique idea for sure.
