### ISSUE TITLE
Modifiers

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#159]
So I am trying to use @OnModifierTableEntry for storing modifiers.  (Yes, I know you can use CombatLogs, but they are wrong in many ways).

Here is an output of one entry 
```
entry_type: DOTA_MODIFIER_ENTRY_TYPE_ACTIVE
parent: 12681455
index: 2
serial_num: 218
modifier_class: 1193
ability_level: 1
creation_time: 123.39846
caster: 12681455
ability: 1704004
aura: false
```

Entry Type : Either Added or Remove.
Parent  : Basically who is getting the buff.
Index : A sequential list in order from 1-X when the game ends.  Each hero gets its own list.
Serial Number : **Unknown** 
Modifier Class : In Source 1 this references the ModifiersName StringTable.  In Source 2 that list does not exist.  **Any ideas what to do?**
Ability Level : Figure this out on your own.
Creation Time : Time in replay.
Caster : Who Casted it.
Ability : Handle of the Ability, easy to convert, could be an item.
Aura : If its an Aura effect.  I think this is used for items like AC where the Holder gets a different buff from the aura.  

Any help on the 2 above?

**Comment by spheenik** [comment]
Looks like the string table holding the names was removed.
One would have to look whether they added something describing the modifier_class.
I will have some time in the next few days to work on clarity, and I will use it for finding out why people are getting [these a lot more](https://github.com/skadistats/clarity/issues/153). But I'll keep this in mind, maybe I'll find something along the way.

**Comment by spheenik** [comment]
I just looked into a super current replay (Vici vs. VGJ from Bucharest yesterday, match id [3764049023](http://replay133.valve.net/570/3764049023_2139059369.dem.bz2)). This replay properly contains the StringTable "ModifierNames". And you can use the modifier_class, to properly look up there.

I used the [stringtabledump example](https://github.com/skadistats/clarity-examples/tree/master/src/main/java/skadistats/clarity/examples/stringtabledump) to check.

No idea about the serial_num, but maybe you do not really need it?

**Comment by STRATZ-Ken** [comment]
Odd.  I put a output on OnStringTableCreated and the endpoint never gets hit on creating a table called “ModifierNames”.

Literally, I spent about 7 hours on this trying to find ways around before posting this git.  I swear :X

I will check again.

**Comment by spheenik** [comment]
There's a `@UsesStringTable` annotation, which you need to have.

The parameter "*" enables parsing all string tables, while the parameter "ModifierNames" would just enable the ModifierNames.

**Comment by STRATZ-Ken** [comment]
Can you jump on Steam chat? ☺

**Comment by STRATZ-Ken** [comment]
Works, My mistake on the ticket.  Closed.
