### ISSUE TITLE
Question!! get the date

### ISSUE THREAD

**Issue by ect1** [skadistats/clarity#161]
Is it possbile to get date when the game was ended?

**Comment by spheenik** [comment]
I do not think the date is in the replay.
It should be possible though to get at a date with Valve's or odota's api with a match id.

**Comment by STRATZ-Ken** [comment]
https://api.stratz.com/api/v1/match/{id}

**Comment by spheenik** [comment]
Thanks, Ken.

**Comment by ect1** [comment]
Thanks Ken. but I forgot to mention I'm targeting private match

**Comment by STRATZ-Ken** [comment]
> Thanks Ken. but I forgot to mention I'm targeting private match

This is not possible. You could however get the match id, go plus or minus a match id to find the closest match and it will give you a reasonable timestamp.
