### ISSUE TITLE
2.3 Broken

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#162]
Just something simple as 

```
if (cle.hasAttackerName()) {
	int attackNameId = cle.getAttackerNameIdx();
        StringTable stringTable = ctx.getProcessor(StringTables.class).forName("EntityNames");
        String name = stringTable.getNameByIndex(attackNameId);
}
```

Will return a null name (sometimes).

**Comment by spheenik** [comment]
sometimes = ITEM_PURCHASE?

**Comment by STRATZ-Ken** [comment]
Correct,  Just overall, finding “FromHero”  for me is nearly impossible.  Of the 2,000+ CombatLogs I would normally store, I am only getting like 50.  All due to FromHero never really converting from IndexId to a known npc_dota_hero_name.

**Comment by spheenik** [comment]
As we found out just now, it's "CombatLogNames", not "EntityNames".
Sometimes four eyes are barely enough :)

**Comment by STRATZ-Ken** [comment]
**JOKE ON **

Can we delete this post for stupidity.
 :)

**JOKE OFF**
