### ISSUE TITLE
Spectator String Tables Randomly are incorrect.

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#163]
```
@OnMessage(CDOTAUserMsg_SpectatorPlayerUnitOrders.class)
    public void onSpectatorPlayerUnitOrders(Context ctx, CDOTAUserMsg_SpectatorPlayerUnitOrders message) {
		try {
                int abilityId = message.getAbilityId();
	        int targetId = message.getTargetIndex();
                StringTable stringTable = ctx.getProcessor(StringTables.class).forName("EntityNames");
                DefaultEntity defaultEntityAbility = new DefaultEntity(abilityEntity);
                DefaultEntity defaultEntityTarget = new DefaultEntity(targetId );
                 if (stringTable.hasIndex(defaultEntityAbility.getStringTableIndex()))
                {
                        String entityName = stringTable.getNameByIndex(defaultEntityAbility .getStringTableIndex());
               }
               if (stringTable.hasIndex(defaultEntityTarget .getStringTableIndex()))
                {
                        String entityName = stringTable.getNameByIndex(defaultEntityTarget .getStringTableIndex());
               }
}
```

I threw together some sample code.  Randomly in replays, I will get incorrect stringtable entries.
I compared the dtClass to the StringTable and I get stuff like this.

Tue Mar 06 09:03:20 PST 2018 | 3767341538 | Missing Parser Names
CDOTA_Ability_Visage_Stone_Form_Self_Cast : visage_stone_form_self_cast

Tue Mar 06 11:58:40 PST 2018 | 3767569740 | Missing Parser Names
CDOTA_Item_EmptyBottle : special_bon

Tue Mar 06 11:58:33 PST 2018 | 3767576780 | Missing Parser Names
CDOTA_Item_PowerTreads : item_1ower_treads

Tue Mar 06 11:58:38 PST 2018 | 3767583891 | Missing Parser Names
CDOTA_Unit_Hero_Legion_Commander : npc_dota_hero_unique_omniknder CDOTA_Unit_Hero_Pugna : npc_dota_hero__2gna CDOTA_Unit_Hero_Legion_Commander : HP 720 : Level 1 : FromHero 104 : TIME -91 CDOTA_Unit_Hero_Pugna : HP 1295 : Level 14 : FromHero 45 : TIME 776 CDOTA_Unit_Hero_Pugna : HP 1215 : Level 11 : FromHero 45 : TIME 599 CDOTA_Unit_Hero_Pugna : HP 540 : Level 1 : FromHero 45 : TIME -91 CDOTA_Unit_Hero_SkeletonKing : HP 640 : Level 1 : FromHero 42 : TIME -91 CDOTA_Unit_Hero_SkeletonKing : npc_dota_hero_sttack_damage

I then take the same replay, and try again, and it doesn't do it.  I ended up putting in protection to read from the dtClass().ClassName instead but back to doing some string comparisons.

**Comment by spheenik** [comment]
Very, very strange. Is it possible for you to compile some code that reproduces this?
There is nothing indeterministic that I can think of in clarity, so running it again should always return the same value :/

**Comment by spheenik** [comment]
Fixed with [this commit](https://github.com/skadistats/clarity/commit/1c64edcf185789477e63da66a55aed44f83a3900).
Please check and close if working ;-)

**Comment by STRATZ-Ken** [comment]
12 hours, no errors.  Looks good.
