### ISSUE TITLE
robust check for hero (versus hero-creep or unit)?

### ISSUE THREAD

**Issue by austinmilt** [skadistats/clarity#164]
I am using the dtname CDOTA_Unit_Hero_* to check that an entity is a hero (in the colloquial sense), but this fails for some hero-like entities, e.g. CDOTA_Unit_Hero_Beastmaster_Boar. 

It appears that an additional condition I can check is for the entity's m_nPlayerOwnerID == -1. Is this a robust means to check that an entity is a hero, or is there some more straightforward or robust way to do this?

EDIT: I am also using the condition entity.getProperty("m_hReplicatingOtherHeroModel").equals(16777215) to check for illusions

**Comment by spheenik** [comment]
Does the boar have a m_nPlayerOwnerID or not?

**Comment by austinmilt** [comment]
Yes, it has m_nPlayerOnwerID and is some value other than -1 (in my specific case it was 4 because Beast Master was player 4, i.e. CDOTA_Unit_Hero_Beastmaster.m_iPlayerID == 4)

**Comment by spheenik** [comment]
If the Beastmaster himself has -1, then I'd say it is robust enough.

I think there's also a handle m_hOwningEntity (iirc), which is 16777215 if there is no owner (which should be the case for the hero), while for the boar it should contain a handle to the Beastmaster entity.

It's been awhile... So please check for correctness.

**Comment by spheenik** [comment]
...and I have to add that there might be hero entities that are owned, which I think is true for illusions (but this must be checked too). 
So it depends on whether you want the one hero entity that corresponds to a player, or any hero entity (including illusions).

**Comment by austinmilt** [comment]
There is m_hOwnerEntity, but, at least in my current example, the value is not 16777215 (null) for the boar.

I will leave this issue open a couple days in case another visitor has more info. (feel free to close it when you feel it's been long enough).

**Comment by austinmilt** [comment]
I have an additional condition used to filter out illusions (see edited OP).

**Comment by spheenik** [comment]
>  There is m_hOwnerEntity, but, at least in my current example, the value is not 16777215 (null) for the boar.

Correct. It is null when there is none, so it's not a hero if it' not null, which is the case for the boar.

**Comment by austinmilt** [comment]
I dont think so. None of the other entities (that are heroes) have a null value there either.
