### ISSUE TITLE
Having issues with positional info

### ISSUE THREAD

**Issue by pFnX** [skadistats/clarity#168]
Is it possible to find out which enemy heroes are close (lets say a 500 units range) to a certain player? I'm aware of the existence of "CBodyComponent.m_vecX and Y" and also the cells, but how could I, based on that, find out if there are other heroes near a certain player? (sorry if this is obvious but I'm really not finding an answer). 
Also, still regarding positional info, is there any way to find out if an hero is currently
in a lane or in the jungle area? If I had the values  of the areas of each lane I could simply check if my hero current position is within those areas, if yes the hero is "laning", else its "jungling" but how can i get those positional values of each lane?

It might be easy for some but I'm really lost on this and it is of extreme importance for me, could use some help!

Thanks in advance!!

**Comment by spheenik** [comment]
Here is some code that computes entity positions: [gist](https://gist.github.com/spheenik/3766744d47c170f25cf5). 
It's old, and Source 2 does not have the cellbits property, but you can use a constant value 7 instead.

You will get two X/Y coordinates (from both players you want to look at) this way, and you can compute `sqrt(sqr(x1-x2) + sqr(y1-y2))` to get the distance.

Regarding lanes: I think the way it's done is by looking at the player's positions in early game and matching those to map positions you consider being a certain lane. @howardchung might chime in to say how they do it. Afaik Dotabuff does not use player positional info, but click events by the players (it's an entity in the replay which gets emitted each time a player clicks somewhere on the map), and going from there.

**Comment by piaxar** [comment]
Hi, sorry for maybe a stupid question, but how can I get Entity object that has this property: "CBodyComponent.m_vecX" ?

Actually I try to parse coordinates for each player during the game. Am I on the right way to get it?

**Comment by spheenik** [comment]
@piaxar: Please do not hijack threads, open a new one!

That said, you can for example do `ctx.getProcessor(Entities.class).getByDtName("CDOTA_Hero_Antimage")` to get a hero entity.
