### ISSUE TITLE
How to get creep properties from Entity?

### ISSUE THREAD

**Issue by Wizard1209** [skadistats/clarity#169]
I tracking creeps by there Entities from @OnEntityEntered. But how can I find out are they dire or radiant, range or melee etc.

**Comment by spheenik** [comment]
They should have a `m_iTeamNum`-property, 2 being radiant and 3 dire.
Range or melee can be deduced from their max healh for example, or from their model (see the [Resources example](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/resources/Main.java)

**Comment by Wizard1209** [comment]
Thank you for answer. I have related question.
From example you send, what is skadistats.clarity.event.Insert(insert event or @Insert)?

**Comment by spheenik** [comment]
`@Insert` is clarity's do it youself dependency injection, and it will put the reference to that processor there.
It's basically the same as `ctx.getProcessor(ProcessorClass.class)`.

For finding out which properties are there, I recommend [clarity analyzer](https://github.com/spheenik/clarity-analyzer).
