### ISSUE TITLE
hi I want to get  voice data: commentary in pro matche

### ISSUE THREAD

**Issue by raehyuk** [skadistats/clarity#170]
Thanks in advance :)
I don`t see it in the example repository.
Can anybody help me getting voice data?

**Comment by raehyuk** [comment]
Thanks for reply :) 
is there any parser can get commentary voice data?

**Comment by spheenik** [comment]
There's no open source one that I am aware of.

**Comment by ykim** [comment]
@spheenik I've taken an interest in this as well. Do you know of a place to start to be able to decode the voice data?
