### ISSUE TITLE
Could i get protobuf from message of voice?

### ISSUE THREAD

**Issue by raehyuk** [skadistats/clarity#171]
Thanks a lot in advance :)

If i get protobuf message of voice i think i can parse voice from the protobuf message.

Thank you so much :)

**Comment by spheenik** [comment]
The raw protobuf messages are `CSVCMsg_VoiceInit` and `CCLCMsg_VoiceData`, iirc.

**Comment by spheenik** [comment]
@raehyuk: Did this help? Can we close this?
