### ISSUE TITLE
CSGO Can't get kill/damage events using OnCombatLogEntry

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#172]
Like with Dota 2 replays, we can use the OnCombatLogEntry event to get data when damage is done or heroes have been killed, how they were killed and by who. I tried using this for CSGO replays but none of the event functions fired off. I use a ControllableRunner and am able to get other data I need from the Context, pretty much the same way as with Dota 2. This is basically how I do it within my program:

```
    @OnCombatLogEntry
    public void onCombatLogEntry(Context ctx, CombatLogEntry cle) {
    	System.out.println("Combat Happened");
    	System.out.println(cle);
    }
```
I was wondering if there was another way to get damage and kill events as they happen or if I'm not doing it right for CSGO replays. Thanks!

**Comment by spheenik** [comment]
There simply is no combat log in CSGO replays. But: There's a lot more game events than in Dota. Round start, end, grenade explosions, lots of stuff there...

**Comment by TodorovicF** [comment]
@spheenik Perfect! I just looked at the data and it's pretty extensive, exactly what I was looking for. Thanks a lot!
