### ISSUE TITLE
Missing Entry 

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#173]
Match Id : 3958588567

At In-game time 3:20.85 Zeus loses a Teleporting buff.  This does not appear in the logs of @OnModifierTableEntry or @OnCombatLogEntry but does appear in the client CombatLogs.  I do see other heroes lose the teleporting buff, so its not an issue with the modifier itself, but for some reason Skadi does not see that record.

![image](https://user-images.githubusercontent.com/24981405/41610250-bb7dea3c-73ba-11e8-87f3-a667781e5ffb.png)

**Comment by STRATZ-Ken** [comment]
Found more instances of this.  

MatchId : 3960741857

At 3:06 Pudge picks up a Regen rune.  We never get the remove modifier at 3:25

![image](https://user-images.githubusercontent.com/24981405/41925929-e57a606e-793b-11e8-882e-5b6d5134bfb9.png)

**Comment by STRATZ-Ken** [comment]
@spheenik Any chance you got a minute or may have a lead to the cause?  Its causing my base logic of game recreation to fail under some weird conditions.  :(

**Comment by spheenik** [comment]
I was completely away and offline for a week, now I cannot d/l the replay (3960741857).
I am almost sure that I do not swallow/hide any combat log messages from you, so if it's not there, I don't really know why.

**Comment by STRATZ-Ken** [comment]
I'll get you another match tomorrow.  It's happening in a bunch of files and really throwing off my modifiers.

Sent from my iPhone

On Jul 4, 2018, at 11:16 AM, Martin Schrodt <notifications@github.com<mailto:notifications@github.com>> wrote:


I was completely away and offline for a week, now I cannot d/l the replay (3960741857).
I am almost sure that I do not swallow/hide any combat log messages from you, so if it's not there, I don't really know why.

-

**Comment by STRATZ-Ken** [comment]
https://expirebox.com/download/f1cfb5492a8bfce05d1e6564073821b4.html Will be there for 2 days.

**Comment by spheenik** [comment]
Just checked your replay (with the combat log example), and everything is there:
```
[00:08:39.394] npc_dota_hero_pudge receives modifier_rune_regen buff/debuff from npc_dota_hero_pudge
[00:08:58.823] npc_dota_hero_pudge loses modifier_rune_regen buff/debuff
```

**Comment by spheenik** [comment]
and I kind of expect you to do this basic validation before opening a bug yourself!

**Comment by STRATZ-Ken** [comment]
So after speaking with @spheenik I have come to the consensus is that ModifierTables is not pure and be careful when using it.  Regen did NOT come up for the removal of Pudge but did come up in the CombatLogs.  Just for others to know.
