### ISSUE TITLE
Detection of misses

### ISSUE THREAD

**Issue by Dmytro4** [skadistats/clarity#174]
Im trying to track misses from hero attacks.
1. Im using overhead_alerts. is there any other way to track misses of attacks?
2. I have **entindex** for target and attacker and seems like there is no instruments to check is attacker was hero or not because its always returning "**CDOTAPlayer**" but for **target_entindex** its ok. 
So is there any way to get kind of **source_entindex**? because having parent entindex is not what i need.
f.e. when enigma's eidolons attacking some hero (f.e. clinkz in strafe) i will have tons of misses messages with **source_player_entindex** = enigma .
3. **target_player_entindex** and **source_player_entindex** is always the same. By params names target and source entindex just cant be the same.

```
message_type: OVERHEAD_ALERT_MISS
value: 0
target_player_entindex: 4
target_entindex: 940
source_player_entindex: 4
```

**Comment by spheenik** [comment]
The entity-data in the replay is always only "the result" of what damage has been done.
I suspect (I am not sure) that you'd have to analyze the "animation phases" to find out if there was a "try to hit" which resulted in a miss. The overhead alerts are another way to get at this.

You can do `ctx.getProcessor(Entities.class).getByIndex(idx)` to get at the player entity.
If this returns a CDOTAPlayer it means that one of the entities controlled by the player did the damage.
