### ISSUE TITLE
Tracking of player clicks on units

### ISSUE THREAD

**Issue by Dmytro4** [skadistats/clarity#176]
Is there a way to track when some player clicked on enemy hero? Clicked not with spell but with left click to view his hp/mana/inventory/talents/etc. I guess it should be somewhere in CDOTAPlayer (because of same type of clicks with spectators) but i didnt found anything usefull(

**Comment by spheenik** [comment]
There are 2 messages that come to mind:

`CDOTAUserMsg_SpectatorPlayerClick`: occurs when the player (right-) clicks somewhere, maybe this also gets emitted when he (left-) clicks another player.

`CDOTAUserMsg_SpectatorPlayerUnitOrders`: occurs when the player issues an order for a unit (for example for casting a spell)

Other than that, I do not know if it's even in the replay. But if you are able to view a replay from the players perspective, and you can see the left click changing the selected unit, it must be somewhere.

**Comment by Dmytro4** [comment]
in `enum dotaunitorder_t` there is no such events as selecting of opponents and i checked `CDOTAUserMsg_SpectatorPlayerUnitOrders` on example replay and there was only default event such like buying of items or using of spells
`CDOTAUserMsg_SpectatorPlayerClick` didnt store any data in my replay that dont have any spectators in it.

Yeap, you are able to see which target is currently active in perspective of target. Even when you click on someone with spell you actually clicking with leftclick but you didnt select this target, you just doing some actions on it so i guess my question should be asked in another way - "**How to track which target is selected by player (i guess for spectators the same)**". 

So i spend some hours and i was right about `CDOTAPlayer `- its showed in `m_hSpectatorQueryUnit`, so whenever you change your target unit it will change on entity num that you can get from `CDOTA_Unit_Hero_.*` of each hero
ty

**Comment by spheenik** [comment]
Glad you found it.

One thing though: The *Spectator* messages should still be there in the replay, even if there's no one spectating. They are used when playing back the replay, to see clicks in player perspective.

Are you saying there were no such messages?

**Comment by Dmytro4** [comment]
I checked it on my private lobby 1x1 replay. I  didnt get any messages from this class (maybe of some mistakes in code) . I will check this again tmrw on few replays.

**Comment by Dmytro4** [comment]
yes, i didnt get anything with `@OnMessage(DotaUserMessages.CDOTAUserMsg_SpectatorPlayerClick.class)` from my 1x1 private lobby game and even from my pub game

**Comment by spheenik** [comment]
But you got unit orders, right?

**Comment by Dmytro4** [comment]
true

**Comment by spheenik** [comment]
Makes sense. Can we close this?

**Comment by Dmytro4** [comment]
sure

**Comment by Lamananas** [comment]
Hello, may i ask a question about this statement : 

> `CDOTAUserMsg_SpectatorPlayerClick`: occurs when the player (right-) clicks somewhere, maybe this also gets emitted when he (left-) clicks another player.

based on the description this is the event i want to detect, but just as Dmytro4 i can't get any messages from this class (i tried with 2-3 different replay.dem files)

any idea why ? Is there maybe something i need to activate first ? Could it be related to @UsesPlayerInfo ?

**Comment by spheenik** [comment]
Nope, PlayerInfo is unrelated. I suppose you try to get the messages with `@OnMessage(CDOTAUserMsg_SpectatorPlayerClick.class)`? If this is correct, and you do not get any, it means there are none in the replay.

**Comment by Lamananas** [comment]
Indeed that's what i tried and i did'nt get any message.

I bareley played DOTA 2 so maybe this is a stupid question but.. does that mean that none of the players ever right-clicked during the entire game (like, to move their character or select a creep to attack)? is that even possible ? O_O

**Comment by spheenik** [comment]
> does that mean that none of the players ever right-clicked?

Hehe, no :)

It means that Valve decided that they are not going to provide this message in the replay. 
Or, thinking about it, since it is named "...Spectator...", this means there were no spectators clicking units? Could you try a replay which was officially casted with an observer and see if you get any?

**Comment by Lamananas** [comment]
in opendota i downloaded the match with ID 3355640875 (https://www.opendota.com/matches/3355640875/overview) which (if i'm not mistaken) was part of the "DreamLeague Season 11" (https://fr.dotabuff.com/esports/series/1582398-dreamleague-season-11-major-psg-lgd-vs-infamous)

and yes,  i now get messages with `@OnMessage(CDOTAUserMsg_SpectatorPlayerClick.class)` =)
i don't know what a "spectator" is in DOTA 2  (yes i know veeeeeery very little about DOTA 2.. ), is it really one of the player or is it someone who watched the match live ? 
I am starting to suspect that `CDOTAUserMsg_SpectatorPlayerClick` doesn't necessarily mean that a **player** right-clicked somewhere.

also there is sadly no information about the position of the click but there is an entindex, order_type and target_index, so could i assume at the very least that this is not the message that is triggered when a player clicks somewhere on the map to move his hero ?

(P.S : thank you very much for your help, i hope i'm not annoying you too much ^^)

**Comment by spheenik** [comment]
A spectator is a spectator! :)
A person that watches the game. So my comment was wrong, and I fixed it.

So, what about `CDOTAUserMsg_SpectatorPlayerUnitOrders`? Does it have the information you need?

**Comment by Lamananas** [comment]
it seem so to me.

I get messages with `CDOTAUserMsg_SpectatorPlayerUnitOrders` in every match i try, from those messages i can either retrieve a position (probably when the player clicks somewhere in the map to move his hero) or a target_index (probably the entity on wich the player clicked, like a creep or another player).

so that works for me, thank you very much for your help ! =D
