### ISSUE TITLE
Detect whether entity belongs to hero?

### ISSUE THREAD

**Issue by Dmytro4** [skadistats/clarity#177]
Hey! 
Im trying to get differences of entity properties between real heroes and summoned units or illusions.
With help of Clarity analyzer i compared `CDOTA_Unit_Hero_PhantomLancer` properties between real hero and illusions and only difference that i found to compare illusions with real hero is `m_hReplicatingOtherHeroModel` that is 16777215 for hero and is the value `m_hInventoryParent` of real hero for illusions. To cut summoned units i found `m_bIsSummoned`.
Is there an easier way to detect real hero in `OnEntityPropertyChanged` and is cutting of m_hInventoryParent and m_hReplicatingOtherHeroModel is enough to detect real one?

**Comment by spheenik** [comment]
16777215 means "null handle" in Source 2. So if an entity has this as `m_hReplicatingOtherHeroModel`, it means it is not replicating. If it's != 16777215, this will be the handle of the hero entity it is replicating.

I think checking `m_hReplicatingOtherHeroModel` is enough, and I don't know of an easier way (it's easy enough anyway...)

**Comment by Dmytro4** [comment]
yeap, its 256³ but i have doubts about `m_hReplicatingOtherHeroModel ` because Morphling can replicate other heroes model and i guess this value also should show this. 
I will try to check this later in some replays with morph.

**Comment by spheenik** [comment]
Very interesting point, please keep me updated on what you find.

**Comment by Dmytro4** [comment]
yes, `m_hReplicatingOtherHeroModel ` of Morph is changing while he is in ulti form of another hero with entity of replicated hero. So this method is not enough to cut at least illusions.
I guess i found the way of connection between `CDOTAPLayer `and hero entity. 
`m_hModifierParent `or Hero entity is the same as `m_hAssignedHero ` for `CDOTAPlayer ` so you just need to compare it. This (as far as i understand it) should cut any illusions or other units like meepo clons or Arc warden ulti because there could be only one value in `m_hAssignedHero `
```
Integer owner = (Integer)getEntityProperty(e, "m_hOwnerEntity", null);
Entity ownerEntity = ((Entities)ctx.getProcessor(Entities.class)).getByHandle(owner.intValue());
if(((ownerEntity.getDtClass().getDtName()).toString()).equals("CDOTAPlayer")&&
getEntityProperty(ownerEntity, "m_hAssignedHero", null).equals(
getEntityProperty(e, "m_hModifierParent", null))){
...
}
```

**Comment by Dmytro4** [comment]
p.s. When player disconnects from the game then you cannot track his model properly with the way i said to. In my case this is actually what i needed, so if player typed "gg" and disconnects from the game then any further actions (if he will not recconect) will not be tracked
