### ISSUE TITLE
How can i parse wards and heroes at once

### ISSUE THREAD

**Issue by EvO-E** [skadistats/clarity#179]
@OnEntityPropertyChanged(classPattern = "CDOTA_NPC_Observer_Ward.", propertyPattern = "CBodyComponent.m_cell.")
I cannot make this parse heroes and wards
It either parses wards or heroes
I even tried putting the whole main function in another file and calling it with different args and it still didnt work

**Comment by spheenik** [comment]
I don't get what you are trying to archieve. Please try to describe it again.

**Comment by EvO-E** [comment]
Okay So I need to get the position of wards and heroes, but I can't repeat the annotation function, I tried everything, either I can get wards or heroes.

**Comment by spheenik** [comment]
Post your code.

**Comment by spheenik** [comment]
While I am waiting, `classPattern` and `propertyPattern` are regular expressions. So, if you want hero or observer ward, you can use `(CDOTA_Hero_.*|CDOTA_NPC_Observer_Ward)`

**Comment by EvO-E** [comment]
What about both of them at the same time

**Comment by EvO-E** [comment]
`package skadistats.clarity.examples.propertychange;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import skadistats.clarity.model.Entity;
import skadistats.clarity.model.FieldPath;
import skadistats.clarity.processor.entities.*;
import skadistats.clarity.processor.runner.Context;
import skadistats.clarity.processor.runner.SimpleRunner;
import skadistats.clarity.source.MappedFileSource;
import skadistats.clarity.source.Source;
import skadistats.clarity.model.s2.S2CombatLogEntry;
import javax.vecmath.*;
import skadistats.clarity.decoder.Util;
import skadistats.clarity.processor.resources.Resources.Entry;
import skadistats.clarity.model.CombatLogEntry;
import skadistats.clarity.processor.gameevents.OnCombatLogEntry;
import skadistats.clarity.processor.entities.OnEntityPropertyChanged;






@UsesEntities
public class Main {
    
    private final Logger log = LoggerFactory.getLogger(Main.class.getPackage().getClass());
    
    
    static Context ctx; static Entity e; static FieldPath fp;
    public void run(String[] args) throws Exception {
        long tStart = System.currentTimeMillis();
                Source source = new MappedFileSource("C:\\Users\\RaiN\\Desktop\\replay.dem");

        new SimpleRunner(source).runWith(this);
        
        
    }
 
  
   @OnEntityPropertyChanged(classPattern = "CDOTA_Hero_.*|CDOTA_NPC_Observer_Ward", propertyPattern = "CBodyComponent.m_cell.*")
   
    public void onEntityPropertyChanged(Context ctx, Entity e, FieldPath fp) {
       
        
        System.out.format(
                "%6d %s: %s = %s\n",
                ctx.getTick(), 
                e.getDtClass().getDtName(),
                e.getDtClass().getNameForFieldPath(fp),
                e.getPropertyForFieldPath(fp)
        );
    }

    
public static float getVecOrigin(Entity e, int idx) {
        Object v = e.getProperty("m_vecOrigin");
        if (v instanceof Vector2f) {
            float[] v2 = new float[2];
            ((Vector2f) v).get(v2);
            return v2[idx];
        } else if (v instanceof Vector3f) {
            float[] v3 = new float[3];
            ((Vector3f) v).get(v3);
            return v3[idx];
        } else {
            throw new RuntimeException("unsupported vector found");
        }
    }
    public static final int MAX_COORD_INTEGER = 16384; 

    public static float getX(Entity e) {
        int cellBits = 7;
        int cellX = e.getProperty("m_cellX");
        return cellX * (1 << cellBits) - MAX_COORD_INTEGER + getVecOrigin(e, 0) / 128.0f;
    }

    public static float getY(Entity e) {
        int cellBits = 7;
        int cellY = e.getProperty("m_cellY");
       return cellY * (1 << cellBits) - MAX_COORD_INTEGER + getVecOrigin(e, 1) / 128.0f;
    }
    public static void main(String[] args) throws Exception {
        OBSParser HeroParser = new OBSParser();
        HeroParser.run(args);
        new Main().run(args);
      
       
    }

}
`

**Comment by EvO-E** [comment]
https://gist.github.com/EvO-E/4080c23780599f36c6360532185809c6

**Comment by EvO-E** [comment]
This might seem horrible but it works "|CDOTA_Hero_.*|CDOTA_NPC_Observer_Ward_.*|CDOTA_NPC_Observer_Ward|"

**Comment by spheenik** [comment]
So it's working now?

**Comment by EvO-E** [comment]
Well it works with regex, but writing 2 separate methods didn't work, it was one of the few first things i tried.

**Comment by spheenik** [comment]
This would be a bug. Can you provide a small example reproducing the bug?

**Comment by EvO-E** [comment]
Just to be clear, why did you mean by 2 separate methods? Because you can't use @onEntityPropertyChanged more than once. And I tried taking the onEntityPropertyChanged class and duplicating it and then creating a second instance of @onEntityPropertyChanged but it doesn't work. It gives an exception that the second class has is not pointing to a listener or something. I also saw you were using pattern so I went here https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html
But the only operator that would work would be | and it's random because other operators can only let you retrieve elements that are followed BY something

**Comment by EvO-E** [comment]
I managed to get multiple values using your Mana example like this
Entity e = item.getValue();
            FieldPath cx =  e.getDtClass().getFieldPathForName("CBodyComponent.m_cellX");
            FieldPath cy =  e.getDtClass().getFieldPathForName("CBodyComponent.m_cellY");
            FieldPath vx =  e.getDtClass().getFieldPathForName("CBodyComponent.m_vecX");
            FieldPath vy =  e.getDtClass().getFieldPathForName("CBodyComponent.m_vecY");
            FieldPath team = e.getDtClass().getFieldPathForName("m_iTeamNum");
            FieldPath HeroLevel = e.getDtClass().getFieldPathForName("m_iCurrentLevel");
            FieldPath Health = e.getDtClass().getFieldPathForName("m_iHealth");
