### ISSUE TITLE
Tracking players position (X,Y) on the map

### ISSUE THREAD

**Issue by mehdi-kaytoue** [skadistats/clarity#18]
Hello there, 
thanks a lot for the great job your are doing with this api!
I was wondering if its possible to track the position of the players
and the items they buy accross time. 
What about the minions also? Are they tracked with your api?

Thanks a lot for your reply,
cheers,
Mehdi

**Comment by uSide** [comment]
http://pastebin.com/wEkmMSZq

Anyone know's id for Oracle?

**Comment by spheenik** [comment]
> http://pastebin.com/wEkmMSZq
> 
> Anyone know's id for Oracle?

Nope.

But I know what e == null means: The hero has not been picked yet :)

**Comment by mkmkmkmk** [comment]
From  https://github.com/dotabuff/d2vpk/blob/master/dota_pak01/scripts/npc/npc_heroes.txt
it says 111

**Comment by Chonchonts** [comment]
Hi,

I have some difficults to get the name of one object.

For example, I want to get the first item (e = Entity object and ctx = Context in event):

 ```java
int handle = (int)e.getProperty("m_Inventory.m_hItems.0000");
             
                    if (handle != 2097151) {
                        String itemName = ctx.getProcessor(Entities.class).getByHandle(handle).getProperty("m_iName");
                    }
```
But I have always a null value.

And with the following handle:

 ```java
  int handle = (int)e.getProperty("m_hMyWearables.0000");
```
I have the m_iName  empty (sry for the formatting :p):
+-------+-----------------------------------------------------------------------------------------+--------------+
|    59 | m_iParentAttachment                                                                     | 0            |
+-------+-----------------------------------------------------------------------------------------+--------------+
|    60 | m_iName                                                                                 |              |
+-------+-----------------------------------------------------------------------------------------+--------------+
|    61 | movetype                                                                                | 0            |
+-------+-----------------------------------------------------------------------------------------+--------------+

Finally, I search the items in the 6 slots.

P.S : I have Clarity SNAPSHOT 2.1
Cheers,

**Comment by spheenik** [comment]
Hey,
your code looks right. It might well be true that I broke something. Maybe @howardchung can say a word about the latest snapshot's ability to read S1 entities correctly. I am to tired now to look into it, real life needs attention. If it doesn't clear up, I'm gonna look into it, tomorrow or the day after.

Also, can you give the match id?

**Comment by ykim** [comment]
@Chonchonts : If you are parsing Source 1 replays, I highly recommend using clarity 2.0. The 2.1 snapshot has changed a lot of things in how the Entity operates. Can you try that and see if it helps? In addition, can you provide a replay along with what Entity you were looking at? I can take a look and see what's going on.

**Comment by Chonchonts** [comment]
Hi,

Thanks for the replies, but it's my fault :X. There are few items at the start of the game with empty "m_iName". I make some conditions and I have succeeded in recover data.
But it's still are to me to understand the different types of items attributes.
I understand this: m_Inventory.m_hItems.0000  but why 14 slots ? 6 slots + stash?
Also: bcc_localdata.m_hMyWeapons.0015 to bcc_localdata.m_hMyWeapons.0048 is quite strange for my too.
Finally, I search which key on the keyboard is assigned by the player to each 6 slots of items and each m_hAbilities, its possible?

**Comment by Anders-Lunde** [comment]
Hi guys. I'm really new to java programming so I'm dealing with lots of newbie problems at once here. My ultimate goal is to dump to a text file all the xy positions of all 10 players during the entire dota2 replay, say every second or so. I tried downloading the clarity project as zip file, extract it, open it in eclipse as a maven project, and then I inserted the code from http://pastebin.com/wEkmMSZq  (by mehdi-kaytoue) into a main.java file with the package/directory skadistats.clarity.examples.simple. The problem seems to be that the following imports are not found:

skadistats.clarity.match.Match;
skadistats.clarity.parser.Profile;
skadistats.clarity.parser.TickIterator;
com.dota2.proto.Demo;

The following imports seems to be unproblematic:

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import skadistats.clarity.model.Entity;
import skadistats.clarity.Clarity;

Am I doing something wrong? Is this a result of the new Dota2 patches (source2)? Any advice would be greatly appreaciated!

**Comment by spheenik** [comment]
Yes, the code is for Clarity 1, which was loooooong ago :)
Example code I recommend [in a recently closed issue](https://github.com/skadistats/clarity/issues/126#issuecomment-272269084), as well as [Opendota's parser](https://github.com/odota/parser/blob/master/src/main/java/opendota/Parse.java). Please open a new issue when you have questions, and do not revive such an old one!

**Comment by spheenik** [comment]
Oh and regarding getting positions on the map, [Clarity Analyzer has code that does this](https://github.com/spheenik/clarity-analyzer/blob/master/src/main/java/skadistats/clarity/analyzer/main/icon/EntityIcon.java)

**Comment by joram56** [comment]
@spheenik The link in your post above has expired, can you provide a new link for where Clarity gets positions on the map?

**Comment by spheenik** [comment]
Here is a more recent example: https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/position/Main.java#L165-L171

The whole example does almost what you want to achieve, it will print a line whenever a hero's position changes.
