### ISSUE TITLE
m_ihealthState doesn't change through out the game

### ISSUE THREAD

**Issue by EvO-E** [skadistats/clarity#180]
The attribute doesn't change through out the game. Not sure if bug or I'm missing something.

**Comment by spheenik** [comment]
It definitely should. But without an example I cannot tell you if you are missing stuff or not!

**Comment by spheenik** [comment]
Ah, I guess you probably mean `m_iLifeState`? 0 = alive, 1 = dying animation, 2 = dead

**Comment by EvO-E** [comment]
ye but it doesn't change. I parsed a whole replay with it never changing. Unless im doing something wrong.

**Comment by spheenik** [comment]
Run [this](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/lifestate/Main.java), if it works for your replay, you're doing something wrong.
