### ISSUE TITLE
Tracking of taunts

### ISSUE THREAD

**Issue by Dmytro4** [skadistats/clarity#181]
Is there a way to get taunt events? I tried to catch `CHAT_MESSAGE_TAUNT ` but didnt get anything

**Comment by spheenik** [comment]
I've got to pass on this one. Only thing I can image is animation related, or because of the sound the taunt emits, but idk.

**Comment by spheenik** [comment]
Solved by @BusyLivingDota in a nice way in
https://github.com/skadistats/clarity/issues/262
