### ISSUE TITLE
INT Bugged on new replays.

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#189]
Match Id : 4259525978
Latest 2.4 Snapshop (and same on 2.3 snapshots).
m_flIntellectTotal on the Player Entity has Int as -2147483648 to start the game.  I am unsure if this is a Dota 2 replay issue, or a bug in Skadi.  But leaving it here as I am walking out the door for Vacation.

About 20,000 replays so far have this issue within the last 24 hours.

**Comment by spheenik** [comment]
Hey, I suspect this was also because of the recent bugfix. Please retest with 2.4.
