### ISSUE TITLE
Is it possible to use clarity for realtime event parsing?

### ISSUE THREAD

**Issue by tonicebrian** [skadistats/clarity#193]
I'd like to build a client for providing realtime analytics on a running game and I don't know if clarity can be used as an spectator and provide same functionality that already provides for replayed matches

**Comment by spheenik** [comment]
What you can do is start recording a demo in the console, and then using a [LiveSource.java](https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/source/LiveSource.java) get at the data while it's written.
