### ISSUE TITLE
m_iPlayerID is 0 for all Heros?

### ISSUE THREAD

**Issue by zicongma** [skadistats/clarity#194]
Hi there,
I am trying to retrieve the player information every time that a Hero entities is updated (the player that controls the hero). From what that I have read [here](https://github.com/skadistats/skadi/wiki/DT_DOTA_BaseNPC_Hero) I should use the "m_iPlayerID" field. However, after using clarity analyzer and analyzing a few games, I realised that this field is 0 for most of the field, if not all. I'm not sure if this is the expected behaviour. However, if this is the case, how else can I extract the information of the player that controls hero?

**Comment by spheenik** [comment]
I just did a quick look at 3 replays, and for both of them `m_iPlayerID` is properly set on the `CDOTA_Unit_Hero_XXX` entities. Not sure what's going on. Can you elaborate on what exactly your code is doing? (Or provide a match id/demo so I can have a look?)

**Comment by zicongma** [comment]
Hi there, 

Thanks for getting back to me so quickly.
So basically I first looked at clarity analyzer with match id of 4439579013, and for this match all the <CDOTA_Unit_Hero_XXX> entities are all 0, at least so by the looks of it.

I also wrote some code and that prints for each entity update on hero, the m_iPlayerID and it seems like all I get is 0 as well.

**Comment by spheenik** [comment]
Ya, the replays I looked at where older, so maybe they stopped to fill this recently. Anyway, what you can also do is look at `m_hOwningEntity`, which is a handle to the owning `CDOTAPlayer` entity. You basically do `ctx.getProcessor(Entities.class).getByHandle(m_hOwningEntity)` to get to it. HTH.

**Comment by zicongma** [comment]
Thanks a lot Martin,
It works wonders, except for one problem.
I get NullPointer for the player sometimes and I'm not sure why this is happening. Like most of the time its working, but sometimes I just get null.
`    @OnEntityUpdated
    public void onUpdated(Context ctx, Entity e, FieldPath[] updatedPaths, int updateCount) {
        Float TIME_EPS = (float) 0.0001;

        if (!(isHero(e))) {
            return;
        }

        Entities entities = ctx.getProcessor(Entities.class);
        float real_time = getRealGameTimeSeconds(entities);

        if (real_time < TIME_EPS) {
            return;
        }

        for (int i = 0; i < updateCount; i++) {
            FieldPath path = updatedPaths[i];
            String pathName = e.getDtClass().getNameForFieldPath(path);
            Entity player = ctx.getProcessor(Entities.class).getByHandle((int) e.getProperty("m_hOwnerEntity"));
            if (player == null) {
                System.out.println("Somehow got null " + e.getProperty("m_hOwnerEntity"));
                names.add(e.getProperty("m_hOwnerEntity").toString());
            }
            System.out.format("Entity: %s, Property: %s, Value: %s, ID: %s, Time: %s\n", e.getDtClass().getDtName(), pathName, e.getPropertyForFieldPath(path), player.getProperty("m_iPlayerID"), real_time);
        }
    }`

**Comment by spheenik** [comment]
Not every entity is a hero, and some of them have no owning entity.
I think you misunderstand what `@OnEntityUpdated` does: It gets called whenever an entity `e` gets some of its properties updated. For each call, it will always be the same entity `e`, so it makes no sense to loop over all the updated paths and repeatedly lookup the owner of it. It will always be the same, since `e` is invariant.

**Comment by spheenik** [comment]
Damn, just saw you check for heros... So, I am not entirely sure what's happening, but some pointers:

There are Hero illusions (although they should theoretically also be owned by a player). You can detect that by checking `m_hReplicatingOtherHeroModel`. If it is 16777215, it's no illusion, otherwise it's a handle to the real hero entity it is a replicate of.

An other thing is that during the time clarity fires all `@OnEntityUpdated` events, the entities can be in an inconsistant state. For for example, if an entities owning entities' `m_hOwnerEntity` is updated, it might be that the entity that's referenced is created a bit later.

**Comment by spheenik** [comment]
I just looked at the replay, and something with entity decoding is *very wrong*

**Comment by spheenik** [comment]
So: There was indeed a bug in clarity with recent replays, causing it to wrongly parse entity updates. It did not know the type Vector4D. I fixed this and pushed a new snapshot (2.4)

@jcoene, @STRATZ-Ken: Heads up!

**Comment by spheenik** [comment]
(`m_iPlayerID` is back to normal, now)

**Comment by zicongma** [comment]
Thanks a lot martin, m_iPlayerID works well now.
Just out of curiosity regards to the null ehandel, I wrote some code to check
```
            Entity player = ctx.getProcessor(Entities.class).getByHandle((int) e.getProperty("m_hOwnerEntity"));
            if (player == null) {
                System.out.println(e.getProperty("m_hOwnerEntity") + " " + e.getDtClass().getDtName() + " " + e.getProperty("m_hReplicatingOtherHeroModel"));
            }
```
I got about 11500 entries and all the m_hReplicatingOtherHeroModel is 16777215. I guess it still could be the expected behaviour given your last point.

Anyways I can work with m_iPlayerID for now, thanks a bunch.

**Comment by spheenik** [comment]
16777215 is a special handle, meaning "not set".
