### ISSUE TITLE
How to find out which player it is in CDOTA_DataRadiant and CDOTA_DataDire?

### ISSUE THREAD

**Issue by zicongma** [skadistats/clarity#195]
So I'm trying to find out which player it is in the DataRadiant and DataDire entities to access the player's gold xp and etc. 
I'm curious on how I would relate each entry to players. 

My current guess is that the indices corresponds to the ones in CDOTA_Team.
For example in CDOTA_Team (m_iTeamNum = 2), player field at m_aPlayers.0000 would be the same as the one represented in DataRadiant (m_iTeamNum = 2) with field names starting with m_vecDataTeam.0000.

Is this the correct way of doing this? Or is there some better ways? Cheers.

**Comment by zicongma** [comment]
Also, what about CDOTA_PlayerResource?

**Comment by spheenik** [comment]
You can use `m_iPlayerID` for that: -1 means neither Radiant nor Dire, 0-4 means DataRadiant, 5-9 means DataDire. IIRC, you can use the player ID directly for `CDOTA_PlayerResource`

**Comment by zicongma** [comment]
Right so based on what you said, m_iPlayerID is used in the CDOTA_PlayerResource, so player with a id of 1 would have fields starting with 0/1/... in this entity, that solves my problem for this entity. However, regards to the CDOTA_DataRadiant and CDOTA_DataDire entities, the fields range from 0-4 in both files, how exactly would I know which field is representing which player?

Cheers.

**Comment by spheenik** [comment]
0-4 -> DataRadiant 0-4
5-9 -> DataDire 0-4

**Comment by zicongma** [comment]
Oh.. Didn't expect it to be this simple haha.
So the ordering of m_aPlayers.000n in CDOTATeam is something completely different then?
Apologize if these seem like dumb questions.
