### ISSUE TITLE
How should i get position accordinates using clarity?

### ISSUE THREAD

**Issue by Zony-Zhao** [skadistats/clarity#200]
Is there any info like "m_iTotalEarnedGold"? Or is there any other way to get position accordinates for creeps and heros?

**Comment by spheenik** [comment]
There's `CBodyComponent.m_cell[X,Y]` and `CBodyComponent.m_vec[X,Y]` on each creep and hero entity.
The position can be calculated as `cell * 128 + vec`.

Regarding total earned: [Here is some guidance](https://github.com/spheenik/clarity-analyzer/issues/8)

**Comment by spheenik** [comment]
I also suggest to run [clarity-analyzer](https://github.com/spheenik/clarity-analyzer) to explore the data.

**Comment by Zony-Zhao** [comment]
Thanks for reply! It helps a lot!New problems
1.How can I get entity's information like it in the clarity analyzer(at every tick I want) instead of "onEntitycreated"or"onEntityspawned".
2.And how to use a hero entity to get the the abilities and items? Do I need to cast like this: (HeroEntity)entity e?

**Comment by spheenik** [comment]
1. `ctx.getProcessor(Entities.class).getByIndex()` for example... There are other accessors on the `Entities` processor as well
2. m_hAbilities and m_hItems are handles.
You can do `ctx.getProcessor(Entities.class).getByHandle(*handle*)`  to get the entity for item/ability.

**Comment by Zony-Zhao** [comment]
Thank you!

**Comment by Zony-Zhao** [comment]
In many issues spheenik answerd a name for entity,and some names for properties,like CDOTA_XXXX and m_iXX. Is there a list or something show all these infos? And this list is made offcialy or made by clarity programmers? 
Apologize if this seems dumb questions, but as i see, this would help a lot of beginners using clarity.

**Comment by Zony-Zhao** [comment]
Let me answer this myself. 
@OnEntityPropertyChanged()
    public void onChanged(Entity e, FieldPath fp) throws Exception {
        if(e==null){return;}
        if (e.getDtClass().getDtName().startsWith("CDOTA_Unit_Hero_")) {return;}
        if (e.getDtClass().getDtName().startsWith("CDOTA_Item")) {return;}
        if (e.getDtClass().getDtName().startsWith("CIngameEvent")) {return;}
        if (e.getDtClass().getDtName().endsWith("Wearable")) {return;}
        if (e.getDtClass().getDtName().endsWith("Ability")) {return;}
        if(e.getDtClass().getDtName().equals("CWorld")){return;}
        if(e.getDtClass().getDtName().equals("CDOTAPlayer")){return;}
        if(e.getDtClass().getDtName().equals("CDOTATeam")){return;}
...
...
   System.out.println(e.getDtClass().getDtName());
}
I just print all the class name of all kinds of entities and list them there.(Including courier, tower, ingameEvent_TI9, entity that i never thought of). If you would like to check a certain entity's properties, just print it. The toString function is going to make a chart to show all the properties. Get it as you like.

**Comment by Zony-Zhao** [comment]
Hello! A Question on clarity!All the issue comments said that it's impossible to access the creep's name in game. Like creep_radiant_melee_upgraded.
However it is easy to get a stringtable called "Combatlog", which contains all kinds of neutrals, lane creeps' types. Is there any possiblity to access the names on this table?
(As you can see, in this table there is rock_golem, dark_troll etc.)

**Comment by Zony-Zhao** [comment]
Sorry.It seems I sent the wrong picture.

**Comment by spheenik** [comment]
`ctx.getProcessor(StringTables.class).forName("CombatLogNames").getNameByIndex()`

**Comment by spheenik** [comment]
To make clarity populate the string table annotate your processor with `@UsesStringTable("CombatLogNames")`
