### ISSUE TITLE
About getting Tree Entity

### ISSUE THREAD

**Issue by Zony-Zhao** [skadistats/clarity#202]
how to get infos about a tree entity?
I want to know which tree on this map has been cut down and where it is.

**Comment by spheenik** [comment]
There is an array with bits for each tree on the Data[Radiant|Dire|Spectator] entities (iirc).
Problem is, I do not know the mapping from bit to actual tree. You would have to extract that from the map data somehow...

**Comment by Zony-Zhao** [comment]
Thank you very much for remembering this.
We also noticed the WorldTreeState. However, we cant use it by getByHandle() or resources(like it when getting model).
And from m_bWorldTreeState.0000 to 0255, it is the same in Data[radiant|Dire|Spectator],it just repeats.


------------------ 原始邮件 ------------------
发件人: "Martin Schrodt"<notifications@github.com>;
发送时间: 2019年7月6日(星期六) 下午4:18
收件人: "skadistats/clarity"<clarity@noreply.github.com>;
抄送: "1668069501"<1668069501@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [skadistats/clarity] About getting Tree Entity (#202)




There is an array with bits for each tree on the Data[Radiant|Dire|Spectator] entities (iirc).
 Problem is, I do not know the mapping from bit to actual tree. You would have to extract that from the map data somehow...

**Comment by spheenik** [comment]
As I said: m_bWorldTreeState is a gigantic array of bits, each supposedly representing a single tree on the map. But I do not know which bit corresponds to which tree, and it will also change between different iterations of the map (I guess).

**Comment by Zony-Zhao** [comment]
How did you guys write the clarity?
Can I write a parser like clarity? For some games like LOL?Is it because of Valve's open source?
Is there any docs or info?

**Comment by spheenik** [comment]
There is no official documentation, so the info had to come from here and there.
Regarding LOL: I have no idea!

**Comment by Zony-Zhao** [comment]
Well then the 'here and there' refers to?Give me some key words or links plz.

**Comment by spheenik** [comment]
Man!
There are none, otherwise you would find stuff on google.
Why do you want to write something like clarity anyway?
And if you want to do so, why not read the source of clarity and port it?

**Comment by STRATZ-Ken** [comment]
No one that I know of has been able to determine this.  You could count the amount of trees cut, by looking when a value of the tree changes (but then divide by 2 since it could be a tree spawning).  Could also fail if Iron Branches are used a lot.  But I doubt we will ever find a way to map to the tree hash map.

**Comment by Zony-Zhao** [comment]
> No one that I know of has been able to determine this. You could count the amount of trees cut, by looking when a value of the tree changes (but then divide by 2 since it could be a tree spawning). Could also fail if Iron Branches are used a lot. But I doubt we will ever find a way to map to the tree hash map.

For temporary trees such as Furion's ability and iron branches, there is an extra entity created which has a class called temp_tree(or something like this).
