### ISSUE TITLE
how can i find all the runes spawning log？ i miss some runes which wasn't activated by heroes。how can i find the runes which wasn't activated by heroes。

### ISSUE THREAD

**Issue by xiaoyangmoa** [skadistats/clarity#206]

**Comment by spheenik** [comment]
There are Entities for each rune, called `CDOTA_Item_Rune`. Use clarity-analyzer to inspect a replay.
Whenever one gets spawned, you'll get an event `@OnEntityCreated` where the entity given will be such a rune.

**Comment by xiaoyangmoa** [comment]
thanks
