### ISSUE TITLE
How to retrieve Magical Resistance from Dota2 replay?

### ISSUE THREAD

**Issue by VladimirRyzhkov** [skadistats/clarity#207]
I tried to get MagicalResistance and figured out that there is only one property with similar name: m_flMagicalResistanceValue from CDOTA_Unit.* classes.
But it has the constant value 25.0 on every tick:

```
tick	unit	m_flMagicalResistanceValue
5622	CDOTA_Unit_Hero_Juggernaut	25.0
5624	CDOTA_Unit_Hero_Earthshaker	25.0
19601	CDOTA_Unit_Hero_Lina	25.0
37775	CDOTA_Unit_Hero_Zuus	25.0
64213	CDOTA_Unit_Hero_Juggernaut  25.0
73137	CDOTA_Unit_Hero_ArcWarden 25.0
```

Replay: http://replay145.valve.net/570/5006656170_682731911.dem.bz2

Is there another way to get real MagicalResistance?

**Comment by spheenik** [comment]
As written [here](https://github.com/skadistats/clarity-examples/issues/40) just now, it seems that the computed magical resistance is not propagated to the client - i.e. the field is never updated.

**Comment by VladimirRyzhkov** [comment]
I see. Thank you
