### ISSUE TITLE
[feature] log to file

### ISSUE THREAD

**Issue by KaiWangCanada** [skadistats/clarity#208]
Hi Skadistats, 

Carity is a wonderful project, I love it very much.

Now I'm trying to log out all the combat logs. It is really long, and unable to show all in the console.

I tried to config the log4j, but seems like I'm not skilled enough to do it right. Half an hour has passed and it is still not logging to a file.

I think a lot of people are having similar problems as me. Could you please add an alternative logback.xml configration file which log to a file, so that when people want to log to a file, they can simply overwrite the log to console one? It can save people like me a lot of time.

Thanks! Have a good day.

**Comment by spheenik** [comment]
I'd rather not do that, since it's completely unrelated to the project. 
But if you post your `logback.xml` here, I will have a look at it.

**Comment by KaiWangCanada** [comment]
Dear Spheenik, 

Thank you so much for the reply. Here is my logback.xml:

<configuration>
	<appender name="FILE" class="ch.qos.logback.core.FileAppender">
		<param>
			<file>c:/logfile.txt</file>
			<immediateFlush>"true"</immediateFlush>
			<threshold>"info"</threshold>
			<append>"false"</append>
		</param>
		<encoder>
			<pattern>%msg%n</pattern>
		</encoder>
	</appender>

	<logger name="skadistats.clarity" level="info" />

	<root level="info">
		<appender-ref ref="FILE" />
	</root>
	
</configuration>

I want to log to the file c:/logfile.txt, however it is not working. 

Thanks for your precious time :)

**Comment by spheenik** [comment]
If it works it works!
Good job :)

**Comment by KaiWangCanada** [comment]
Thanks, bro :)
