### ISSUE TITLE
Parse message to human readable json

### ISSUE THREAD

**Issue by maharjanraj** [skadistats/clarity#209]
Is it possible to parse message to json with keys as same as the variables from proto? Like we get when doing message.toString().

For e.g:
https://github.com/skadistats/clarity-protobuf/blob/master/src/main/proto/s2/s2_dota_gcmessages_common.proto

From above proto, if I want to parse CMsgDOTAMatch instance. 
What I expect is something like:
```
{
  players: [{account_id: xx, player_slot: x, hero_id: x, ...}, ...]
}
```

Currently when I convert the message to Json using Gson, I get:
```
{
  players_: [{accountId_: xx, playerSlot_: x, heroId_: x, ...}, ...]
}
```

**Comment by spheenik** [comment]
Short answer: Not that I know of...
Long answer: There is a class `JsonFormat` in protobuf 3+ that does conversion to JSON, but I do not know how/if the key conversion can be tinkered with. Maybe GSON lets you customize that somehow?

**Comment by spheenik** [comment]
Here is another lead: https://stackoverflow.com/a/46673110/1856400
