### ISSUE TITLE
Protect from Out of Range on getByIndex

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#210]
Example : 

```
@OnMessage(CDOTAUserMsg_SpectatorPlayerUnitOrders.class)
    public void onSpectatorPlayerUnitOrders(Context ctx, CDOTAUserMsg_SpectatorPlayerUnitOrders message) {
int abilityId = message.getAbilityId();
Entity abilityEntity = ctx.getProcessor(Entities.class).getByIndex(abilityId);
}

```
Match Id Example 5069162573 

Can we just return null on getByIndex if its outside the range?

**Comment by spheenik** [comment]
Hmm. Why? Throwing IndexOutOfRange is standard in these cases.

**Comment by STRATZ-Ken** [comment]
How so?  We dont control getAbilityId and we dont control getByIndex.

Maybe getAbilityId shouldn't return a possible EntityId, but would return a nullable int if its not connected to an Entity?

**Comment by spheenik** [comment]
Protobuf cannot return nullable. If the value is not set, the function `message.hasAbilityId()` will return false. 

What was the abilityId returned in this case?

**Comment by STRATZ-Ken** [comment]
I only looked at 3-4 of them.  The number was extremely high.  ~100,000.  There was 3 numbers within the match id I listed, that would fail.

**Comment by spheenik** [comment]
And in the case where it does not fail, it returns an entity that contains an ability?

**Comment by STRATZ-Ken** [comment]
It could be an Ability, Item, Npc, etc.

**Comment by spheenik** [comment]
Oh well, I prefer throwing ;-)
Catch it if you can!
