### ISSUE TITLE
Is there a function I can track the hero's position all the time?

### ISSUE THREAD

**Issue by wx930910** [skadistats/clarity#211]
Hi, I wonder is there any function under Entity (CDOTA_Unit_Hero) can help us to track the location for heros all the time?

Thanks!

**Comment by wx930910** [comment]
I found the CBodyComponent.m_vec and CBodyComponent.m_cell can be used to calculate the location for a hero, but I cannot find any function to return the time similar like the CombatLogEntry.getTimestamp() function. 
So may I ask is there a function under Entities return current game time? Thank you for any help you can provide!

**Comment by wx930910** [comment]
Hi I found that the click can be calculated by 1000 * ctx.getTick() / 30 so I just need to overwrite onEntityPropertyChanged function to get the context and then calculate hero position at each time.

Please correct me if I am wrong. Thank you!

**Comment by spheenik** [comment]
There are 30 ticks per second.

The context object can also be injected, like shown [here](https://github.com/skadistats/clarity-examples/blob/59d7030ba655ea4fba32899f2d1a42562f6b92f2/src/main/java/skadistats/clarity/examples/lifestate/Main.java#L15-L16)

**Comment by STRATZ-Ken** [comment]
if (gameTime != previousUpdateGameTime)
{
GetHeroEntityLocation and store. 
}

Use it where ever you need it. This will allow you to update at least 1 time per second (No reason to store each tick, as its way to much).

**Comment by XinpengLiu321** [comment]
Are those two functions still working in v2.5?
I want to extract the death position of heroes and currently my codes are like:
System.out.printf("%06d: %s at index %d has died at %d/%d\n", ctx.getTick(),e.getDtClass().getDtName(),e.getIndex(),(x axis value),(y axis value)) ; But I can't finger out how to call the functions.

**Comment by spheenik** [comment]
Please provide more code, I do not understand your issue/question.

**Comment by XinpengLiu321** [comment]
My code are copied from: 
clarity-examples/src/main/java/skadistats/clarity/examples/lifestate/
The original project prints the spawn/death event of entities, the output is like :
"009644: CDOTA_Unit_Hero_PhantomLancer at index 2285 has died"
Now I want to know the hero's position(no need to know all the entities) when it has been killed. 
The result I want to get is like:
"009644: CDOTA_Unit_Hero_PhantomLancer at index 2285 has died at 140/122"
Thank You!

**Comment by XinpengLiu321** [comment]
I already solved the problem,and the code is:
    public void onDied(Entity e) {
        System.out.printf("%06d: %s at index %d has died at (%d,%d)\n", ctx.getTick(), e.getDtClass().getDtName(), e.getIndex(),
        e.getPropertyForFieldPath(e.getDtClass().getFieldPathForName("CBodyComponent.m_cellX")),
        e.getPropertyForFieldPath(e.getDtClass().getFieldPathForName("CBodyComponent.m_cellY")));
    }
 please tell me if I am wrong. 
Thank you all the same!

**Comment by spheenik** [comment]
It is correct. If you want better precision, you can use:
```java
    private Vector getPosition(Entity e) {
        if (!e.hasProperty("CBodyComponent.m_cellX")) {
            return null;
        }
        return new Vector(
                getPositionComponent(e, "X"),
                getPositionComponent(e, "Y"),
                getPositionComponent(e, "Z")
        );
    }

    private float getPositionComponent(Entity e, String which) {
        int cell = e.getProperty("CBodyComponent.m_cell" + which);
        float vec = e.getProperty("CBodyComponent.m_vec" + which);
        return cell * 128.0f + vec;
    }
```

**Comment by reacheight** [comment]
@spheenik How do you know a cell size is a 128 x 128 x 128?

**Comment by spheenik** [comment]
@reacheight Hmm, it has just always been this way. In Source 1 (before Dota 2 Reborn), the cell size was still encoded (as having 7 bits -> 128). They removed that in Source 2, so it certainly looks like it's constant until eternity in their eyes.

**Comment by reacheight** [comment]
Oh, okay, thanks. I use this formula and it seems to be correct (minus ~8192 to set the origin to the bottom left of the map), just trying to make sure I understand what I'm doing xd.
