### ISSUE TITLE
Who picked up the neutral item?

### ISSUE THREAD

**Issue by xiaoyangmoa** [skadistats/clarity#214]
I want to get this information from the pop-up messages (pick neutral items) on the right side during video playback, but I don't know how to get these pop-up messages

**Comment by spheenik** [comment]
Heads up: Did a protobuf update today, and there are now new UserMessages:

`CDOTAUserMsg_FoundNeutralItem, CDOTAUserMsg_OutpostCaptured, CDOTAUserMsg_OutpostGrantedXP`
