### ISSUE TITLE
Sorry to bother you. I want information about outposts after the game and the new game, but I can't

### ISSUE THREAD

**Issue by dp12321** [skadistats/clarity#215]
In the current version, I can't get any information about outposts. I don't know why

**Comment by spheenik** [comment]
I did not have time yet to look into how they are implemented. So I'll have to pass. Anyone else?

**Comment by dp12321** [comment]
Thank you very much, You've had a long day 
 I found that  targetName=npc_dota_watch_tower  is in @ oncombatlogentry, which helps me a little

**Comment by spheenik** [comment]
Heads up: Did a protobuf update today, and there are now new UserMessages:

`CDOTAUserMsg_FoundNeutralItem, CDOTAUserMsg_OutpostCaptured, CDOTAUserMsg_OutpostGrantedXP`

**Comment by dp12321** [comment]
Thank you! You are so handsome, I will try it (it seems that my previous code needs to be invalidated).

**Comment by dp12321** [comment]
Sorry to disturb you again. I found that CDOTAUserMsg_FoundNeutralItem.getPlayerId() = - 1 will appear when using CDOTAUserMsg_FoundNeutralItem. I can't get which team found it.  So, how to get which team to find it

**Comment by spheenik** [comment]
If the game does not set the player id, then you're pretty much out of luck.
Maybe watch for new items, and if they are neutral, wait for them to show up in an inventory...

**Comment by dp12321** [comment]
Thank you, Happy Christmas Eve! You are right, but sometimes neutral items may be updated. At this time, they cannot be judged accurately, and the names of neutral items are sometimes incorrect.

**Comment by spheenik** [comment]
> and the names of neutral items are sometimes incorrect.

Can you elaborate? What version are you using? How do you get the name? Is it wrong only sometimes or always?

**Comment by dp12321** [comment]
Version is clarity 2.4.1；  
 @OnTickStart
    public void onTickStart(Context ctx, boolean synthetic) {
// Here debugger can get all the objects in the game
ctx.getProcessor(Entities.class).dtClasses.byDtName
}
