### ISSUE TITLE
Entry variable names manual or Documentation

### ISSUE THREAD

**Issue by vbashiri** [skadistats/clarity#216]
Hello there!

Is there any guide or manual for entry variable names? Like what is "CBodyComponent.m_hParent" and which "m_hItems.0015" is corresponding for which item slot?
Even if there is some info, it would be much help. in other issues mentioned, "Properties starting with m_h are handles". What other stands for, like m_f, m_i, etc?

Thanks in advance.

**Comment by spheenik** [comment]
f = float
i = integer
h = handle (this is like a pointer to another entity, which you can get to if you do `ctx.getProcessor(Entities.class).getByHandle(handle)`

Which one is which slot, I dont know, I would think that it's in the order the slots are filled when you buy.

**Comment by vbashiri** [comment]
Thanks a lot.
Is there any manual or documentation?
to look for meaning of these kinds of names like "CBodyComponent.m_hParent"?
