### ISSUE TITLE
Exception  highLowMultiplier is zero! for new replays

### ISSUE THREAD

**Issue by Dmytro4** [skadistats/clarity#217]
Hey man!
Long time no see. I tried to parse some new replays and i get this error. Is this only for me?
Can you please help me?
![image](https://user-images.githubusercontent.com/22562710/72645286-f573f780-397b-11ea-9456-ff6f22a177af.png)

**Comment by Dmytro4** [comment]
I tried to build with 2.2,2.3,2.4 snapshots, same error
2.5 is not working for my code

**Comment by Dmytro4** [comment]
reading through errors i found that i need to change snapshot version to 2.4.1 
It could be good to point this somewhere for new users (that <2.4.1 snapshots are not working for new replays?)
https://github.com/skadistats/clarity/issues/212
can be closed <3

**Comment by spheenik** [comment]
there is a 2.4.1 which contains a fix for this

**Comment by spheenik** [comment]
(and 2.4 code should work fine with 2.5, so if you describe the problem I might help)

**Comment by STRATZ-Ken** [comment]
I just tried 2.5 for the first time. I believe I am getting the same issue, I am unable to see a full stacktrace.

I did catch the exception with `com.sun.jdi.InvocationException occurred invoking method.`

To reproduce, use latest 2.5 snapshot.  When Entities are created, I store them for looping later.  

Example, every time you see a building, store it in an entity. Each new tick, loop through the Buildings.  In match id : 5242242924 you will see at 590 seconds into the game, the 4th tower loses its record completely, and thus created a NPE.

**Comment by STRATZ-Ken** [comment]
My issue was solved as the issue with dead entities was fixed.  I was still tracking dead Entities.  Thanks,

**Comment by huertasdanny** [comment]
@STRATZ-Ken can you help me debug my case? I'm currently using the clarity-examples library but I get similar errors as the ones on this thread. Using 2.5 Snapshot the error is:
![image](https://user-images.githubusercontent.com/4691064/74995520-faf2b080-5405-11ea-86b4-8f9bed25bcd4.png)
and with the stable 2.4 its: 
![image](https://user-images.githubusercontent.com/4691064/74995491-e7dfe080-5405-11ea-92f9-547db7a679ef.png)

The entity at index __ error is crashing a lot of my test cases.

**Comment by spheenik** [comment]
@STRATZ-Ken Those are all console recorded?
