### ISSUE TITLE
Map tick to game time 

### ISSUE THREAD

**Issue by Stelian** [skadistats/clarity#218]
Hi is there a way to map a tick to the ingame clock? I am interested to know how can I can find out at what tick do we have the game start (after pick bans finished)

**Comment by spheenik** [comment]
Please see #106 and #116.

**Comment by Stelian** [comment]
Cheers @spheenik managed it. For those wondering, my approach to this was to follow the update entity event and look for the CDOTAGamerulesProxy Entity, where 3 properties are in scope: m_pGameRules.m_flPreGameStartTime, m_pGameRules.m_fGameTime and m_pGameRules.m_flStateTransitionTime.

If you need the tick for that exact frame of the game, you can insert the context and do ctx.getTick
