### ISSUE TITLE
Parsing Local Made Replays

### ISSUE THREAD

**Issue by huertasdanny** [skadistats/clarity#221]
Anyone know/have run into the issue with clarity not working on local made demos? i.e demos recorded using the DOTA2 console. I seem to have no issue parsing a replay downloaded from the DOTA servers but can't seem to get any relevant data (death times, spawns etc) from the locally created replay. 

Help?

**Comment by spheenik** [comment]
I have spent quite some time to make CSGO (Source 1) console recorded replays working, but I never came around to making Source 2 replays really work, since there never was the need for it.

**Comment by spheenik** [comment]
That said, you should get data from them. Parses might crash maybe, but there shouldn't be no data whatsoever...

**Comment by spheenik** [comment]
I'll close this.  A lot has been done since this was opened to improve console recorded replay parsing. So this might be obsolete.
