### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#222]
Hey Skadi,

Over the past few patches, we have seen issues fixed which is now causing massive CPU usage.  Is there any chance we can look into CPU performance?  The same hardware we used was able to parse about 25 matches/second.  Were now down to about 10~matches per second.  We can buy more hardware, if there is nothing you can do, but I wanted to ask first.

Thanks,

Ken

**Comment by jsam** [comment]
We are noticing similar performance spikes. What hardware are you guys using to achieve those numbers?

**Comment by STRATZ-Ken** [comment]
We use 15 physical machines which have 24 (2 x E5-230v3) Cores each.  This is now maxing those machines to 100% CPU. (Some machines have 72 Cores each (2 x E52686 v4).

**Comment by spheenik** [comment]
@STRATZ-Ken: As I told you on steam a while ago, 2.5 (which I suppose you use) uses a more accurate method of processing entity data, which needs more processing. I would advise to use 2.4.1 in production, which should not have such an issue...

**Comment by STRATZ-Ken** [comment]
Can you elaborate on what exactly is more accurate? Or what is not accurate on 2.4.1?

Sent from my iPhone

On Mar 1, 2020, at 11:55 AM, Martin Schrodt <notifications@github.com> wrote:

?

@STRATZ-Ken<https://github.com/STRATZ-Ken>: As I told you on steam a while ago, 2.5 (which I suppose you use) uses a more accurate method of processing entity data, which needs more processing. I would advise to use 2.4.1 in production, which should not have such an issue...

-

**Comment by spheenik** [comment]
Whenever an entity update comes in, it references a previous frame this update is the difference to.
In normal replays, this will always be the previous frame, so you always have to keep only a single state of all entities.

In console recorded replays and live data this is no longer the case. An entity update could reference some frame in the past which is not the last frame. So you have to keep a list of previous frames, and always copy all unchanged data to the new frame. 

Also generation of change events becomes harder. 

Lot's of modifications to the inner workings had to be done to implement this properly. I even have some ideas to optimize further, all that's missing is time to develop it...

**Comment by spheenik** [comment]
@STRATZ-Ken @jsam I am happy to announce that I basically fixed this whole issue completely. 2.5 is back to 2.4 speeds now, with this [commit](https://github.com/skadistats/clarity/commit/650533fac4eedf98fe420f8aecd4f1a6b716f3d5). Please test!

**Comment by STRATZ-Ken** [comment]
<3

**Comment by jsam** [comment]
@spheenik Thank you. Will try and let you know.

**Comment by jsam** [comment]
Ok, I've been testing it for a while now and it really does seem to address the CPU explosion issue, and performance is kinda back to normal. 

Thank you @spheenik

**Comment by STRATZ-Ken** [comment]
@spheenik  Is there any changes that may alarm CPU issues?  We got back up to to the 20~ matches a second, but now since the new change, were back to around 11~ second.  With the huge amount of uptick in players/matches were quickly falling further and further behind.  

- Is there any methods that you know are expensive and stay away from?

We ran a heatmap a few months ago, here were the results 
![image](https://user-images.githubusercontent.com/24981405/233848946-d6adc655-b191-44af-880a-61f849cecbdb.png)

We estimate that 76% of the CPU usage is from Skadi under the hood stuff.

**Comment by STRATZ-Ken** [comment]
![image](https://user-images.githubusercontent.com/24981405/233849009-4c1af4f8-b003-427e-a331-be185d0251cc.png)

**Comment by spheenik** [comment]
No change to performance whatsoever, from 2.7.8 to 2.7.9.

**Comment by spheenik** [comment]
Ah and regarding your question: Not doing repeated lookups of properties by name, and instead doing it by field path, but I think you know that already.
