### ISSUE TITLE
m_flPhysicalArmorValue always displays Base Armor at level 0

### ISSUE THREAD

**Issue by rudpes** [skadistats/clarity#223]
As per title, the m_flPhysicalArmorValue of the CDOTA_Unit_Hero entity always displays the base Armor value of the hero.
Am I doing something wrong ? Should this be the value of the armor the hero currently has ?

**Comment by spheenik** [comment]
Nope, you're doing nothing wrong. The server does not propagate the value to the client unfortunately, which basically means the client computes the real value on the fly...
