### ISSUE TITLE
@OnEntityCreated doesn't work now

### ISSUE THREAD

**Issue by PeaXCD** [skadistats/clarity#225]
It doesn't work since the latest update was released.

**Comment by PeaXCD** [comment]
By the way, how can i change the version to 2.4.1?

**Comment by PeaXCD** [comment]
Oh i know the reason! You must use both @OnEntityCreated and @OnEntityUpdated, then it will work. I'm very happy to report this for you :)

**Comment by spheenik** [comment]
Hmm, perfectly possible that I botched something. What exactly did you expect to work which didn't?

**Comment by STRATZ-Ken** [comment]
Having the same issue. @spheenik You available on Steam?

**Comment by STRATZ-Ken** [comment]
For me 

```
@OnEntityCreated
    public void OnEntityCreated(Entity e) {
		
    }
```

Never fires for me on 2.5 build. Works fine in 2.4 builds.

**Comment by spheenik** [comment]
Oh wow, there was indeed a small bug. EntityCreated would not fire, unless you subscribed to EntityUpdated. Fixed and pushed a new snapshot.

**Comment by STRATZ-Ken** [comment]
Also what was the reason to remove access to the `ctx`?

**Comment by spheenik** [comment]
> Also what was the reason to remove access to the `ctx`?

Access is not removed. It is just not required anymore. If you want, you can add the parameter at the beginning, and it will be passed.
If you rather like shorter method signatures, you can also inject it in your processor:

```java
    @Insert
    private Context ctx;
```
