### ISSUE TITLE
I want to get the hero's health

### ISSUE THREAD

**Issue by dp12321** [skadistats/clarity#227]
Hello,  I don't know how to get the hero's blood volume. I tried some methods, but I still can't get the hero's blood volume.

**Comment by spheenik** [comment]
`entity.getProperty("m_iHealth")`

**Comment by dp12321** [comment]
Good brother, thank you! I'll try

**Comment by spheenik** [comment]
if you want to find more, use [clarity-analyzer](https://github.com/spheenik/clarity-analyzer)
