### ISSUE TITLE
I'm sorry to bother you again. I want to know if the hero skill is in CD state. I think I'm doing something wrong now, because I find that when the game time is 0, the hero skill is in active state. I'm very contradictory

### ISSUE THREAD

**Issue by dp12321** [skadistats/clarity#228]
for (int a = 0; a < 17; a++) {
                        FieldPath a_fp = Hero.getDtClass().getFieldPathForName("m_hAbilities.00" + String.format("%02d", a));
                        if (a_fp != null) {
                            Entity ablititys = ctx.getProcessor(Entities.class).getByHandle((Integer) Hero.getPropertyForFieldPath(a_fp));
                            if (ablititys != null) {
                                String AblitityName = getEntityName(ctx, ablititys);
                                Boolean is_Active = ablititys.isActive();
                            }
                        }
                    }

**Comment by spheenik** [comment]
`isActive()` on an entity only says that in the communication with the server, this entity is active, which means that the server will update properties of it. It has nothing to do with cooldown state. The ability entity also has properties, for example:
```
0 m_hOwnerEntity 16696318
1 m_iLevel 1
2 m_bInAbilityPhase false
3 m_fCooldown 0.0
4 m_iCastRange 600
5 m_iManaCost 50
6 m_bAutoCastState false
7/0 CBodyComponent.m_hParent 16696318
7/1 CBodyComponent.m_flScale 1.3513514
7/2 CBodyComponent.m_name 0
7/3 CBodyComponent.m_hierarchyAttachName 0
8/0 m_pEntity.m_nameStringableIndex 364
9 m_MoveCollide 0
10 m_MoveType 0
11 m_flCreateTime 0.0
12 m_ubInterpolationFrame 0
13 m_iTeamNum 3
14 m_hEffectEntity 16777215
15 m_fEffects 16
16 m_flElasticity 1.0
17 m_Gender 0
18 m_bSimulatedEveryTick true
19 m_bAnimatedEveryTick true
20 m_nMinCPULevel 0
21 m_nMaxCPULevel 0
22 m_nMinGPULevel 0
23 m_nMaxGPULevel 0
24 m_iTextureFrameIndex 0
25 m_flNavIgnoreUntilTime 0.0
26 m_bRefCountsModifiers false
27 m_bHidden false
28 m_bActivated true
29 m_iDirtyButtons 0
30 m_bToggleState false
31 m_flCooldownLength 0.0
32 m_flChannelStartTime 0.0
33 m_flCastStartTime 0.0
34 m_bInIndefiniteCooldown false
35 m_bFrozenCooldown false
36 m_flOverrideCastPoint -1.0
37 m_bStolen false
38 m_bReplicated false
```
Check `m_iLevel != 0` to see if it's skilled, and `m_fCooldown == 0.0` to see if it's not on cooldown right now. Is that what you wanted?

Again: I suggest you use clarity-analyzer.

**Comment by dp12321** [comment]
Thank you for your busy reply. I think you are right. I want to try it

**Comment by spheenik** [comment]
Of course I am right, I made the software! :)

**Comment by dp12321** [comment]
thank you very much!
