### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by ergmyth** [skadistats/clarity#229]
I found this git from stratz.com. In their open api I found some bugs:
1. Sniper's second spell counting as a stun
2. Lich and KotL hypnotize doesn't count as a disable.
3. Shadow demon second spell doesn't count as a disable.
4. Medusa third spell is blocking a damage. So I think blocked damage doesn't count as a receivedDamage, because she has very low value for this parameter. Also Visage has same problem and other heroes maybe too.
5. Brewmaster panda's spells doesn't count.

**Comment by spheenik** [comment]
That's a pity.
I can't do anything about it, since I only wrote this parser, and not the code that provides their API.

@STRATZ-Ken: Maybe you can help?

**Comment by ergmyth** [comment]
By the way, does the parser collect information about a heroDamage to Roshan?

**Comment by ergmyth** [comment]
Also Faceless Void slowCount is anomaly high = 33.8, and slowCount = 0

**Comment by spheenik** [comment]
> By the way, does the parser collect information about a heroDamage to Roshan?

You do not understand: The parser does not "collect information". It merely is an API for allowing others to do so.

**Comment by ergmyth** [comment]
@STRATZ-Ken: 
Next heroes slow parameter is 0:
Treant, Lion, Bounty Hunter, Pangolier, Void Spirit, Razor, Snapfire, OD, Earth Spirit, Dazzle
