### ISSUE TITLE
smoke Distinguish

### ISSUE THREAD

**Issue by yangex** [skadistats/clarity#230]
I'm sorry to bother you.
For smoking，I want to know how to distinguish between Ninja Gear and  Smoke of Deceit.
When smoking , what i get from （CombatLogEntry）cle.getInflictorName() is always modifier_smoke_of_deceit .
Is there any way to solve this？

**Comment by spheenik** [comment]
I don't really know.
@noxville anything to add?

**Comment by yangex** [comment]
![github](https://user-images.githubusercontent.com/42961347/81262663-cdb2b780-9070-11ea-9d0e-81fad326f026.png)

like this，I want to know which equipment is used

**Comment by yangex** [comment]
[http://dota2-dem.cn-gd.ufileos.com/test%2Fgithub.png](url)
just like this, I want to know which equipment is used

**Comment by yangex** [comment]
[https://github.com/yangex/mall/blob/master/github.png](url)
just like this，I want to know which equipment is used

**Comment by yangex** [comment]
[http://dota2-dem.cn-gd.ufileos.com/test%2Ftest.png](url)
just like this，I want to know which equipment is used。
（Pictures are not allowed here，Please open the link with the browser）

**Comment by yangex** [comment]
[http://dota2-dem.cn-gd.ufileos.com/test%2Fgithub.png](url)
just like this，I want to know which equipment is used。
（Pictures are not allowed here，Please open the link with the browser）

**Comment by Noxville** [comment]
I would look for DOTA_COMBATLOG_ITEM entities first to look for an item_used event. 

```
noxville@batrider:/data/replays$ cat ./5401545298.json | jq '.events[] | select(.type == "item_used")'  | jq .values[3] | sort | uniq -c  | egrep '(ninja|royal|repair|flicker)'
      4 "item_flicker"
      1 "item_ninja_gear"
      3 "item_repair_kit"
      2 "item_royal_jelly"

```

**Comment by yangex** [comment]
Thank you for your reply. I think I know how to solve it

**Comment by spheenik** [comment]
Leave a note on how you did it!

**Comment by yangex** [comment]
I took a stupid approach。
Record the equipment use time from DOTA_COMBATLOG_ITEM entities ，and then compare the data obtained from DOTA_COMBATLOG_MODIFIER_ADD entities  with the above time to determine whether it is Ninja Gear or Smoke of Deceit. 
I don't quite understand why cle.getInflictorName() from DOTA_COMBATLOG_MODIFIER_ADD entities is always modifier_smoke_of_deceit ，whether it's Ninja Gear orSmoke of Deceit.

**Comment by STRATZ-Ken** [comment]
> I took a stupid approach。
> Record the equipment use time from DOTA_COMBATLOG_ITEM entities ，and then compare the data obtained from DOTA_COMBATLOG_MODIFIER_ADD entities with the above time to determine whether it is Ninja Gear or Smoke of Deceit.
> I don't quite understand why cle.getInflictorName() from DOTA_COMBATLOG_MODIFIER_ADD entities is always modifier_smoke_of_deceit ，whether it's Ninja Gear orSmoke of Deceit.

Its because they get lazy when adding modifiers.  Many old heroes (Around for a while) still use MODIFIER_STUN instead of STORM_HAMMER (Sven) for example.

The above data can easily be collected from our API as well, as we capture and re-create the entire game from scratch. So modifiers are easily grabbed.
