### ISSUE TITLE
How to contribute to this projet?

### ISSUE THREAD

**Issue by Henroks** [skadistats/clarity#231]
Hi! I've been using clarity for a while (for csgo more specifically). I would like to contribute with code in any form that helps you with it. I'm fairly new to Java (came from C++), with that said please pardon my newb question:
I have hit a wall when trying to build clarity in my own computer, the steps I did:
- git clone clarity
- imported it on IntelliJ
- Hit build, got this response:
![image](https://user-images.githubusercontent.com/52092050/82161454-28b78c00-9873-11ea-83bf-fde864fa1e74.png)

How do I import this build to my project to try it out? I see that there is no .jar anywhere after this "successful build" so I'm kinda lost

**Comment by spheenik** [comment]
Did you import it as a maven project?
There should be a jar in the target Folder. If there is not, issue a `mvn package` in the root folder, this should give you the target folder with a jar in it.

**Comment by Henroks** [comment]
Yes I did!
Now when I try to run any demo it returns 
`NoSuchMethodError: java.nio.MappedByteBuffer.position(I)Ljava/nio/MappedByteBuffer`

Do I have to change any props other than this:
```
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.source>1.8</maven.compiler.source>
  </properties>
```

Here is my build configs
  ```
<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <mainClass>
                    org.MyApp.App
                  </mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

Any idea?

**Comment by spheenik** [comment]
Seems like you run it with a different JDK than it was built with.

**Comment by spheenik** [comment]
Thought about it some more:
Please:

- create a new project just from `clarity-examples`
- run an example (it should download clarity from the repository, but otherwise work fine)
- clone `clarity`
- choose "add module from existing sources" in your clarity-examples project, and import `clarity`
- you should now be able to run examples, and Idea will use the imported clarity module to run it

**Comment by VitorCaleffi** [comment]
After many tries and trying to find out what was wrong with my env, building the artifact with IntelliJ solved my problems. Thanks!

**Comment by Henroks** [comment]
After many tries and trying to find out what was wrong with my env, building the artifact with IntelliJ solved my problems. Thanks!

**Comment by spheenik** [comment]
There's no solid way to mitigate this. Where did you get the demos?

**Comment by Henroks** [comment]
[This match on HLTV](https://www.hltv.org/download/demo/57395) Dust 2 is Ok but Mirage returns this exception

**Comment by spheenik** [comment]
Sometimes replays on HLTV are truncated, and they might also be corrupt.
Either way, nothing I can do in clarity to "repair" the underlying data.

**Comment by Henroks** [comment]
Cool! Thanks
