### ISSUE TITLE
Is there a way to retrieve pro name (Dota 2)?

### ISSUE THREAD

**Issue by ChitaAPC** [skadistats/clarity#232]
When parsing a premium level match I noticed that the player names are what they have set in their steam profile, rather than the actual pro names that you can see when watching the game through the client. 
For clarity, I am retrieving the player names from `CDOTA_PlayerResource` under `m_vecPlayerData.0000.m_iszPlayerName`.
I have looked for any property with either a string name or a `m_pEntity.m_nameStringableIndex` using the ClarityAnalyser.
So far I have looked at the following entities:

- `CDOTAPlayer`
- `CDOTA_PlayerResource`
- `CDOTATeam`
- `CDOTA_DataDire`
- `CDOTAGamerulesProxy`

Is there anywhere else I am missing?

Any help would be greatly appreciated.

**Comment by spheenik** [comment]
So, the name in `m_iszPlayerName` is what they set themselves, while ingame they are shown by their real, official name, rather by what they have set. Right?

If so, maybe something can be retrieved from the steam web api, using the steam id of the player.

**Comment by ChitaAPC** [comment]
Yes thats right.
I guess the game must just display the most up to date name for the steam id. 
Just found a bit surprising that this doesn't get stored in the dem file.
Thanks for the help. :)

**Comment by spheenik** [comment]
The steam ids of the players are in there. I'd check the api, or manually maintain a database of pro players, if I really need it.

**Comment by ChitaAPC** [comment]
If anyone else needs it, Open dota has a nice API call that has that (https://api.opendota.com/api/proPlayers) 
I suspect there will be a Valve API equivalent somewhere as well.

Thanks again for the help spheenik

**Comment by STRATZ-Ken** [comment]
If your into GraphQL, you can also use https://api.stratz.com/graphiql Which is very easy to link proPlayers to matches. (STRATZ)

**Comment by Noxville** [comment]
If you have their steam32 ID then you can just request https://datdota.com/api/players/$playerId

i.e. https://datdota.com/api/players/87278757 for Puppey
