### ISSUE TITLE
Restart ControllableRunner

### ISSUE THREAD

**Issue by Henroks** [skadistats/clarity#233]
Hi, sorry for spamming this repo :/

I know there is a way to seek forward with ControllableRunner.seek, but is there a way to restart the parsing progress?

If not a "built-in" way, do you recommend any logic that I should follow?

So far, I did this in my main:
```
        Source source = new MappedFileSource(this.demoPath);
        runner = new ControllableRunner(source);
        runner.runWith(this);

        while(!runner.isAtEnd() && runner.isRunning())
            runner.tick();
```

Then I call:
`runner.halt();`

In order to interrupt the first while, but, when the line above is called the thread never really dies and I get stuck in an infinite wait loop.

Maybe this is not the most elegant way of doing this, any recommendations? Thank you again

**Comment by spheenik** [comment]
What do you mean "restarting the process"? 
Do you say `runner.halt()` does not kill the runner thread?

**Comment by Henroks** [comment]
Start from the beginning of the demo again.

Yes, I tried to use `runner.halt()`, when I used it my program got stuck here:
![image](https://user-images.githubusercontent.com/52092050/83039514-ab2f1100-a014-11ea-9933-b23af9163cb6.png)
(Trhead.java)
I just made another test, waited for 5 minutes. The software never leaves this  `while (isAlive())` lopp

**Comment by spheenik** [comment]
You could do `runner.seek(0)` to get back to tick 0.

Why do you want a `ControllableRunner` anyway? From your earlier example, it seems like it would be enough to use a `SimpleRunner` for example.

Other than that, your code seems to call `join` but you do not show it. Can I have a full example that replicates your problem?

**Comment by Henroks** [comment]
I have tried  `runner.seek(0)`, no luck.

I imagine that SimpleRunner could do the trick as well, but how do I interrupt it? I'll probably have to wait till it ends to start it over.

This is basically what I do:
![image](https://user-images.githubusercontent.com/52092050/83048543-1f22e680-a020-11ea-840c-de0d6d0d93da.png)

And after a few rounds I'll call `runner.halt()`, and the behavior described above will occur again.

This is all I do related to the runner on the entire code

**Comment by spheenik** [comment]
I can't help you without a complete example.
You can't just throw me bits and waste my time trying to figure out the problem.

**Comment by Henroks** [comment]
You are right. Here is it, I have just tried and the problem continues:
```
public class App {
    @Insert
    public Context ctx;
	
	public static void main(String[] args) throws Exception {
        new App().run(args);
    }
	
	public void run(String[] args) throws Exception {
		Source source = new MappedFileSource("console-1.dem");
		runner = new ControllableRunner(source);
		runner.runWith(this);

		while(!runner.isAtEnd() && runner.isRunning())
			runner.tick();
	}

	@UsesEntities
	@OnGameEvent
	public void onGameEvent(GameEvent event) {
		switch (event.getName()) {
			case "round_announce_match_start":
				try {
					runner.seek(0);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
				break;
		}
	}
}
```

This will cause, for me at least, to be stuck here:
![image](https://user-images.githubusercontent.com/52092050/83049439-90af6480-a021-11ea-8f52-91629c64c899.png)

**Comment by spheenik** [comment]
I see where the problem is:

- the main thread is in `runner.tick()` which will `waitForTickReached(currentTick + 1)`
- the parsing thread will find the game event on `currentTick` and will seek to 0
- if the parsing thread obeys here (and I do not think it does, but I'd have to check), the main thread could never reach `tick + 1` since it'll hit the seek to 0 first

To sum up:

The functions to control the runner are not supposed to be called from the parsing thread.

What do you want to do? What should happen after the runner halted?

**Comment by Henroks** [comment]
Cool understood.
Im trying to first list all players in teams in a CSGO console demo, because of networking (and the server vis check) you cannot get this information at round start, so I want to:
List the players trough the round
get their steam ids and etc
go back to round start to proper analyze it

**Comment by spheenik** [comment]
Use a ControllableRunner this way:
When you got the player info, set a variable to indicate that, but let the runner continue.
Then on the main thread, look at the variable, and do the seek from there.

But do the players really change during the round? In my projects, this seems to happen basically never, so why do it?

**Comment by Henroks** [comment]
So, when round starts (this happens only on console recorded demos), your team (user recording the demo) is available and you can get m_iTeam (and any other info really) just fine, but the other players and spectators will be 0 (in my experience).

![image](https://user-images.githubusercontent.com/52092050/83059836-e9d2c480-a030-11ea-96c7-5a1c028354dd.png)
It worked perfectly! Thank you
And now I have the correct info when the game starts, you're awesome

**Comment by spheenik** [comment]
Glad I could help ;-)
