### ISSUE TITLE
rune pick up event

### ISSUE THREAD

**Issue by yangex** [skadistats/clarity#237]
In 5453224510 this macth，the last rune was picked up at 34:03 before a player send GG。
The problem is that CDOTAUserMsg_ChatEvent.CHAT_MESSAGE_RUNE_PICKUP not listen in last rune pick up event。
If I want to get message about this event, how can I solve it?
Thank you for your answer

**Comment by spheenik** [comment]
Are you saying that there is no `CDOTAUserMsg_ChatEvent.CHAT_MESSAGE_RUNE_PICKUP` message in the replay?

**Comment by yangex** [comment]
yes，after the player send gg，there is on CDOTAUserMsg_ChatEvent.CHAT_MESSAGE_RUNE_PICKUP message in the replay

**Comment by spheenik** [comment]
Hmm, if you really need it, you can look at the rune entity disappearing.
