### ISSUE TITLE
How to use  getLocationX() and  getLocationY() in CombatLogEntry?

### ISSUE THREAD

**Issue by XinpengLiu321** [skadistats/clarity#238]
I am trying to get a hero's location when some combatlog event happens. I found two functions in the CombatLogEntry named getLocationX() and  getLocationY(). I guess that it returns the location of the events (however it is not so clear because an CombatLogEntry should have a Target and an Attacker, which are in different location). So I tested them  with the code below:

            case DOTA_COMBATLOG_DEATH:
                log.info("{} {} is killed by {} at {} ,{}",
                    time,
                    getTargetNameCompiled(cle),
                    getAttackerNameCompiled(cle),
                    cle.getLocationX(),
                    cle.getLocationY()

                );
                break;

It is just a slight change on the clarity-examples\combatlog code. 
The result is that  those functions return 0.0 all the time. Can somone please show me how to use those two functions correctly?
By the way I cannot find the source code of those functions, Can someone tell me where it is?
Thank you!

**Comment by spheenik** [comment]
Might well be that the dota client does not encode the position of the death event in the combat log.
If so, you can get at player positions by using entities.

**Comment by spheenik** [comment]
See for example https://github.com/skadistats/clarity/issues/211

**Comment by spheenik** [comment]
Unfortunately, the data is not there.
