### ISSUE TITLE
How to retrieve voice data from a csgo replay

### ISSUE THREAD

**Issue by VitorCaleffi** [skadistats/clarity#240]
Is it possible? Where should I start?

**Comment by spheenik** [comment]
Is there any in CSGO replays?
I always thought this feature exists only for Dota...

**Comment by VitorCaleffi** [comment]
Yes! I've been reading a lot about it lately.. 
When watching a replay I can hear both teams, so the data is there for sure.

I also have found `svc_VoiceData` net messages, so maybe that's a start?
I believe that both CSGO and Dota uses the same methods and encoding, as far as I read about it, since they both uses Steam services for voice communication

**Comment by spheenik** [comment]
If it's the same as in Dota, there is a `VoiceInit` early in the replay, and then multiple `VoiceData` packages with encoded chunks. The chunks are encoded with a `speex` codec. That's about all I know...
