### ISSUE TITLE
Is there a convenient way to get dataset with all information?

### ISSUE THREAD

**Issue by metra4ok** [skadistats/clarity#241]
I need to get a .csv file with maximum amount of information about a game (heroes level, positions, gold, exp, scores, tower status and so on - some kind of game's timestamp) at specific moments of time (each 20 seconds, for example). Is there a convenient way to parse all that information?
It will be used in machine learning project.
Sorry if it is a silly question, I have no experience in Java at all and it is hard for me to figure it out by myself.

**Comment by spheenik** [comment]
Nope, there isn't.

A good way to start would be to look at [OpenDota's parser](https://github.com/odota/parser/tree/master), which is a good example of what you're trying to achieve.
