### ISSUE TITLE
CombatLogEntry.getTimestamp() vs game tick

### ISSUE THREAD

**Issue by neoedmund** [skadistats/clarity#242]
Hi, I use `public void onCombatLogEntry(CombatLogEntry cle) {}` to parse dota2 replay. 
I need to know `tick` from `CombatLogEntry`, `CombatLogEntry.getTimestamp()* 30` is not the tick value. How to ? 
Thanks.

**Comment by spheenik** [comment]
You can get it from the Context.
You can inject a Context in your Processor by using

```
@Insert
private Context ctx;
```

and then in your `onCombatLogEntry()` use `ctx.getTick()`.

**Comment by neoedmund** [comment]
Thank you. That's it!
