### ISSUE TITLE
How can i get the item_aghanims_shard used?

### ISSUE THREAD

**Issue by yangex** [skadistats/clarity#250]
```
CombatLogEntry.getType() == DOTA_COMBATLOG_TYPES.DOTA_COMBATLOG_PURCHASE&& CombatLogEntry.getValueName().startsWith("item_aghanims_shard")
```
Like this，i can  get the item_aghanims_shard purchase time。
but i want to konw the usage time, you know ，this is different because courier exist。
I would appreciate it if you could help me！

**Comment by GoCross** [comment]
> ```
> CombatLogEntry.getType() == DOTA_COMBATLOG_TYPES.DOTA_COMBATLOG_PURCHASE&& CombatLogEntry.getValueName().startsWith("item_aghanims_shard")
> ```
> 
> Like this，i can get the item_aghanims_shard purchase time。
> but i want to konw the usage time, you know ，this is different because courier exist。
> I would appreciate it if you could help me！

I'm sorry to bother you. Have you solved this problem?

**Comment by reacheight** [comment]
@yangex Can you please tell if you have you solved this problem?

**Comment by spheenik** [comment]
I dont' know if he did that way, but you could check the inventory slots of the hero entities to find out if it's in there.

**Comment by reacheight** [comment]
@spheenik I've just checked it - yes, it appears for a moment in an inventory slot and then gets consumed instantly. I hoped there is a property for "shard state" of a hero somewhere in the replay, but I gues it'll work.

**Comment by spheenik** [comment]
Ok, this means that the shard is transformed into a modifier on the hero.

**Comment by spheenik** [comment]
Or new abilities show up on the hero....

**Comment by yangex** [comment]
> @yangex Can you please tell if you have you solved this problem?

I don't have a good way.
I just solved it by buying CDOTA_Item_Aghanims_Shard and @OnEntityDeleted(classPattern = "CDOTA_Item_Aghanims_Shard").

Basically, it can solve the problem.But after a hero uses  aghanims_Shard,he pick up item_aghanims_shard_roshan nd gave it to others hero,the item_aghanims_shard_roshan entity will be deleted and recreated.This will cause the item_aghanims_shard_roshan to be used twice

**Comment by reacheight** [comment]
For history: as spheenik suggested, this information is stored in modifiers. Here is some Scala code, but I think it should'nt be too complex to understand:

```scala
@OnModifierTableEntry
def onModifierEntry(ctx: Context, modifier: DotaModifiers.CDOTAModifierBuffTableEntry): Unit = {
  val table = ctx.getProcessor(classOf[StringTables]).forName("ModifierNames")
  val modifierName = table.getNameByIndex(modifier.getModifierClass)
  val hero = Entities.get(modifier.getParent)
  ...
}
  ```
Basically, `modifier.ModifierClass` contains index of modifier in `ModifierNames` string-table (name is `modifier_item_ultimate_scepter` for Scepter and `modifier_item_aghanims_shard` for Shard), and `modifier.Parent` contains handle of hero-entity.
