### ISSUE TITLE
2.6.0 Support Thread

### ISSUE THREAD

**Issue by spheenik** [skadistats/clarity#251]
## January 26, 2021: New releases and versioning model update!

Starting today, I will switch to a semantic versioning theme (MAJOR.MINOR.PATCH)

* MAJOR will probably not change in a long time
* MINOR will be increased when there are changes that I believe to be disruptive (and want you to test them first)
* PATCH will be for bugfixes, like we had with the latest 7.28 update.

Today, I made two releases:
* Version 2.5: this is simply the last snapshot as a release
* Version 2.6.0: the first version using the new scheme

There will be no bugfix releases for 2.5, so please migrate your code in a timely manner.

## Changes in 2.6.0

* lots of restructuring / code cleanup regarding the field update parsing code (should not be noticeable)
* package rename `skadistats.clarity.decoder` -> `skadistats.clarity.io` (global search/replace should suffice)
* package rename `skadistats.clarity.io.unpacker` -> `skadistats.clarity.io.decoder` (global search/replace should suffice)
* new event `OnEntityPropertyCountChanged`, which is raised when the amount of properties in an entity changed
* with ControllableRunner (seeking), improved `OnEntityUpdated` to only contain FieldPaths that have been changed
* small performance increase for BitStream
* added proper handling of a special case with Dota 2 console recorded replays, which would throw an exception before

**Comment by spheenik** [comment]
@Noxville @podex @howardchung @STRATZ-Ken @ChitaAPC @nul0m

Headsup, especially for the folks that have problems with console recorded replays with Dota 2, since this might fix it.

**Comment by Noxville** [comment]
Can we just set up some (very rough) unit tests for clarity - perhaps one replay per month or per patch with simple logic (OnEntityUpdated, OnEntityCreated, some stringtables, etc - just ensuring it can decode the full stream - nothing more complicated).

**Comment by spheenik** [comment]
Hmm, could you provide the replays?

**Comment by Noxville** [comment]
For pro matches, sure - although I would expect moving forward you'd want to throw in some non-pro matches to the sample every once in a while.

**Comment by spheenik** [comment]
Hmm, not really necessary. They've had the same format, as long as they were not recorded live, but downloaded from Valve.

**Comment by maxpaj** [comment]
@spheenik 

I have a technical question: 

In the Dota 2 client, I can use the console to enter `demo_gototick X` or `demo_goto 0min`. However, that corresponds to the replay time, not the in-game time. 

Is a way to determine the tick of a specific in-game time, such as the first creep spawn (0:00)?

**Comment by Noxville** [comment]
You could parse the game until gamerules updates m_flGameStartTime = 0.0 and then you'll know when the horn sounds.

**Comment by spheenik** [comment]
Exactly. Since draft time is not constant, and since there could be pauses before the horn, there simply is no way to know without parsing the replay.

**Comment by spheenik** [comment]
And to add, even after the horn sounds, there could be pauses during which the replay tick increases but game time doesn't.

**Comment by maxpaj** [comment]
Thank you all for the answers! :)
