### ISSUE TITLE
CDOTAUserMsg_SpectatorPlayerUnitOrders click coordinates

### ISSUE THREAD

**Issue by en660552** [skadistats/clarity#252]
How to understand the coordinates of the user clicked on the map or hero ?. I wrote a simple method as an example. 

```
    @UsesStringTable("EntityNames")
    @UsesEntities
    @OnMessage(DotaUserMessages.CDOTAUserMsg_SpectatorPlayerUnitOrders.class)
    public void onSpectatorPlayerClick(Context ctx, DotaUserMessages.CDOTAUserMsg_SpectatorPlayerUnitOrders message){

        Entity e = ctx.getProcessor(Entities.class).getByIndex(message.getEntindex());

        log.info("{}, X: {}, Y: {}, Z: {}",
                ctx.getTick(),
                message.getEntindex(),
                message.getPosition().getX(),
                message.getPosition().getY(),
                message.getPosition().getZ()
        );
    }

```
I get the output such this
76091  X: -5736.0186, Y: -1842.9775, Z: 128.00012

How to interpret such coordinates correctly ? What are the units of measurement here?

**Comment by spheenik** [comment]
The coordinates are "kind of" arbitrary, and correspond to the real dota map the real client loads.
If you want to calculate the coordinate of an entity, refer to [this code](https://github.com/skadistats/clarity/issues/211#issuecomment-611944367).

**Comment by Trimatix** [comment]
Hi Spheenik, what is the range of possible values for a hero's coordinates please?
(as given by your function that you just linked, in https://github.com/skadistats/clarity/issues/211)

Many thanks!

**Comment by spheenik** [comment]
Depends on the map. Why do you want to know? Why don't you simply test?

**Comment by Trimatix** [comment]
I see, thanks!
So that I can normalize some positional data prior to use with a neural network. Good idea to find it through testing 👍

**Comment by spheenik** [comment]
I see. Depending on how you want to do it, you might want to only use the cell the hero is in then.
It'll be 256*256 cells from which roughly only the inner 128*128 contain the map.

**Comment by Trimatix** [comment]
Just in case anyone else would like this information, by running around the edge of `dota.bsp` in the 15/04/21 patch of dota 2, I got these coordinate ranges with [spheenik's function](https://github.com/skadistats/clarity/issues/211#issuecomment-611944367):

| Dimension | Minimum | Maximum |
| ------------- | ------------- | ------------- |
| X | 8666.781 | 23840 |
| Y | 16384 | 9992.297 |
| Z | -120.359 | 8384 |

I did not measure cells.

**Comment by spheenik** [comment]
Thank you, @Trimatix. I'll close this, seems solved.
