### ISSUE TITLE
No "game_info" for some replays in infoForFile

### ISSUE THREAD

**Issue by Dmytro4** [skadistats/clarity#254]
For some replays, there is no game_info which consists of gameid, heroes, drafts, and other important data. There is only information about frames and ticks
Example id: 5889302968
By running "info" package you get this (v2.6.0):
![image](https://user-images.githubusercontent.com/22562710/118148619-6c5abc80-b419-11eb-91d9-27eed5312115.png)

**Comment by Dmytro4** [comment]
btw there are a lot of such matches from 12863 league - https://www.dotabuff.com/esports/leagues/12863-epic-league-season-3
is that known or there is some bug in the parser?

**Comment by spheenik** [comment]
I only use protobuf to decode the info packet. If it is sparsely filled, like in your example, I do not think it's a bug on my side, it's just that more data was never included.

Were do the replays originate?

**Comment by Dmytro4** [comment]
> Were do the replays originate?
they are from the Epic League (linked above). For now, I only found the issue with that league

**Comment by spheenik** [comment]
And you download from Valve or from them? 
If you download from them, they probably did "console record" them, and Valve change (read screw up) console recording on a regular basis.

**Comment by Dmytro4** [comment]
> And you download from Valve or from them?
> If you download from them, they probably did "console record" them, and Valve change (read screw up) console recording on a regular basis.

i downloaded them from Valve's servers http://replay274.valve.net/570/5889302968_85551580.dem.bz2

**Comment by spheenik** [comment]
Well then

¯\_(ツ)_/¯
