### ISSUE TITLE
Annotation Questiones 

### ISSUE THREAD

**Issue by BusyLivingDota** [skadistats/clarity#255]
Greeting from a java newer. The clarity project is really fasinating and magical, literally makes everything I can imagine come true. I spent the whole last month on Java and finally can understand this remarkable work. However I still have some questiones.

First the way I see Clarity work is that, we code a processor which have a method using one of your annotation. The runner will call the method at the right time and fill in with parameters recorded in @UsagePointMarker + Context. Is that correct? Is Context always aviliable without declared in @UsagePointMarker? Is there any other default parameter can get without declared like Context?

Then I couldn't understand using @UsesEntities at the start of a class. I tried to run the program without it and the result came no difference.  What's the point of @UsesEntities, or am I doing something wrong?

Last might sounds noob but without having a big boy to consult, can you tell me what exactly technology or skill is used on this annotation work? I just learnt polymorphic, reflection kinda stuff and hoping to find some video or task can study with.

Hope I made my word clear, cause I am new in programing, this is my 1st tweet on github. I literally sign up github just for clarity. Looking forward to your reply.

Sincerely,
BusyLiving

**Comment by spheenik** [comment]
> The runner will call the method at the right time and fill in with parameters recorded in @UsagePointMarker + Context. Is that correct?

Yes. The context however is a remnant of earlier versions. Clarity will look at the signature of your method, and if you declare a Context as the first parameter, it will pass it. It's optional though, so you do not have to. There are no other default parameters implemented. You can use `@Insert` in your processors like this to achive the same:

```java
    // other way to get at the context
    @Insert
    private Context ctx;

    // inject EngineType, which contains helper functions depending on the type of replay (Dota, CSGO, ..) you're working with
    @Insert
    private EngineType engineType;

    // inject other processor, this is the same object you would get if you do ctx.getProcessor(Entities.class)
    @Insert
    private Entities entities;
```

The `@UsesEntities` is a marker, which makes clarity enable entity processing (= add the processor Entities.class to the run), even if there are no entity-related annotations (for example `@OnEntityUpdated`). The reason your example works without it is probably that it contains one or more such annotations which allows clarity to detect you're wanting entity data anyway. [Here are all the annotations that would work](https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/processor/entities/Entities.java#L48-L57)

Annotations are a cool concept, which you can do a lot of stuff with. They are pretty easy to use. You can just declare an annotation, then put it on some code, and reflect on which annotations are there during runtime. That's exactly what clarity does. When you hand it a processor, it looks at all it's methods, and finds annotations it knows about. For each of those annotations, there is a processor in clarity which is a `@Provider` for this functionality. Clarity then also adds the providing processor to the run, and in turn scans it's methods for other providers that are needed. This process is repeated until no new providers are found. (Notice for example, how `Entities.java` uses `@UsesDTClasses` which adds the `DTClasses.java` processor)

There is a lot of useful Java code that uses annotations. For example JPA (a standard for persisting data in a DB) uses annotations which you can use to describe the type of data you want to persist. There's also tons of frameworks that use it for dependency injection or more (Spring / CDI). Again, there's nothing magic about annotations. They're just a tool, albeit a very useful one. Declare one, mark your code with it, reflect over the code to do something if they're there.

Hope that helps :-) Feel free to follow up!

**Comment by BusyLivingDota** [comment]
Thanks for your reply! Your answer is like a beacon shining my direction.

I could say I definately have more questions, but I would rather figure them out myself next few days, and there is a lot to learn for me btw. I will probably raise up more issues in the future.

Can't stop appreciating your aid again, fast, helpful and enlightening!
