### ISSUE TITLE
Interaction Between Entities And CombatLog

### ISSUE THREAD

**Issue by BusyLivingDota** [skadistats/clarity#259]
Greeting:

I've been working on Clarity for weeks and seems getting into it. Appreciate Clarity the great work, again. I'm trying some interactions between Entities and CombatLog, which consume a lot of work. Just trying to make sure I'm not wasting my time, I need to make this clear.

By using entities we can obtain all properties of all entities, but can never get relation or interaction(like kills, damage source, skill target). On the other side by using combatlogs we can obtain all interaction between entities, but we can never get  one of the entity object simply by calling something.(Of course we can inject entities and looking for it but that's the demanding part) Am I understatnding wrong?

The task I am currently working on is figuring out creep position when killed by the hero. I am trying to use cxt.getTick() to connect Entity and CombatLog, but it happens when two creep die at same tick on different side of map by different killer. Just asking is it my responsibility to distinguish the situation or I am missing some really simple solution.

**Comment by ChitaAPC** [comment]
The combat log event has the name of both the unit was killed (`CombatLogEntry.getTargetName()`) and the killer (`CombatLogEntry.getAttackerName()`) in the event.
The name reported in the combat log entry matches the `name` attribute in the entities, so you can match it this way.

I can't remember exactly, but I am pretty sure kill events in the combat log can also give you the location of where the event happened, so this is probably pretty useful for keeping track which event is which in the example you gave

**Comment by spheenik** [comment]
Yes, afaik as I know there is no easy relation between entities and the combat log, so you have to use some sort of clever algorithm to find the relation yourself.

The pointers that @ChitaAPC gave certainly help a lot to sort this out, but from the top of my head, I can imagine cases where you might still run into problems. For example, what is the name of a Luna Illusion that is owned by the enemy Shadow Demon? I think it would be Luna :(

Notice, there's an attacker name, and an inflictor name, maybe the inflictor will be the Shadow Demon in this case, I'm not sure.

**Comment by BusyLivingDota** [comment]
Thanks for your replies, I think I got what I want.

cle.getLocationX() and cle.getLocationY() always return 0.0 as far as I know, please inform me if you have achieved any location information successfully so far from CombatLogs.

It would be fine if we investigating the main hero entities. But if we work on illusions, creeps or summon, IDing one from a lot could be seriously demanding. Whatever, never impossible.

**Comment by BusyLivingDota** [comment]
After a month I finally figure out a way to solve this problem. The key is that the arrangement of npc_dota_hero_heroname in CDemoFileInfo is equals to the playerID in each CDOTA_Unit_Hero_HeroName entity. So I use a controllable runner to just find all 10 heroes(OnEntityCreated) and put them in a HashMap<Integer,String>, then quickly go through the CDemoFileInfo which is very fast, and get another HashMap<Integer,String>, then we got two HashMaps which have relative values with same key. I guess it should be the simplest way to connect combatlog and entities, as far as I know.
