### ISSUE TITLE
How to get Activity ChatWheel and Spray Informations

### ISSUE THREAD

**Issue by BusyLivingDota** [skadistats/clarity#261]
Hi:

Admire the project! I am currently working on message and trying to find out chatwheels players used in games. I am awared to use DotaCommonMessages.EDOTAChatWheelMessage.valueOf( id ) to get the message name of chatwheel. However when it comes to a dotaplus chatwheel some nemestice chatwheel or spray, I tried to output the message but it only contain chat message id as following (we already got id below 85):

chat_message_id: 82001
player_id: 7
param_hero_id: 0
emoticon_id: 0

chat_message_id: 71
player_id: 4
param_hero_id: 100
emoticon_id: 0

chat_message_id: 100001
player_id: 5
param_hero_id: 0
emoticon_id: 0

So do you have any idea how to get human readable names from these chatwheels?

**Comment by spheenik** [comment]
No idea.
Might well be that the mapping is in the data of the dota client itself.
I'd look in the vpaks where those messages are, and try to write a small tool that extracts ids.

**Comment by BusyLivingDota** [comment]
well I did a little bit tryout and get some arangement to these id:
1-85: basic chatwheels we got in EDOTAChatWheelMessage 
86-120(might be inaccurate): dotaplus sounds chatwheel, works on allies team only.
328-330: three Guild chatewheels for all chat
331-333: three Guild sprays
334-343: Nemestice sprays
354-358: Nemestice sounds chatwheel, seems work on allies team only
XXX00Y: Hero chatwheel of dotaplus, XXX from 1 to 121 for the hero ID I guess; Y from 1 to 9, and when Y =1,2 the chatwheel is for allies and 3-9 for all.
140XXX: Team support sprays and chatwheels at all chat. Can't really distinguish these cheesy lines.

Do you have any idea how to get heroID with its name? I found https://github.com/skadistats/skadi/wiki/Hero-Names-and-IDs but it's from 7 year ago and require to update.

**Comment by spheenik** [comment]
You can query the Valve Web-API (needs apikey), or, if you just want to click: [OpenDota API](https://api.opendota.com/api/heroes).

**Comment by spheenik** [comment]
Lol, OpenDota even has enriched data which tells you that Broodmother has 8 legs :leg::leg::leg::leg::leg::leg::leg::leg:, while Wisp has none: :sob:

**Comment by BusyLivingDota** [comment]
I got it! Thanks a lot!

**Comment by BusyLivingDota** [comment]
I'm definately losing my braincell on that website
