### ISSUE TITLE
Can't find taunt usage in replay

### ISSUE THREAD

**Issue by BusyLivingDota** [skadistats/clarity#262]
Hello:

I use SpectatorPlayerUnitOrders in order to find taunt usages. However it never gives any. I'm pretty sure AA used taunt at 3:30 in game 6066544589 but the processor detect nothing. Here is my processor please help me! (Or is there another way to detect taunt using?)

```java
 @OnMessage(DotaUserMessages.CDOTAUserMsg_SpectatorPlayerUnitOrders.class)
    public void taunt(DotaUserMessages.CDOTAUserMsg_SpectatorPlayerUnitOrders message){
        if(message.getOrderType()==22){
            output.add(message.toString() + ClockTime.getClockTime(entities) );
        }
    }
```

**Comment by spheenik** [comment]
I'm not sure. If I remember correctly, `CDOTAUserMsg_SpectatorPlayerUnitOrders` is only there when there are actual spectators in the game. If I'm right, this is a bit like Schrödingers cat. If no one is there to spectate, the player did taunt, and not taunt at the same time...

**Comment by BusyLivingDota** [comment]
Well the game I'm using is Fnatic's ti qualifier game against Omega Gaming and there were 12 spectators, and its lived all over the world. I just run throw all Fnatic and Undying games in the regional qualifier and get nothing (21 games total). No doubt all of these games have more than 3 actual spectators, and get nothing.

**Comment by spheenik** [comment]
:man_shrugging:

**Comment by BusyLivingDota** [comment]
Sorry for wasting you time but I solve my problem again. There is a m_flTauntCooldown property for every Hero Entity and I just found out that whenever the player uses taunt the property changes value. The value seems be the taunt used second of m_pGameRules.m_fGameTime property of the proxyrules, so everything is awesome now!

**Comment by spheenik** [comment]
Fantastic way to solve this!
