### ISSUE TITLE
[bug?] Strategy time purchases don't appear in combat log

### ISSUE THREAD

**Issue by reacheight** [skadistats/clarity#268]
**Steps to reproduce**
Run processor with something like
```java
@OnCombatLogEntry
public void onCombatLogEntry(CombatLogEntry cle) {
    if (cle.getType() == DotaUserMessages.DOTA_COMBATLOG_TYPES.DOTA_COMBATLOG_PURCHASE) {
        System.out.println(cle.getValueName());
    }
}
```
with `SimpleRunner` or `ControllableRunner`.

**Expected behaviour (?)**
Items purchased during strategy time are printed.

**Actual behaviour**
Only items purchased after strategy time are printed.

Examples of matches: 6158170178, 6165650952.

**Comment by spheenik** [comment]
Nope, not a bug. There is nothing in clarity that would remotely be able to filter combat log events during strategy time. 
It must be something within the dota client, preventing to issue those events.

Only thing you can do is to look at the entity when it first spawns, all items that are already there must have been bought during strategy time.
