### ISSUE TITLE
Can't Find Entity ByHandle When Illusion Rune Used

### ISSUE THREAD

**Issue by BusyLivingDota** [skadistats/clarity#269]
Greeting:

I am currently looking for item purchasing and combining in dota2. However there are item entities created also when illusions are created. I try to except them by identify their owners and see if its an illusion. However I can receive the owner's handle but can not find it using  **entities.getByHandle(e.getProperty("m_hOwnerEntity"))**. Such situation only happens at tick that a hero create illusions. By the way its pretty intresting because in such circumstances the item name shown is abnormal. Like bloodstone normally should be CDOTA_Item but in such situation it becomes CDOTA_Item_Bloodstone(and powertreads too). I think it should be a bug or something, hope someone can help, much thanks!

I am having trouble uploading the code and dem file, so you maybe have to download the rep yourself, or just use a random dem and change the filepath.

Here is my code:

```java
//code start here
package busyliving.githubissue;

import skadistats.clarity.event.Insert;
import skadistats.clarity.model.Entity;
import skadistats.clarity.model.StringTable;
import skadistats.clarity.processor.entities.Entities;
import skadistats.clarity.processor.entities.OnEntityCreated;
import skadistats.clarity.processor.entities.UsesEntities;
import skadistats.clarity.processor.runner.Context;
import skadistats.clarity.processor.runner.SimpleRunner;
import skadistats.clarity.processor.stringtables.StringTables;
import skadistats.clarity.processor.stringtables.UsesStringTable;
import skadistats.clarity.source.MappedFileSource;

import java.util.ArrayList;

@UsesStringTable("EntityNames")
@UsesEntities
public class ItemCreated {
    
    //replay file path
    static final String REPLAY_PATH = "C:\\Users\\Administrator\\Desktop\\6167888335.dem";
    
    static ArrayList<String> output = new ArrayList<>();
    static ArrayList<String> exceptionHandles = new ArrayList<>();

    @Insert
    Context ctx;
    @Insert
    Entities entities;

    @OnEntityCreated
    public void itemBought(Entity e) {
        if (!e.getDtClass().getDtName().contains("CDOTA_Item")) {
            return;
        }
        if (e.getDtClass().getDtName().contains("Rune") || e.getDtClass().getDtName().equals("CDOTA_Item_Physical")) {
            return;
        }

        StringTable stringTable = ctx.getProcessor(StringTables.class).forName("EntityNames");
        try {
            Entity owner = entities.getByHandle(e.getProperty("m_hOwnerEntity"));

            //if the item has an owner but we can't find it, then add its info to the arrayList.
            if (owner == null && (int)e.getProperty("m_hOwnerEntity") != 16777215) {
                exceptionHandles.add(ctx.getTick() + "\t" + e.getDtClass().getDtName() 
                        + "\t" + e.getProperty("m_hOwnerEntity"));
            }
            /* There are cases an item is owned by a courier, then we let owner point to the owner of the courier.
            *  There are also cases that a courier is owned by a player but not hero, 
            *  then we point it to the assigned hero.
            * */
            if (owner.getDtClass().getDtName().contains("Courier")) {
                owner = entities.getByHandle(owner.getProperty("m_hOwnerEntity"));
            }
            if (owner.getDtClass().getDtName().contains("CDOTAPlayer")) {
                owner = entities.getByHandle(owner.getProperty("m_hAssignedHero"));
            }
            //roshan can have items too, skip it.
            if (owner.getDtClass().getDtName().equals("CDOTA_Unit_Roshan")) {
                return;
            }
            //if the owner is an illusion or clone, then we skip.
            if (!((int) owner.getProperty("m_hReplicatingOtherHeroModel") == 16777215)) {
                return;
            }
            output.add(ctx.getTick() + "\t" 
                    + stringTable.getNameByIndex(e.getProperty("m_pEntity.m_nameStringableIndex")) 
                    + "\t" + owner.getDtClass().getDtName());

        } catch (NullPointerException npe) {
            output.add(ctx.getTick() + "\t" + npe + "\t" 
                    + e.getDtClass().getDtName() 
                    + e.getProperty("m_hOwnerEntity"));
        }
    }

    public void run(String args) throws Exception {
        new SimpleRunner(new MappedFileSource(args)).runWith(this);
    }

    public static void main(String[] args) throws Exception {
        long tStart = System.currentTimeMillis();

        new ItemCreated().run(REPLAY_PATH);

        for (int i = 0; i < output.size(); i++) {
            System.out.println(output.get(i));
        }

        System.out.println("======Exceptions That Owner Handle Is There But Can't Find Owner======");

        for (int i = 0; i < exceptionHandles.size(); i++) {
            System.out.println(exceptionHandles.get(i));
        }

        long tMatch = System.currentTimeMillis() - tStart;

        System.out.println("total run " + tMatch / 1000.0 + " sec");

    }
}
```

**Comment by spheenik** [comment]
Clarity fires the `@OnEntitySomething`-Events in the order they are received in the replay. It might well be that the entity you're looking for is created later in the same tick. This is not a bug - it's just the way it is. One way to "work around" this is to keep a list of all lookups you want to do, and defer the lookup to then end of the tick with `@OnTickEnd`:

```java

private List<Runnable> actions = new ArrayList();

@OnEntityCreated
public void onCreated(Entity e) {
  // bail if it's not the right entity
  actions.add(() -> {
    Entity owner = entities.getByHandle(e.getProperty("m_hOwnerEntity"));
    // do the work here
  }
}

@OnTickEnd
public void onTickEnd(boolean synthetic) {
  actions.forEach(Runnable::run);
  actions.clear();
}

```

Let me know if this helped.

**Comment by BusyLivingDota** [comment]
I modified my code according to your instruction. It works perfectly. Even though there is still some NPE somewhere, but none of them triggered by can't find an entity with a handle.

//code start here
package busyliving.githubissue;


import skadistats.clarity.event.Insert;
import skadistats.clarity.model.Entity;
import skadistats.clarity.model.StringTable;
import skadistats.clarity.processor.entities.Entities;
import skadistats.clarity.processor.entities.OnEntityCreated;
import skadistats.clarity.processor.entities.UsesEntities;
import skadistats.clarity.processor.reader.OnTickEnd;
import skadistats.clarity.processor.runner.Context;
import skadistats.clarity.processor.runner.SimpleRunner;
import skadistats.clarity.processor.stringtables.StringTables;
import skadistats.clarity.processor.stringtables.UsesStringTable;
import skadistats.clarity.source.MappedFileSource;

import java.util.ArrayList;

@UsesStringTable("EntityNames")
@UsesEntities
public class ItemCreated2 {

    //replay file path
    static final String REPLAY_PATH = "C:\\Users\\Administrator\\Desktop\\6167888335.dem";

    static ArrayList<String> output = new ArrayList<>();
    static ArrayList<String> exceptionHandles = new ArrayList<>();
    static ArrayList<Entity> items = new ArrayList<>();

    static boolean tickEnd = false;
    @Insert
    Context ctx;
    @Insert
    Entities entities;

    @OnEntityCreated
    public void itemBought(Entity e) {
        if (!e.getDtClass().getDtName().contains("CDOTA_Item")) {
            return;
        }
        if (e.getDtClass().getDtName().contains("Rune") || e.getDtClass().getDtName().equals("CDOTA_Item_Physical")) {
            return;
        }
        ItemCreated2.items.add(e);
        tickEnd = true;

    }

    @OnTickEnd
    public void onTickEnd(boolean synthetic) {
        if (tickEnd) {
            doTheWork();
        }
        items = new ArrayList<>();
        tickEnd = false;
    }

    private void doTheWork() {
        for (Entity e : items) {
            StringTable stringTable = ctx.getProcessor(StringTables.class).forName("EntityNames");
            try {
                Entity owner = entities.getByHandle(e.getProperty("m_hOwnerEntity"));

                //if the item has an owner but we can't find it, then add its info to the arrayList.
                if (owner == null && (int) e.getProperty("m_hOwnerEntity") != 16777215) {
                    exceptionHandles.add(ctx.getTick() + "\t" + e.getDtClass().getDtName()
                            + "\t" + e.getProperty("m_hOwnerEntity"));
                }
                /* There are cases an item is owned by a courier, then we let owner point to the owner of the courier.
                 *  There are also cases that a courier is owned by a player but not hero,
                 *  then we point it to the assigned hero.
                 * */
                if (owner.getDtClass().getDtName().contains("Courier")) {
                    owner = entities.getByHandle(owner.getProperty("m_hOwnerEntity"));
                }
                if (owner.getDtClass().getDtName().contains("CDOTAPlayer")) {
                    owner = entities.getByHandle(owner.getProperty("m_hAssignedHero"));
                }
                //roshan can have items too, skip it.
                if (owner.getDtClass().getDtName().equals("CDOTA_Unit_Roshan")) {
                    return;
                }
                //if the owner is an illusion or clone, then we skip.
                if (!((int) owner.getProperty("m_hReplicatingOtherHeroModel") == 16777215)) {
                    return;
                }
                output.add(ctx.getTick() + "\t"
                        + stringTable.getNameByIndex(e.getProperty("m_pEntity.m_nameStringableIndex"))
                        + "\t" + owner.getDtClass().getDtName());

            } catch (NullPointerException npe) {
                output.add(ctx.getTick() + "\t" + npe + "\t"
                        + e.getDtClass().getDtName()
                        + e.getProperty("m_hOwnerEntity"));

            }
        }

    }

    public void run(String args) throws Exception {
        new SimpleRunner(new MappedFileSource(args)).runWith(this);
    }

    public static void main(String[] args) throws Exception {
        long tStart = System.currentTimeMillis();

        new ItemCreated2().run(REPLAY_PATH);

        for (int i = 0; i < output.size(); i++) {
            System.out.println(output.get(i));
        }

        System.out.println("======Exceptions That Owner Handle Is There But Can't Find Owner======");

        for (int i = 0; i < exceptionHandles.size(); i++) {
            System.out.println(exceptionHandles.get(i));
        }

        long tMatch = System.currentTimeMillis() - tStart;

        System.out.println("total run " + tMatch / 1000.0 + " sec");

    }
}

**Comment by spheenik** [comment]
No, not at all. An entity object IS the TrueEntity object (whatever you mean by this).
It holds an EntityState object, which will change on a tick by tick basis.
A handle *identifies* the entity.

**Comment by BusyLivingDota** [comment]
Sorry that was my mistake get this thing wrong. I was unable to find the owner entity because the illusion's items are created before illusions. Whenever an illusion's item is created, it's "m_hOwnerEntity" property is pointing to the illusion looking for ward to created but not yet, so we solve it by put out work on the end of the tick.

Thanks for your patiance again, really appreciate!
