### ISSUE TITLE
Equipment sale

### ISSUE THREAD

**Issue by yangex** [skadistats/clarity#270]
I can't get the item sales。
CombatLogEntry.Type contains DOTA_COMBATLOG_PURCHASE. I don't understand why it doesn't include DOTA_COMBATLOG_SELL?
I would appreciate it if you could help me！

**Comment by spheenik** [comment]
Hehe, not all is logical in the world of Valve. If that combat log type is not there, they are simply not generating it. You might be able to track sales when the item entity gets deleted though.

**Comment by yangex** [comment]
hah,I'm so stupid.Thank you for reminding me
