### ISSUE TITLE
Some questions about buy back 

### ISSUE THREAD

**Issue by yangex** [skadistats/clarity#272]
I suddenly found that GoldReason is not included 2 in the DOTA_COMBATLOG_TYPES.DOTA_COMBATLOG_GOLD。
I'd like to know how much it costs to buy back now。
Look forward to your reply。

**Comment by spheenik** [comment]
Hmm. Valve do stuff like this all the time. I'm not sure how I could help you. If it's gone, it's gone :(

**Comment by yangex** [comment]
I found other ways to solve this problem。
![企业微信截图_1637313672991](https://user-images.githubusercontent.com/42961347/142606724-291cc526-b6b4-4c44-9264-14bb535bba28.png)
It can be calculated by this formula。I tried. This formula is correct。
