### ISSUE TITLE
How to check if a summoned unit was killed?

### ISSUE THREAD

**Issue by reacheight** [skadistats/clarity#273]
Hello! I'm trying to calculate how much gold a player fed with its summons. The problem is I don't know how to properly check if a summon was really killed by another player, and it's not just its lifetime ended. Currently, I'm tracking the lifeState property, but its behavior is the same for both cases. Can we get this information from a summon entity somehow?

**Comment by spheenik** [comment]
I think you might get this information from the combat log. It should contain an entry for the summon dying, which should contain information about who did the last blow.

**Comment by spheenik** [comment]
I think you might get this information from the combat log. It should contain an entry for the summon dying, which should contain information about who did the last blow.

**Comment by reacheight** [comment]
Yeah, I knew about the combat log, but I didn't know how to link a summon entity (which contains information about its gold bounty) and its combat log entries.

I ended up like this: for every log entry for summon kill (basically I count every unit as a summon if its source is a hero except for the hero itself and observers/sentries) I take its killer hero and search for the DOTA_COMBATLOG_GOLD entry with the same timestamp for this hero. So in the first entry I check if a summon was killed, and in the second entry I check how much gold it gave to the enemy.
