### ISSUE TITLE
How to get the item quantity

### ISSUE THREAD

**Issue by yangex** [skadistats/clarity#274]
hello,The two item_ward merge into item_ward_dispenser.
I want to get the quantity of each,but I don't know how to do it.
Look forward to your reply！！

**Comment by spheenik** [comment]
Hmm, don't know from the top of my head.
I'm pretty sure @Noxville does.

**Comment by reacheight** [comment]
m_iCurrentCharges property of CDOTA_Item_Ward_Dispenser entity

**Comment by yangex** [comment]
Thank you very much for helping me a lot.
