### ISSUE TITLE
ControllableRunner seek is halting

### ISSUE THREAD

**Issue by larry-barry** [skadistats/clarity#276]
I have a very basic script that I am testing with:

```
this.runner = new ControllableRunner(new MappedFileSource(this.replayFile));
this.runner.runWith(this);
System.out.println("test");
this.runner.seek(1);
System.out.println("test2");
this.runner.halt();
```

It gets as far as test, does the seek... and never makes it to the second test2 output.

Am I doing something wrong? SimpleRunner works fine.

**Comment by gogogram-john** [comment]
Ah I see the problem. I need to decorate the class with `@UsesEntities`

**Comment by larry-barry** [comment]
Ah I see

**Comment by larry-barry** [comment]
I see the problem. Need to decorate the class with `@UsesEntities`
