### ISSUE TITLE
CDOTA_DataSpectator.m_iNetWorth  error

### ISSUE THREAD

**Issue by yangex** [skadistats/clarity#278]
match_id:6369655877
frames: 68926

![image](https://user-images.githubusercontent.com/42961347/149073038-47d5168d-cafb-4c87-b620-800d3533ba79.png)

![image](https://user-images.githubusercontent.com/42961347/149073181-c1591ac1-425e-451e-bd63-a72a86b4c7e9.png)

As shown in the figure，the m_iNetWorth.0001(Void Spirit)  do  not match,less than 2000.

I wonder why，thank you.

**Comment by spheenik** [comment]
Hmm. 
- is the sorting correct? Your sorting in the screenshot seems to be by networth, and in the replay it's by player index.
- Are you sure it's the correct tick?

**Comment by yangex** [comment]
I'm sure, this Is It.I use commands demo_gototick  to 68926.

![image](https://user-images.githubusercontent.com/42961347/149147604-d2b70c3a-ca0f-4142-a58a-781ed443b01c.png)

Void Spirit happens to be the second.

The data of other heroes can match.

**Comment by reacheight** [comment]
![изображение](https://user-images.githubusercontent.com/21079607/149916549-6ccd1fcc-b8b4-4f82-bd01-b1c4de3cf83e.png)
actually, there is a moment in the replay, when we can see void spirit's networth drops by 2400 gold (right when his courier delivers him boots of travel ¯\\_(ツ)_/¯ ) and then goes back. to see this I had to replay this moment multiple times, in most cases it doesn't change.

**Comment by spheenik** [comment]
Nice find, @reacheight .
This basically means that there is a short amount of time when the item is neither on the courier and the hero.
It kind of phase shifted :)
Might be just a coincidence, that in this replay, at that exact amount of time the networth is updated.
