### ISSUE TITLE
How to map the cursor position of a player to the currect world location?

### ISSUE THREAD

**Issue by TheAmazingLooser** [skadistats/clarity#280]
Well the question most likely stands for itself. I want to map the current cursor of a player to see if the player currently hovers over a rune, hero, creep,... (basically any kind of object on the map)
I do only have the cursor-position so far (I'm fairly new to the parser and java overall).
Is there an already built-in function/example/working code i could use or do I have to code it myself?
If the latter is the case, how exactly can I find out the camera position of a player (since its needed to calculate the coursor position)?

**Comment by spheenik** [comment]
I don't know. There is a camera position in the player entity, but you would have to project the cursor position into the world somehow. No idea how.
