### ISSUE TITLE
Hello! I'd like to use your parser, but I'm kinda new, can you give me some pointers?

### ISSUE THREAD

**Issue by Whoeza** [skadistats/clarity#281]
Hi there Martin,

I've read the OpenDota page "lessons learned from parsing X millions of replays" and I was convinced I wanted to use Clarity.

I'd like to use Clarity but I don't know how it works. So far, I understand that you can parse what you specify in the form of events that you listen for. Is this the key concept to understand how Clarity works?

I have experience in Java, but not in Maven. Do I need to understand Maven in order to use Clarity? (example, I see the java files and I installed Maven, but I don't see a way that I can run any file, not even the clarity-examples are running for me)

Can we have a talk on Discord maybe?

Can I suggest and/or help making a documentation for your project?

Best regards,

Whoeza

**Comment by reacheight** [comment]
Hi! I've been using clarity for a while, that's how I see the process of parsing a replay in the core.

At any given moment of a replay it's state is defined by the set of entities. The entities contain information in their properties. For example, for every unit in a replay (like hero, creep, courier, tower and so on) there is an entity that represent it. Such entities have properties with it's HP, Mana, Attack Damage and many more. There are also entities that don't represent some unit, but just contain useful information, like `CDOTAGamerulesProxy`, which contains info about game time and state. So, yeah, a replay is essentially a sequence of events on the entities or their properties, that you can listen for.

What I recommend to do to get familiar quickly:
1) Use [clarity-analyzer](https://github.com/spheenik/clarity-analyzer), it **really** helps to understand what I've wrote above. And you need to know what entities and properties there are in a replay to parse it anyways.
2) Check [clarity-examples](https://github.com/skadistats/clarity-examples).
3) Check issues in this repo and search them first if you have a question, there is a lot of info.
4) Try build something small :). You'll learn basics quickly.

What about Maven, I don't think you need deep understanding of it. Just google basic stuff about installing a package I guess.

Good luck!

**Comment by Whoeza** [comment]
Thank you Rom!

**Comment by Whoeza** [comment]
I tried checking the clarity-analyzer, but it was too much code about JavaFX than parsing, that I quickly lost interest. I found the clarity-examples much more useful. I'll try again from that, and maybe from Manta or Clarity themselves.
Do you know how to write a parser or how to parse replays from .dem files yourself, @reacheight ?

**Comment by reacheight** [comment]
No, I don't.

No need to check clarity-analyzer code, just download, build and use it.
