### ISSUE TITLE
List of full m_hItems possible values

### ISSUE THREAD

**Issue by ucontacti** [skadistats/clarity#282]
I have got a piece of code that gets the id and name of the items like this:

`String item_slot = String.format("m_hItems.%04d", i);`
`int item_id = et.getProperty(item_slot);`
`String item_name = getEntityNameByHandle(item_id, entities, stringTable);`

But I want to do a onehotencoder. To do that I need to have a list of all item_id values. It would be great to have a list of all possible one-to-one mapping of each item_id and the corresponding String value.

**Comment by spheenik** [comment]
If I remember correctly, the item name is in the string table "ItemNames", and your code seems to suggest that you know this already. They string table gets filled as the game progresses, so only items used in the game show up. This also means that the item_id is not constant across games, as it is the index into the string table.

What exactly is a onehotencoder?

**Comment by spheenik** [comment]
Yes, since the string table is empty at the start of the replay, then gets filled with a new entry every time a new item gets bought that was not there before, increasing the index.

**Comment by ucontacti** [comment]
Thank you
That was really helpful
