### ISSUE TITLE
Issues with console recorded replays

### ISSUE THREAD

**Issue by nyxnyxnyxdota** [skadistats/clarity#284]
Hello.

I was playing with this amazing parser and while it shows combat log entries for Dota TV replays, it never shows combat log entries for console recorded replays. I read in other issues that Valve frequently breaks them. Is that the current state of things? Is it broken in a way that Clarity is unable to show combat log entries for these replays?

Thanks.

**Comment by spheenik** [comment]
I'm not sure. Might well be. Can you try playing back your replay in the client, and check if there are combat logs?
If yes, then there's 2 possibilities: 

1. Client creates them on the fly, in which case we're out of options.
2. There is a bug in clarity, which I would gladly fix.

So, check it, and report back. Thank you!

**Comment by nyxnyxnyxdota** [comment]
I played it with `playdemos <filename>` and it seems like the combat log is empty. Does that mean it's not available in the replay or could it be that the game is not playing the replay file properly? In general it feels buggy. The replay file is big, 50MB. Very weird that it doesn't contain any combat info.

I uploaded the replay file to my [Google Drive](https://drive.google.com/file/d/1ZIizN2Z3lOXLITB2RzyEwHT7Laek1dEE/view?usp=sharing), is there any chance you can take a look? I'd appreciate it!

**Comment by spheenik** [comment]
Checked the replay, it contains no combat log. Did a little research, there is a console command `dota_combatlog_file` which takes a file where events are supposedly written. Maybe this will do? (will most certainly not be parseable with clarity though, but who knows.

**Comment by nyxnyxnyxdota** [comment]
Sorry for the late reply. I tested this command and seems like it's disabled. Whether it's a real match, demo hero or a custom lobby with cheats, no file is created. Not sure there's anything else to do then :|

Thanks anyway for the help and for this great tool!
