### ISSUE TITLE
Missing ABILITY_PING_INCOURIERBACKPACK

### ISSUE THREAD

**Issue by Whoeza** [skadistats/clarity#292]
Hi! I was learning how the `combatlog` example works from the `clarity-examples` repository and I found that `ABILITY_PING_INCOURIERBACKPACK` is present in the `GameTracking-Dota2` repository but not in clarity's.
Does it mean the current clarity does not parse `ABILITY_PING_INCOURIERBACKPACK`?

If I get better at this, I will send a pull request to help updating clarity. At present time, I can open the issue here at best.
Cheers

**Comment by spheenik** [comment]
Will be there once I pushed the new clarity-protobuf updates.
They are already running locally, so a matter of hours.

**Comment by spheenik** [comment]
Update pushed an hour ago.
