### ISSUE TITLE
Where did fGameTime go?

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#296]
This is not a Skadi issue, I dont think. However, they removed `EntityHelper.getEntityPropertyField(gameRulesProxy, "m_pGameRules.m_fGameTime", null);` 

Anyone with an idea how to find it or calculate in-game time, please reply here.

**Comment by builder-247** [comment]
Just a wild guess based on the commit - `GameTime_t` ? https://github.com/skadistats/clarity/commit/f9bde0340d2056bcb3d9b47e7939ea5b695cbb0e

**Comment by spheenik** [comment]
I can confirm that the property is no longer available, the send tables no longer contain `m_fGameTime`. They contain new properties though: `m_nTotalPausedTicks`, as well as a `m_nPauseStartTick` and `m_bGamePaused`.

It seems like one could be able to calculate the game time from this.
My guess would be that `m_nTotalPausedTicks` gets updated at the end of a pause.

So, to calculate it:
`gameTime = (m_bGamePaused ? replayTick : m_nPauseStartTick) / 30`

Probably `m_flPreGameStartTime` and `m_flGameStartTime` have also be taken into account, eg. the calculation must only be done if `m_flGameStartTime` is zero.

I suspect Valve did this because they realized that replays get a a substantial amount smaller by doing it this way.
I can't code together something right now, earliest tomorrow. But I will gladly add a utility function that does the computation right, once we figured out how to.

**Comment by STRATZ-Ken** [comment]
Unfortunately, these values are always 0.

![image](https://user-images.githubusercontent.com/24981405/223546508-4df5ef49-a61b-400a-8716-82ae4d826d1c.png)

**Comment by spheenik** [comment]
And there was a pause in the replay?

**Comment by STRATZ-Ken** [comment]
Nope.

**Comment by spheenik** [comment]
Then the formula should be valid.

**Comment by Tsury** [comment]
I can confirm that `m_nPauseStartTick` and `m_nTotalPausedTicks` work just as explained by @spheenik.
They are sent along with `m_bGamePaused` when it changes.

**Comment by spheenik** [comment]
I'm pretty sure the tickrate is 30/sec.
So the difference maybe comes from somewhere else.
What is `m_flGameLoadTime` in your case? Maybe if that's a time for loading the game, it could be around 7 seconds.

**Comment by STRATZ-Ken** [comment]
m_flGameLoadTime = 0.

**Comment by spheenik** [comment]
@Tsury Can you share a link to a replay with a pause?

**Comment by Tsury** [comment]
I edited my previous message, a small correction.

I don't have a link - I didn't check an official match, but recorded a dem file in a local lobby. I'm assuming the behavior is kept.

**Comment by Tsury** [comment]
Could this be a possibel formula?
`((m_nPauseStartTick || currTick) - m_nTotalPausedTicks) / 29.9999984354`

(`0.03333333507180214` is the `tickInterval` sent inside `CSVCMsg_ServerInfo`. `1/tickInterval` is `29.9999984354`)

**Comment by spheenik** [comment]
> m_flGameLoadTime = 0.

Ok. Damn.

**Comment by STRATZ-Ken** [comment]
You should be able to test it vs StartGameTime.  Since that is in seconds. @Tsury.

**Comment by spheenik** [comment]
Ok, it seems I found it. There is a message `NetworkBaseTypes.CNETMsg_Tick.class` which contains not the replay tick, but the server tick. When I compare `m_flPreGameStartTime` and `m_flGameStartTime` (by doing serverTick/30) I come pretty close.

**Comment by spheenik** [comment]
@Tsury 

> `((m_nPauseStartTick || currTick) - m_nTotalPausedTicks) / 29.9999984354`

Yes, should work, but then you rely on them setting `m_nPauseStartTick` to zero on unpause. They are probably going to keep the behaviour, but just to be on the safe side...

**Comment by Tsury** [comment]
@spheenik Yeah I agree - better safe than sorry and use `m_bGamePaused`.

**Comment by spheenik** [comment]
Anyway, off to bed. But with the info above stitching together a workaround should be possible.
Will introduce some functionality in clarity that does this for you - once the dust settles ;-)

**Comment by STRATZ-Ken** [comment]
@spheenik Can you include your test code before heading off?

**Comment by spheenik** [comment]
I don't have any, I just did some simple dump of the properties that looks like this:

```java
    @OnEntityPropertyChanged(classPattern = "CDOTAGamerulesProxy", propertyPattern = "m_pGameRules.m_fl.*Time")
    public void onPauseChanged(Context ctx, Entity e, FieldPath fp) {
        System.out.format(
                "%6d %6d %s: %s = %s\n",
                ctx.getTick(),
                serverTick,
                e.getDtClass().getDtName(),
                e.getDtClass().getNameForFieldPath(fp),
                e.getPropertyForFieldPath(fp)
        );
    }

    @OnMessage(NetworkBaseTypes.CNETMsg_Tick.class)
    public void onMessage(NetworkBaseTypes.CNETMsg_Tick message) {
        serverTick = message.getTick();
    }
```

Output (for the replay that manta has to test this with match id 7047839963):

```
     2    330 CDOTAGamerulesProxy: m_pGameRules.m_flStateTransitionTime = 71.0
     2    330 CDOTAGamerulesProxy: m_pGameRules.m_flHeroPickStateTransitionTime = 21.0
     2    330 CDOTAGamerulesProxy: m_pGameRules.m_flHeroSelectPenaltyTime = 30.0
     2    330 CDOTAGamerulesProxy: m_pGameRules.m_flGGEndsAtTime = 0.0
     2    330 CDOTAGamerulesProxy: m_pGameRules.m_flPreGameStartTime = 0.0
     2    330 CDOTAGamerulesProxy: m_pGameRules.m_flGameStartTime = 0.0
     2    330 CDOTAGamerulesProxy: m_pGameRules.m_flGameEndTime = 0.0
     2    330 CDOTAGamerulesProxy: m_pGameRules.m_flGameLoadTime = 0.0
     2    330 CDOTAGamerulesProxy: m_pGameRules.m_flRoshanRespawnPhaseEndTime = 0.0
   302    630 CDOTAGamerulesProxy: m_pGameRules.m_flStateTransitionTime = 66.0
   302    630 CDOTAGamerulesProxy: m_pGameRules.m_flHeroPickStateTransitionTime = 66.0
  1656   1984 CDOTAGamerulesProxy: m_pGameRules.m_flStateTransitionTime = 81.03334
  2104   2432 CDOTAGamerulesProxy: m_pGameRules.m_flStateTransitionTime = 97.06667
  2587   2915 CDOTAGamerulesProxy: m_pGameRules.m_flStateTransitionTime = 157.1
  2587   2915 CDOTAGamerulesProxy: m_pGameRules.m_flPreGameStartTime = 97.100006
  4387   4715 CDOTAGamerulesProxy: m_pGameRules.m_flGameStartTime = 157.13335
 49339  49667 CDOTAGamerulesProxy: m_pGameRules.m_flRoshanRespawnPhaseEndTime = 1891.4668
 53664  53992 CDOTAGamerulesProxy: m_pGameRules.m_flStateTransitionTime = 2155.6667
 53664  53992 CDOTAGamerulesProxy: m_pGameRules.m_flGameEndTime = 1795.6667
```

**Comment by timkurvers** [comment]
> Ok, it seems I found it. There is a message `NetworkBaseTypes.CNETMsg_Tick.class` which contains not the replay tick, but the server tick. When I compare `m_flPreGameStartTime` and `m_flGameStartTime` (by doing serverTick/30) I come pretty close.

Oh man, I was hoping to not have to start juggling multiple tick types. Good find 👍

**Comment by STRATZ-Ken** [comment]
Looks like everything is working with the code above.  Love it! Thanks for your help again, rest well.

**Comment by BusyLivingDota** [comment]
> Unfortunately, the git topic here, I show it doesn't equal up. Its off by 7-8 seconds.
> 
> [timkurvers/redota#93](https://github.com/timkurvers/redota/issues/93)

Man I am having same problem with a 7-8 seconds delay. Did you find the problem?

**Comment by STRATZ-Ken** [comment]
Your looking into the client ticks.  You want to use the server ticks, an example snippet of code is above.

**Comment by BusyLivingDota** [comment]
> Your looking into the client ticks. You want to use the server ticks, an example snippet of code is above.

I got it. Thanks a lot!
