### ISSUE TITLE
String Comparisons

### ISSUE THREAD

**Issue by STRATZ-Ken** [skadistats/clarity#300]
@spheenik 

What is your thoughts on your OnPropertyChanged and similar endpoints.  Looking under the hood, these are string comparisons.  Can't wait get these from FieldPaths, cache the results then be able to do FieldPath lookups directly?  

https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/processor/entities/PropertyChange.java#L63

**Comment by spheenik** [comment]
Performance-wise, @OnPropertyChanged should be avoided at all costs. It is *very* expensive.

**Comment by STRATZ-Ken** [comment]
What about other Methods, @OnEntityCreated, @OnEntityUpdated, etc.

**Comment by spheenik** [comment]
They are fine, and the recommended way to use.
