### ISSUE TITLE
CS2 support?

### ISSUE THREAD

**Issue by andinua** [skadistats/clarity#305]
Hi @spheenik , not sure if the best place to ask, but do you plan to support CS2 dem files as well? Thank you!

**Comment by spheenik** [comment]
I do, and in face there is already a branch that supports reading them.

https://github.com/skadistats/clarity/tree/csgo2

I plan to make release 3.0.0 sometime soon.

**Comment by andinua** [comment]
Sounds great, thank you!

**Comment by spheenik** [comment]
Certainly seems time.
Will see what I can do the next days.

**Comment by pmachan** [comment]
Hi @spheenik , any news about CS2 support?

**Comment by spheenik** [comment]
This weekend.
