### ISSUE TITLE
Setting descriptor in GameEvent?

### ISSUE THREAD

**Issue by stoke** [skadistats/clarity#32]
Hi,

First of all I wanna thank you for the work you've done, you are seriously awesome guys!

I was wondering why descriptor is not "settable" in the GameEvent class (https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/model/GameEvent.java#L6), I know that it probably isn't thread safe but it should allow for easier access on properties via getProperty (I am pretty new in the java world, so if you would share any thoughts on this it would be really awesome).

Thanks for your time!

**Comment by spheenik** [comment]
It's implemented that way because the meaning of the state of a gameevent is defined by it's descriptor, which is known at construction time, and should never change. Can you elaborate on the use case you have in mind? I do not understand what a settable descriptor would help with getProperty...

**Comment by stoke** [comment]
Thanks for the answer!

My main case would be in combatlog, for example this: https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/combatlog/CombatLogEntry.java#L61 could just be `event.getProperty("value")` which is much clearer imho

**Comment by spheenik** [comment]
Hey stoke,

I seem to have overlooked your response, sry.

The function you seek is already there (in GameEvent.java):

```java
    public <T> T getProperty(String key) {
        Integer index = descriptor.getIndexForKey(key);
        if (index == null) {
            throw new IllegalArgumentException("key not found for this GameEvent");
        }
        return (T) state[index.intValue()];
    }
```

The reason I lookup via index is that I don't wanna do `descriptor.getIndexForKey()` repeatedly, since properties are read a lot of times :)

And to your question: Yes, every game event has it's descriptor set at compile time.
