### ISSUE TITLE
CS2 - Issue Parsing Last tick (not only last)

### ISSUE THREAD

**Issue by ndorigatti** [skadistats/clarity#321]
Hello, referring to this comment: https://github.com/skadistats/clarity/issues/58#issuecomment-2353705537

I'm sharing here the replay data that can be viewed.

The issue is also described here: https://github.com/skadistats/clarity-examples/issues/63#issuecomment-2285761680
As you see, it's not only the last tick, but the issue happens early:  tick 103269/165098

I tried to open the replay with the demo application (Java desktop app) and it opens the file (there are some stranges on the tick bar, but it doesn't crash). In addition, python parser (derived from this project) https://github.com/LaihoE/demoparser is able to parse the same file (but is python and I prefer java code!)

This is the replay: https://drive.google.com/file/d/1rLNyzrN7Zz2s4Kpn7dC6JZbStyaPm5iS/view?usp=sharing
And this is the info file (if you want to check it too): https://drive.google.com/file/d/1YZiHdLCIA4ttbOeUf47pxsV72vabZjpb/view?usp=sharing

The file has downloaded from the game, and can be viewed in the game without issues.

If you need further info, i'm available (I can check where i put my demo code and share if needed, but i'm just doing basics now)

**Comment by spheenik** [comment]
Thanks for taking the time to report and upload the replay.
It was indeed a bug.
If I understand correctly, you recorded the replay yourself?
Anyway, release `3.1.1` can parse it.

**Comment by ndorigatti** [comment]
Oh, I have to thank you for taking time to debug and fix it! My time was really short, happy I could help!
I will try again in a few days and let you know!

The replay is a download from inside cs2 game, so official competitive match saved by valve servers. I have a folder with plenty of files, the idea is to parse them all and generate an xlsx file with all my results!
 Thank you again for your great work!💪

**Comment by ndorigatti** [comment]
Hello @spheenik , first of all my apologies for the late answer. I managed to test the update and now i can confirm i can parse the whole file (can go to last tick and read data!)

Now i'm stuck on reading header of replay, but will add a new issue. Thank you for the bugfix!
