### ISSUE TITLE
About the ordering of pick/bans in info.getGameInfo().getDota().getPicksBansList()

### ISSUE THREAD

**Issue by mkmkmkmk** [skadistats/clarity#33]
Hello there,

I have a question concerning the pick and bans list: are they always given 
in the right order if I use the following code? By "right order", I mean
the order in which the picks/bans were done at the beginning of the match.

Thanks a lot for your help, and keep doing this awesome work!
Cheers

```java
Map<String, String> properties = new LinkedHashMap<String, String>();
Demo.CDemoFileInfo info = Clarity.infoForFile(filename);

for (int i = 0; i < info.getGameInfo().getDota().getPicksBansList().size(); i++) 
{
	properties.put("pick_ban_heroid_p"+(i+1),   "" + info.getGameInfo().getDota().getPicksBansList().get(i).getHeroId());
	properties.put("pick_ban_is_pick_p"+(i+1),  "" + info.getGameInfo().getDota().getPicksBansList().get(i).getIsPick());
	properties.put("pick_ban_team_p"+(i+1),		"" + info.getGameInfo().getDota().getPicksBansList().get(i).getTeam());
}
```

**Comment by spheenik** [comment]
Hey,

there is no other indexing info in CDemoFileInfo, so I think it's safe to assume that the order in the file is correct. 
A LinkedHashMap is a Map that preserves insertion order and when you iterate over it's elements, you get them in the order you inserted them. 
Whether or not  your example is correct depends on how you use the map, and you need to provide the code for that :)

**Comment by mkmkmkmk** [comment]
Hello,
Thanks for your reply! So I assume that my code is correct:
the key for each pick/ban is also composed of the index i in the list of getPicksBansList().
When I enter
'''
properties.get("pick_ban_heroid_p1");
'''
I do indeed get the first choice that was made.

If that's correct, I shall close the issue.
Thanks a lot!
Cheers

**Comment by spheenik** [comment]
Correct :)
