### ISSUE TITLE
CS2 - How to get player information

### ISSUE THREAD

**Issue by kdchambers** [skadistats/clarity#339]
Hi,

I haven't been able to figure out how to get user information for a CS2 demo file and I was wondering if someone could point me in the right direction when they get a chance.

GameEvents (For example) just indicate the user based on their ID so I need a way to figure out who is who.

Thanks

**Comment by spheenik** [comment]
There is an annotation `@OnPlayerInfo` which you can use. There is a small example here:

https://github.com/skadistats/clarity/issues/190#issuecomment-447263977

**Comment by kdchambers** [comment]
Perfect, thank you!
