### ISSUE TITLE
Parsing replays recorded in the console

### ISSUE THREAD

**Issue by ykim** [skadistats/clarity#36]
I was just trying to parse a replay using the latest version of clarity, and I just encountered this issue:

```
Exception in thread "main" java.lang.NullPointerException
	at skadistats.clarity.decoder.PacketEntitiesDecoder.decodeDiff(PacketEntitiesDecoder.java:77)
	at skadistats.clarity.decoder.PacketEntitiesDecoder.decodeAndApply(PacketEntitiesDecoder.java:43)
	at skadistats.clarity.parser.handler.SvcPacketEntitiesHandler.apply(SvcPacketEntitiesHandler.java:22)
	at skadistats.clarity.parser.handler.SvcPacketEntitiesHandler.apply(SvcPacketEntitiesHandler.java:14)
	at skadistats.clarity.parser.HandlerRegistry.apply(HandlerRegistry.java:49)
	at skadistats.clarity.parser.Peek.apply(Peek.java:87)
```

I was looking at the relevant area, and I'm not too entirely sure how an entity would end up being null. Has this been encountered before?

**Comment by spheenik** [comment]
Hey,

> I was just trying to parse a replay using the latest version of clarity, and I just encountered this issue:
> 
> Exception in thread "main" java.lang.NullPointerException
>     at skadistats.clarity.decoder.PacketEntitiesDecoder.decodeDiff(PacketEntitiesDecoder.java:77)

This should not happen unless Valve did change something in the replay data.
Can you supply the match ID?

**Comment by ykim** [comment]
It's a recorded demo actually. I'm guessing the structure of it is different.

**Comment by spheenik** [comment]
How did you record it? Via some console commands?

**Comment by ykim** [comment]
Correct. I was curious to see if the recorded demo structure was different. It was going fine until I hit this issue, which probably indicates that there's some differences.

**Comment by spheenik** [comment]
Can you point me to instructions about how to record one myself?
Then I could try to debug this.

**Comment by ykim** [comment]
Is it easier if I send you an example recorded demo?

**Comment by sancai** [comment]
There was a dota2 protobuf update on steamkit , https://github.com/SteamRE/
SteamKit/pull/100
Could that be the culprit?

**Comment by spheenik** [comment]
Sure, just send it to clarity@martin.schrodt.org

I suspect that the recorded demo is in "live"-format.
In complete replays, you see the server side of things - you see all entities, etc.
In live-mode, you see only your own view of the game - when something disappears in the fog, it's entity is not updated anymore.
This makes map hacking impossible.

I remember speaking to a guy who was working on a "live" parser (capturing packets while watching in client and decoding them on the fly) and he said there were some differences.
Maybe recordings are a neat way to implement live mode without the hassle of having to watch in the client and capture packets.

I will not be able to come up with a solution soon though, since I have 2 other things I wanna finish.

- I am working on a "2.0" with a much nicer to use interface.
- I wanna refactor the protobuf-generation stuff out into a separate library, which can be used from 1.1 and 2.0 branches.

**Comment by ykim** [comment]
@spheenik : Alright, I sent an example recorded demo format.

Any chance you could detail out what 2.0 would be like? Currently, I coded up euls, which attempts to bring an abstraction of DOTA2 entities using clarity. It'd be nice to have a heads-up on what to anticipate, so I can adjust it appropriately. Thanks a lot! :D

**Comment by spheenik** [comment]
Entities will stay the same. So an abstraction layer on them to get at their data more comfortable should not be affected much.

I wanna change clarity to an event oriented processor.
This will be designed from the bottom up, so for example there will be a reader "processor" defined by clarity, which provides you with a @OnMessage event, which is called whenever a new packet on the replay is read.

So, you could hand clarity a class Test {
  @OnMessage
  public void messageRead(Context ctx, GeneratedMessage message) {
    // do something with the packet
  }
}

Then there will be other processors, which for example handle string table generation and updating, or entity decoding.

Then, there would be other "processors" in clarity, which will build on top of this, and provide more fine grained events like

@OnCombatLogEntry, @OnEntityCreated, @OnEntityChanged, @OnHeroPicked, ...

The providers of those elements will define in code what kind of data they need from the replay, so when looking at the events you wanna see, it will be able to deduce which packets from the replay will have to be processed, which in turn makes Profiles obsolete :) You just define what you wanna see by the events you listen to, and clarity will figure out what data is needed.

Another thing I wanna do is factor the protobuf-classes out into a separate project, which can then be used by the 1.1 and 2.0 branches.
That way, 1.1 wont stop working once 2.0 is released.

Cheers :)

**Comment by ykim** [comment]
@spheenik : That sounds pretty sick. I like the protobuf-class separation. I imagine that will make it easier for when Source2 rolls around. Please let me know if there's anything I can do to help debug this. I'm investigating on my end also.

**Comment by spheenik** [comment]
hey ykim,

I just put the 2.0-dev branch up.
Have a look at the clarity-examples README, it'll show you how to get started.
Let me know what you think!

**Comment by ykim** [comment]
@spheenik : Thanks. I'll take a closer look at it and follow up with some issues, thoughts, etc.

**Comment by spheenik** [comment]
Just a quick note: The replays are really like live data (UDP-Traffic when watching directly in the client) and they seem to have some cases clarity is not yet prepared to handle. :disappointed: 

I'm gonna look for solutions...

**Comment by ykim** [comment]
Any new findings for this particular issue? I'm guessing it's still an issue with clarity-2.0.

**Comment by ykim** [comment]
As a heads up, here's a hacky quick fix I made to be able to parse recorded replays: https://gist.github.com/ykim/730daf949808e4e6183c

I'm noticing that some entities become missing, which makes sense since some packets are malformed. I haven't had time to do some more digging, but I'll let you know as I find more.

**Comment by spheenik** [comment]
Hey man,

sorry, had a lot of work lately, and didn't have the muse to touch clarity.

I spent some time on research into this topic several weeks ago, to little avail.
And I don't wanna spray the code with nasty hacks so that the parsing completes, but the data is bogus anyway. So, as long as I do not understand what's going on...

The console replays contain 2 baselines and control data to switch between them. There is also delta updates to entity states at a certain Net_Tick. And then, I get entity deletion requests, and then updates for those on the next tick... 

Also I think there is nothing malformed... just encoded differently.

**Comment by moritzuehling** [comment]
Hey, 

I have implemented the switchable baselines for CS:GO (Source Engine 2013) in a private Repo. 

The way it basically works is the following: On Entity-Create there is sometimes a baseline sent with - if the Server-Class matches the class of the entity that was in the slot before, you use the instance-baseline. The instance-baseline is generated when update_baselines is true. 

I sadly don't have the time to implement this in code for you, but here is the relevant source code. The parser is written in C# and uses some different structs than you do, but it should be applicable. 

[This part](https://gist.github.com/moritzuehling/43d6f10e763efd66b9ba#file-parse_entities-cs-L11) is a bit weird. I reverse-engineered this, and it seems to work in 100% of CS:GO. 

[This part](https://gist.github.com/moritzuehling/43d6f10e763efd66b9ba#file-parse_entities-cs-L128) is also important. Stuff is basically updated here. 

First you try to take the special instance-baseline, and then you take the generic one. [See here](https://gist.github.com/moritzuehling/43d6f10e763efd66b9ba#file-parse_entities-cs-L109) 

Again, this is all from CS:GO, but it should be applicable to Dota 2. (Source 1)

**Comment by spheenik** [comment]
Thank you!
I will port this when I have the time. 
Right now, I gotta push the S2 update out :)

**Comment by spheenik** [comment]
hey Moritz,

I just wanted to have a look at it, but your gists are gone.
If you want, can you send the info to clarity@martin.schrodt.org?

Thank you!

**Comment by spheenik** [comment]
PSA: Reading console recorded replays from Reborn is now possible with the latest snapshot!

**Comment by spheenik** [comment]
Working with Source 2 replay now, and no one wants S1 support now, I guess.
