### ISSUE TITLE
Put real clarity-protobuf version as it breaks non-maven tool builds.

### ISSUE THREAD

**Issue by TimotheeJeannin** [skadistats/clarity#39]
I cannot use clarity 1.2 because it depends on clarity-protobuf with the version set at `LATEST`.

As a result Gradle fails to resolve it:

    FAILURE: Build failed with an exception.
    
    * Where:
    Build file '/home/tim/Workspace/thedotabot/replay_parser/build.gradle' line: 11
    
    * What went wrong:
    Could not resolve all dependencies for configuration ':compile'.
    > Could not find com.skadistats:clarity-protobuf:LATEST.
      Searched in the following locations:
          https://repo1.maven.org/maven2/com/skadistats/clarity-protobuf/LATEST/clarity-protobuf-LATEST.pom
          https://repo1.maven.org/maven2/com/skadistats/clarity-protobuf/LATEST/clarity-protobuf-LATEST.jar
          http://oss.sonatype.org/content/repositories/snapshots/com/skadistats/clarity-protobuf/LATEST/clarity-protobuf-LATEST.pom
          http://oss.sonatype.org/content/repositories/snapshots/com/skadistats/clarity-protobuf/LATEST/clarity-protobuf-LATEST.jar
          http://repo.maven.apache.org/maven2/com/skadistats/clarity-protobuf/LATEST/clarity-protobuf-LATEST.pom
          http://repo.maven.apache.org/maven2/com/skadistats/clarity-protobuf/LATEST/clarity-protobuf-LATEST.jar
      Required by:
          :replay_parser:1.0 > com.skadistats:clarity:1.2
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Is it possible to set a real version of clarity-protobuf so that other tools like Ivy, Sbt and Gradle can work with Clarity ? 

More details here : http://stackoverflow.com/questions/30016001/gradle-fails-to-resolve-the-dependency-of-a-dependency-marked-as-latest

Thank you for this awesome parser. :)

**Comment by spheenik** [comment]
Might do, but, since it's valid for maven, I think this should be fixed on Gradle's side...
I did this on purpose...

**Comment by sancai** [comment]
I agree with Martin.
Have you tried excluding the clarity-protobuf transitive dependency in your
build config and including it manually using 'latest.integration' as
version? It might solve your problem.
2015.05.03. 22:02 ezt írta ("Martin Schrodt" <notifications@github.com>):

**Comment by TimotheeJeannin** [comment]
Yes it solved my problem. :) Thank you. :)

**Comment by spheenik** [comment]
Thank you sancai!
