### ISSUE TITLE
missing combatlog fields in gameeventdescriptor

### ISSUE THREAD

**Issue by howardc93** [skadistats/clarity#40]
It appears that the gameeventdescriptor doesn't have some of the fields that are available in the combat log, so descriptor.getIndexForKey doesn't work for them, and dumping the GameEvent to string doesn't include these fields.

https://github.com/dotabuff/yasha/blob/e58391b610808c5a23c43e493432579085189698/dota/dota_gcmessages_common.proto#L1411

As a manual workaround I am currently defining the indices manually, but I'm getting out-of-bounds errors...

How are are the fields in GameEventDescriptor populated?

**Comment by spheenik** [comment]
Need to look at the code.

I'm on vacation now and I don't have a PC. 

I'll try to give it some time Monday.

**Comment by howardc93** [comment]
More information:

Here I am dumping the fields present in GameEventDescriptor:
https://github.com/yasp-dota/yasp/blob/92fc6c589129e9d6610a51074dd54522b8f2b55d/parser/src/main/java/yasp/YASPCombatLog.java#L99

I checked clarity-protobuf, and this includes:
https://github.com/skadistats/clarity-protobuf/blob/master/src/main/proto/dota_usermessages.proto#L863

Some of the fields, such as stun_duration, slow_duration, location_x, and location_y are missing from the GameEventDescriptor dump.  This suggests that it's not created using the combatlog protobuf definition.

I tried manually defining the indices for the missing fields:
https://github.com/yasp-dota/yasp/blob/92fc6c589129e9d6610a51074dd54522b8f2b55d/parser/src/main/java/yasp/YASPCombatLog.java#L50

This causes an ArrayOutOfBounds error, which suggests that the descriptor needs to be accurate in order to access these fields.

Or is the descriptor created based on the content of the replay file, and therefore it only contains the keys for the fields that actually exist within the replay?

**Comment by spheenik** [comment]
Hey Howard,

the GameEventDescriptor is indeed created from the replay "header" (from 
CSVCMsg_GameEventList):

https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/processor/gameevents/GameEvents.java#L48-L64

So you are right, that the replay file itself defines the amount of 
properties it's GameEvents have.

The code to create an instance of a GameEvent is here:

https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/processor/gameevents/GameEvents.java#L67-L101

Here also the replay defines the number of properties it encodes 
(message.getKeysCount()).

It seems as if the UserMessage containing the combat log is used 
elsewhere, but not in replays, and replays do only have a subset of the 
data.

**Comment by howardc93** [comment]
Okay, so I'm guessing the fields only exist in the protobuf for future use, and they should show up when populated without any code changes.  Do they have to be listed in clarity-protobuf for them to appear in the GameEventDescriptor?

Yasha's protobufs have some more additional fields that clarity-protobuf does not, does this require an update?

https://github.com/dotabuff/yasha/blob/e762361effbdd42161ea9d4f0d04993dbdf696db/dota/dota_gcmessages_common.proto#L1421-L1456

**Comment by spheenik** [comment]
Am 18.05.2015 um 02:00 schrieb Howard Chung:
>
> Okay, so I'm guessing the fields only exist in the protobuf for future 
> use, and they should show up when populated without any code changes. 
> Do they have to be listed in clarity-protobuf for them to appear in 
> the GameEventDescriptor?
>

Nope, the protobuf-message is completely unused atm. It does not appear 
in the replay.
Since they update it from time to time, there certainly is a usage 
somewhere - just not in the replay files.

> Yasha's protobufs have some more additional fields that 
> clarity-protobuf does not, does this require an update?
>
> https://github.com/dotabuff/yasha/blob/e762361effbdd42161ea9d4f0d04993dbdf696db/dota/dota_gcmessages_common.proto#L1421-L1456
>
>

I haven't updated the protobufs for a while, so they could need an update.
They mostly have to be updated when parsing errors occur with never 
replays, or when new user messages are added to the game which are also 
present in the replay.
It still won't help with populating the GameEvents.

**Comment by howardc93** [comment]
okay.  thanks!
