### ISSUE TITLE
Close File Handlers

### ISSUE THREAD

**Issue by ykim** [skadistats/clarity#51]
I was running a lot of runners consecutively, and I realized that there's no real way to close the file handlers. Is it possible to expose that as an option in the runners?

**Comment by spheenik** [comment]
You mean getting rid of MappedFileSources?

**Comment by ykim** [comment]
Is it possible to enable a close function on the MappedFileSources? If that's doable, than that seems to be fine.

**Comment by spheenik** [comment]
Hmm:

http://stackoverflow.com/questions/2972986/how-to-unmap-a-file-from-memory-mapped-using-filechannel-in-java

So you’d have to force for it to be GCed somehow.

**Comment by ykim** [comment]
Mmm... is it automatically closing after the AbstractRunner runs? If so, than that's fine. I just wasn't sure if it was.

**Comment by spheenik** [comment]
It's gone after being garbage collected...

**Comment by ykim** [comment]
Ah, okay. If that's the case, than it's fine.

**Comment by ykim** [comment]
I'm hitting an issue in production where I can't delete the files until all openers to it are closed. Is there a chance this could be exposed in the MappedFileSources somehow?

**Comment by spheenik** [comment]
Seems like it's not collected.
There are several suggested fixes in the stackoverflow thread above.
I will look into implementing a proper close function soon-ish.

**Comment by spheenik** [comment]
New snapshot uploaded.
A source now has a close() function you can call when you're done with it.
Careful: If you call anything on that source afterwards, it'll crash the VM...
