### ISSUE TITLE
Can't compile due to unmappable character

### ISSUE THREAD

**Issue by robertsmieja** [skadistats/clarity#52]
Java Compilation fails with the following error: 

```
clarity\src\main\java\skadistats\clarity\util\TextTable.java:14: error: unmappable character for encoding Cp1252
    public static final char[] FRAME_UNICODE = { 'Γöé', 'ΓöÇ', 'Γöî', 'Γö£', 'Γöö', 'Γö¼', 'Γö╝', 'Γö┤', 'Γö?', 'Γöñ', 'Γöÿ'};
```

Using Java 8, update 45 on Windows 10 64-bit, no IDE

**Comment by spheenik** [comment]
Hi, I don't really wanna merge this, as the encoding of the files is UTF-8.
I suppose you work with gradle?
Does [this](http://mrhaki.blogspot.com/2012/06/gradle-goodness-set-java-compiler.html) help?

**Comment by robertsmieja** [comment]
The post was a bit outdated but it put me on the right track. Thanks.

I left the commented line in because I understood that the non-bytecode characters improved readability, so I really didn't want to change the code either.
