### ISSUE TITLE
2.0 build break

### ISSUE THREAD

**Issue by howardchung** [skadistats/clarity#56]
Log https://jitpack.io/com/github/skadistats/clarity/2.0/build.log

Confirmed it with a local build:
`git checkout c7a0c14b4362bceb1be08057efa52aacf29bd581`
`mvn package`

Looks like the 2.0 build is broken.  Did you update the clarity-protobuf with your refactors?

**Comment by spheenik** [comment]
Yes, I did.
It is using the lastest snapshot of clarity-protobuf to build 2.0.
It should not use a snapshot at all there...

If you make it use clarity-protobuf version 2 it should work.
Why do you wanna build 2.0 anyway? It's in central.

**Comment by howardchung** [comment]
I was using jitpack to enable direct builds from GitHub so if I needed to make changes to clarity I could do so in a fork and build it directly.

I suppose I can use the central version in current master and use clarity HEAD in source2 branch.

That said, a tagged release should probably not break :)

**Comment by spheenik** [comment]
nah, leave it open, I'm gonna fix... :)

**Comment by spheenik** [comment]
and to add to that, if you tie the version of clarity-protobuf to 2, it should work.

**Comment by spheenik** [comment]
Ah well, I think no one cares about 2.0 anymore.
So I'll close, with the following notice:

To fix, the clarity-protobuf dependency in pom.xml has to be:

```
		<dependency>
			<groupId>com.skadistats</groupId>
			<artifactId>clarity-protobuf</artifactId>
			<version>2</version>
		</dependency>
```
