### ISSUE TITLE
new entity property API?

### ISSUE THREAD

**Issue by howardchung** [skadistats/clarity#57]
In clarity 2.0 it looks like this is the way to read entity state:

Assuming `pr` is an Entity object:
`Entity pr = ctx.getProcessor(Entities.class).getByDtName("DT_DOTA_PlayerResource");`
(doesn't look like this changed)

Get the index for the property (one time):
`Integer lhIdx = pr.getDtClass().getPropertyIndex("m_iLastHitCount.0000");`

Then access the entity state using the index at any time:
`Integer lh = (Integer)pr.getState()[lhIdx+i]`

However using clarity HEAD I'm seeing that the getPropertyIndex method is no longer defined--what's the new API for reading entity state?

Additionally, does the API for s1 and s2 entities differ?

**Comment by spheenik** [comment]
Yes, needed to change this, since there S2 does not have an index for a property, but a FieldPath (to allow for nested structures).
So to unify things, you now also get a FieldPath for S1, for which currently only the first entry is used.

Here is an example that will get you going:

https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/matchend/Main.java#L52-L61

**Comment by spheenik** [comment]
Btw, quick heads up:

There's now `@OnEntityEntered` and `@OnEntityLeft` in 2.1-SNAPSHOT...

**Comment by howardchung** [comment]
Awesome, I'll apply it for detecting ward placements.

**Comment by howardchung** [comment]
I haven't been able to come up with a good way to track dewards, though.
Simply watching @OnEntityLeft doesn't give context about what caused it to
leave, right? (expiration, killed by unit, etc.)

**Comment by spheenik** [comment]
right. But since wards have a ttl somewhere, I think you might find out by inspecting the entity.

**Comment by howardchung** [comment]
Any idea what causes this?

`Exception in thread "main" java.lang.RuntimeException: oops. no provider found for required usage point interface skadistats.clarity.processor.entities.OnEntityEntered`

**Comment by spheenik** [comment]
Fuckup on my side...
Gimme 10 minutes.

Am 06.09.2015 um 12:54 schrieb Howard Chung:

**Comment by spheenik** [comment]
new snapshot deployed. Plz check...

**Comment by howardchung** [comment]
Still getting it.  Is this the proper way to set up the handler?

`
	@UsesEntities
	@OnEntityEntered
	public void onEntityEntered(Context ctx, Entity e){
`

**Comment by howardchung** [comment]
Also getting this when trying to read the entity property:
```
Caused by: java.lang.NullPointerException
        at skadistats.clarity.model.s2.field.SimpleField.setValueForFieldPath(SimpleField.java:50)
        at skadistats.clarity.model.s2.field.FixedSubTableField.setValueForFieldPath(FixedSubTableField.java:74)
        at skadistats.clarity.model.s2.S2DTClass.setValueForFieldPath(S2DTClass.java:78)
        at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:40)
        at skadistats.clarity.decoder.s2.S2FieldReader.readFields(S2FieldReader.java:12)
        at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:192)
        at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:133)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:72)
        at skadistats.clarity.event.Event.raise(Event.java:23)
```

**Comment by spheenik** [comment]
I upped another snapshot. Plz check.
Also I need the match-id for the NPE.

**Comment by howardchung** [comment]
https://github.com/yasp-dota/testfiles/blob/master/1698148651_source2.dem

**Comment by spheenik** [comment]
Yea, this is a bit older (build number 983), and it misses crucial info that's needed to decode it.
Atm I am working on hardcoding stuff for certain build numbers that will allow parsing.

**Comment by howardchung** [comment]
Okay.  I'm not planning to parse older replays so I'll just try testing
with a more recent one.

**Comment by howardchung** [comment]
Still getting the error for OnEntityEntered.

Also, it doesn't seem there is a DTclass called 'DT_DOTAGamerulesProxy' in s2 replays?  Do you know if there is an analogue (or if there is a way to dump the list of DTs?)

**Comment by howardchung** [comment]
okay, think I found the dtclass name issue:

Clarity 2.0 used the DT name (DT_DOTA_*) while 2.1 uses the class name ("CDOTAGamerulesProxy").

However, it looks like getFieldPathForName() isn't implemented yet:
https://github.com/skadistats/clarity/blob/be1c00675d60760014976bd1d68c145aac7f9cd0/src/main/java/skadistats/clarity/model/s2/S2DTClass.java#L39

**Comment by spheenik** [comment]
Right, I am having a hard time imagining how to do it (efficiently)...
Maybe I'll hack something together tonight.

**Comment by howardchung** [comment]
Regarding type conversion:

In your example you get the value of the entity property out as an Object and then use .getBytes() to convert it to String:

```
                Object val = ps.getPropertyForFieldPath(fp);
                String str = new String(val.toString().getBytes("ISO-8859-1"));
```

Are you planning to leave the extracted property an Object (and have the user decide how to handle the bytes) or will you provide methods for extracting Integer, Float, etc. from the value?

**Comment by spheenik** [comment]
The signatures are like this:
```java
public <T> T getProperty(String property);
public <T> T getPropertyForFieldPath(FieldPath fp);
```
so they behave like 2.0, and "auto-cast" to whatever you assign it to.
