### ISSUE TITLE
Use for live game stream parsing?

### ISSUE THREAD

**Issue by aaron868** [skadistats/clarity#62]
I've been thinking of writing a library to capture Dota match stats in real-time from live games. Could clarity be used for this purpose? After quick look through the code it seems like I would at least need a client connection to Steam (like SteamKit provides).

Maybe this isn't even feasible. I don't know what kind of data Valve send during live matches. Any thoughts from the community?

Thanks.

**Comment by spheenik** [comment]
I've not tried, but clarity should be able to process live data (from Source 2).
To get to it, you either have to eavesdrop on the network traffic, or use SteamKit or something to connect to Steam and to the Dota game coordinator, and replicate all the steps necessary to connect to a game server as a spectator. Then you'd have to feed the UDP stream into clarity in the right order.
