### ISSUE TITLE
Issues with Maven snapshot repository?

### ISSUE THREAD

**Issue by fischerq** [skadistats/clarity#63]
Hey,

I tried to get the examples running and ran into a few problems.

As I tried to build a simple example using the 2.1-SNAPSHOT I got the following Maven error message:

    [INFO] ------------------------------------------------------------------------
    [ERROR] BUILD ERROR
    [INFO] ------------------------------------------------------------------------
    [INFO] Failed to resolve artifact.

    Unable to get dependency information: Unable to read the metadata file for artifact 'com.skadistats:clarity:jar': Error getting POM for 'com.skadistats:clarity' from the repository: Unable to read local copy of metadata: Cannot read metadata from '/home/fischerq/.m2/repository/com/skadistats/clarity/2.1-SNAPSHOT/maven-metadata-sonatype.oss.snapshots.xml': end tag name </body> must match start tag name <hr> from line 5 (position: TEXT seen ...</center>\r\n</body>... @6:8) 
      com.skadistats:clarity:pom:2.1-SNAPSHOT

    ...
 

The referenced metadata file contained a HTTP referral that did not get resolved:

    <html>
    <head><title>301 Moved Permanently</title></head>
    <body bgcolor="white">
    <center><h1>301 Moved Permanently</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>

I guess its more or less related the issues referenced [here](https://github.com/gwtbootstrap3/gwtbootstrap3/issues/167) and [here](https://issues.apache.org/jira/browse/MNG-4816). My Maven installation was completely new (installed with Eclipse) on Ubuntu 15.04

In my first attempt I tried to fix it by cloning the clarity repo, importing the project into Eclipse and enabling "Resolve dependencies from Workspace projects".

With this the dependencies resolved, but on execution I got the following exception:

    Exception in thread "main" java.lang.RuntimeException: oops. no provider found for required usage point interface skadistats.clarity.processor.gameevents.OnCombatLogEntry
    at skadistats.clarity.processor.runner.ExecutionModel.requireProvider(ExecutionModel.java:64)
    at skadistats.clarity.processor.runner.ExecutionModel.requireEventListener(ExecutionModel.java:77)
    at skadistats.clarity.processor.runner.ExecutionModel.requireProcessorClass(ExecutionModel.java:48)
    at skadistats.clarity.processor.runner.ExecutionModel.addProcessor(ExecutionModel.java:28)
    at skadistats.clarity.processor.runner.AbstractRunner.createExecutionModel(AbstractRunner.java:37)
    at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:79)
    at skadistats.clarity.examples.combatlog.Main.run(Main.java:150)
    at skadistats.clarity.examples.combatlog.Main.main(Main.java:156)

I removed the workspace project, built the local cloned clarity and removed the link to the sonatype repository - and finally got it works.

Maybe the Maven issues are fixable, or at least this might be helpful for somebody else.

**Comment by bwarren2** [comment]
I am getting something similar even with `mvn clean install -U`:

```
(javaparse)ben@Thoth:~/Projects/java-getting-started$ mvn clean install -U
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building replay_parser 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://oss.sonatype.org/content/repositories/snapshots/com/skadistats/clarity/2.1-SNAPSHOT/maven-metadata.xml
Downloaded: http://oss.sonatype.org/content/repositories/snapshots/com/skadistats/clarity/2.1-SNAPSHOT/maven-metadata.xml (768 B at 0.9 KB/sec)
Downloading: http://oss.sonatype.org/content/repositories/snapshots/com/skadistats/clarity-protobuf/3-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/skadistats/clarity-protobuf/3-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/com/skadistats/clarity-protobuf/3-SNAPSHOT/maven-metadata.xml (771 B at 5.3 KB/sec)
Downloaded: http://oss.sonatype.org/content/repositories/snapshots/com/skadistats/clarity-protobuf/3-SNAPSHOT/maven-metadata.xml (771 B at 3.2 KB/sec)
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ replay_parser ---
[INFO] Deleting /home/ben/Projects/java-getting-started/target
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ replay_parser ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/ben/Projects/java-getting-started/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ replay_parser ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 6 source files to /home/ben/Projects/java-getting-started/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/ben/Projects/java-getting-started/src/main/java/Parse.java:[29,52] error: cannot find symbol
[ERROR]  class CombatLog
```

Was a change pushed recently?

**Comment by howardchung** [comment]
Probably need to update your combat log import statement

**Comment by bwarren2** [comment]
Yup, I missed that revamp.  Cutting my old comment.  Thanks Howard!
