### ISSUE TITLE
Item Entity OnEntityCreated Issue

### ISSUE THREAD

**Issue by aaron868** [skadistats/clarity#66]
I've modified the CombatLog example to create a simple test program to track a hero's items. I added the Entity state change events (OnEntityCreated, Updated and Deleted). The issue I have is that I get "CDOTA_Item" from entity.getDtClass().getDtName() during OnEntityCreated. This seems to happen randomly instead of CDOTA_Item_[Items name]. Is this a bug or is there some way I can tell what type of item it is from the state table?

Thank you.

**Comment by spheenik** [comment]
Just a quick note before I'm off: I don't think it's a bug, it might be some very generic item that does not need to be implemented in a special way... Maybe it's something that only gives a simple stat gain, without any other effects?

Stat gains are "given" to a unit by modifiers. So you should be able to correlate the item appearing to a modifier added, if my theory is correct.

**Comment by aaron868** [comment]
What I'm seeing is that I do not get an Item entity in OnEntityCreated for each Item I see bought in the combat log. I thought the missing entities might be the mystery CDOTA_Item. Shouldn't I see all Items bought in OnEntityCreated()? Or have I misunderstood the protocol?

Thanks

**Comment by aaron868** [comment]
I see now what is happening. I doubt it's a bug in Clarity, it's more likely part of the Dota game protocol.Some item enitities (why some and not others is a mystery to me) are sent as CDOTA_Item and some as CDOTA_Item_[item name]. Here is a log snippet:

OnEntityCreated() -- Hero Lion bought CDOTA_Item_Tango
Combat Log -- [00:05:59.200] Lion buys item_tango
OnEntityCreated() -- Hero Lion bought unknown Item CDOTA_Item
Combat Log -- [00:06:00.333] Lion buys item_flask 

CDOTA_Item contains no information that I can see to say what it is. My only idea at this point is to correlate them with the combat log (Yuck!). If anyone knows a better way to track hero items in real time I would be grateful to hear it.

**Comment by spheenik** [comment]
Kind of like the same as with the type of neutral creep.
I will consult my sources in the inner circle about that :)

**Comment by aaron868** [comment]
Thanks. And thanks for developing Clarity. It's a great library.

**Comment by aaron868** [comment]
I figured it out and will post the answer here in case it helps someone else. My goal is capturing game state in real-time. 

The hero and item entities have a property called "m_pEntity.m_nameStringableIndex". This is a row index into a StringTable called "EntityNames". This index will return you the hero or item key from the VPK files (e.g., "npc_dota_hero_antimage" for Anit-Mage, and "item_ultimate_scepter" for Aghanim's Scepter).

The EntityNames string table is built up in pieces as the game progresses. You can get the updates using the Clarity call:

  @OnStringTableEntry("EntityNames")
  public void onStringTableEntry(Context ctx, StringTable stringTable, int rowIndex, String key, ByteString bs) {
      //Store the index and key in a local HashMap<Integer, String> 
     //OnStringTableCreated is not needed
 }

So, any time one of the OnEntity() methods is called you can lookup its index using its "m_pEntity.m_nameStringableIndex" property to get its entity name (key) from the string table. 

In my app I have a database with all the hero and item attributes and that uses the VPK file keys as the primary keys . Once I get the enity name from the string table I can lookup the hero and item attributes.

I believe the same approach will work with hero abilities but that is my next step so I haven't tested it yet.
