### ISSUE TITLE
How to get a neutral creep's name?

### ISSUE THREAD

**Issue by 1zb** [skadistats/clarity#67]
I tried property 'm_pEntity.m_nameStringableIndex' of CDOTA_BaseNPC_Creep_Neutral. But they are all the same (npc_dota_creep_neutral).

**Comment by spheenik** [comment]
Unfortunately, I have not yet figured out a way to do this.
@ykim has tackled this by looking at max health and other parameters to deduce the type of creep.
In Source 1, this was done by the model name, which is no longer present in S2. The model in S2 is a "StrongHandle" and idk how to decypher that.

If you find out, plz share!

**Comment by ykim** [comment]
There is no direct way to determine the name of a neutral creep unfortunately. Here's the methodology I came up with.

S1: Model names are fairly accurate. The only issue is that some neutrals shared the same model names, so some of the other properties of those neutrals (i.e levels and max hp) have to be used to accurately identify the neutral.

S2: Model names are no longer retrievable (unless someone figures this out). This means that all the differentiating properties of the neutrals would have to be used to determine the neutrals.

If you have any questions, feel free to go onto the dota2replay channel on IRC and hit me up.
