### ISSUE TITLE
FieldPath ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by aaron868** [skadistats/clarity#68]
I'm getting frequent ArrayIndexOutOfBoundsExceptions when trying to get the property name of fields during:

@OnEntityUpdated 
public void updateEntity(Context ctx, Entity entity, FieldPath[] fieldPaths, int pathIndex) 

It seems to happen only with item entities.

For example: a path index of 6, gets the FP object "94" from the FieldPath array but there is no FieldPath of 94 in the entity state table. Looking at the FieldPath array I see several paths which are not in the state table and also some duplicates (more than one FieldPath is "94"). Using this FP object the call to entity.getDtClass().getNameForFieldPath(fieldPath) throws an ArrayIndexOutOfBoundsException.

Not sure if I'm doing something wrong here or there is an underlying issue. My code is simply:

private String getPropertyName(Entity entity, FieldPath[] fieldPaths, int pathIndex) {
        return entity.getDtClass().getNameForFieldPath(fieldPaths[pathIndex]);
}

The values are passed directly from @OnEntityUpdated.

Thanks.

**Comment by spheenik** [comment]
The variable you named "pathIndex" is actually the count of items that 
are valid.
You may only read this much from the array.
Also: Do not save a reference to this array. It belongs to the 
EntityProcessor, and will be reused!

**Comment by spheenik** [comment]
For example: https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/lifestate/SpawnsAndDeaths.java#L66-L71

**Comment by aaron868** [comment]
I see. I mistakenly assumed it was the index showing which field had changed. 

Thank you.
