### ISSUE TITLE
6.86 protobuf update

### ISSUE THREAD

**Issue by howardchung** [skadistats/clarity#70]
https://github.com/skadistats/clarity-protobuf needs updated protobufs

**Comment by spheenik** [comment]
I looked over them yesterday, only 2 slight changes. Did you notice a problem?

**Comment by howardchung** [comment]
Looks like new combat log types and fields within CombatLogEntry.  I checked and the replay does not seem to have those types but it might be added in the future.

**Comment by howardchung** [comment]
Valve recently added even more fields to the combat log proto definition, but they also don't appear to be in replays.  If they are added to replays in the future, will clarity handle it or crash if the protos aren't updated?

It would also be nice to have it updated so that running a replay through clarity can tell us if the new combat log types are present.

Currently I'm just running them through rapier and outputting events for combat log types > 19.

**Comment by spheenik** [comment]
Yes, it's long overdue.
I will see what I can do tonight. (10 hours from now)

**Comment by spheenik** [comment]
Sorry, had some hardware probs yesterday, back on track now

**Comment by spheenik** [comment]
Just pushed a new snapshot and new protobufs.
Did not do much testing, hope it works out.
Really gotta go to bed now. 
Please close this if appropriate. gn8 :)
