### ISSUE TITLE
CombatLogEntry.getInflictorName() 

### ISSUE THREAD

**Issue by alex-jin** [skadistats/clarity#73]
getInflictorName() returns different name between DOTA_COMBATLOG_ABILITY and DOTA_COMBATLOG_MODIFIER_ADD.  I want to calculate total stun time for each ability in a match,
but I got different value from getInflictorName(). For example, getInflictorName() returns "vengefulspirit_matic_missile" in DOTA_COMBATLOG_ABILITY, but returns "modifier_stunned" in DOTA_COMBATLOG_MODIFIER_ADD even though this modifier is caused by the ability.

**Comment by spheenik** [comment]
I don't think there's a bug here, since what you describe is as is in the replay data.
It seems that the data does not provide the link between the modifier and the ability. But you should get the ability first, and the modifier add second, which should help correlate...

**Comment by alex-jin** [comment]
Thanks for your reply. So you mean there is no easy way to get total stun time for each ability?  You mean I should use "modifier add time" and "ability use time" to correlate them  and calculate total stun time for each ability ?  But stun could caused by item usage as well.  And lots of inflictorName for "modifier add" are "modifier_stunned" instead of actual ability name or item name.

**Comment by spheenik** [comment]
I did not have time today to check this, but if the data is structured the way you shown, then correlating might be your only choice. 

Or you could bypass the combatlog and use modifiers and entities directly.

**Comment by alex-jin** [comment]
Thanks.

**Comment by spheenik** [comment]
You're welcome.
