### ISSUE TITLE
Where can I find full list of properties, and is it possible to add new property?

### ISSUE THREAD

**Issue by yujiaxinlong** [skadistats/clarity#76]
HI,
sorry to bother you,
I want to make an replay analysis app that can get the duration that one team is seen by the other team, I believe it is really interesting and useful to compare the vision of two teams(especially the time that each team is seen by ward).

But I am really confused about what the "property" in replay analysis is, is it provided by valve? where can I find the list of these properties?
I studied a lot of examples I can find online and saw some usage of these properties, but I really want to know how people know where to find which property should be used when coding.

http://pastebin.com/6szfaGAE
I found this page, but it seems very old, and I cannot understand what most of the properties mean.

Another question is, is it possible to add our own property? maybe by modifying the proto files? I found these is an interface "CanEntityBeSeenByMyTeam" in dota2 workshop, but didn't find related property.

Thank you very much!!

**Comment by spheenik** [comment]
Hi,
the properties from the pastebin are entity properties. Each entity in the replay has a specific type with specific properties. For example, every hero or creep has a property "m_iHealth" containing its current health.

There is no documentation I know of regarding what properties there are. A good starting point is [clarity-analyzer](https://github.com/spheenik/clarity-analyzer) which lets you view all entities with their properties in a GUI.

Of course, you cannot add your own properties to the replay file.

Regarding computation of vision, I don't think it is encoded in the replay (but I might be wrong). 
This means this is done completely client side, and if so, you will not be able to replicate that without also having map data.

**Comment by spheenik** [comment]
Further thinking about it, maybe vision is encoded by some bitfield in the replay.

**Comment by yujiaxinlong** [comment]
Sorry for reply late, my thesis is  driving me crazy.

is bitfield the "Bitstream" in code clarity?

I am thinking maybe the vision thing can be calculated by the position of ward, hero and trees, is tree also an entity in replay?

**Comment by spheenik** [comment]
No, BitStream is used to read the replay (which is encoded as such). You do not need to use it.

There is an entity property m_iTaggedAsVisibleByTeam you might be able to use, I don't know how to interpret it, though.

Trees are not entities, the state of trees is encoded in a huge bitfield.
I don't know which bit maps to which tree though...

**Comment by yujiaxinlong** [comment]
okok, I will try this thank you so much.
and other question, I am studying the protobuf files, and found this line
 " optional bool is_visible_radiant = 11;"
in message  CMsgDOTACombatLogEntry
in dota_usermessage.proto

are all the message in proto files the all data we can get from replay?

**Comment by spheenik** [comment]
Not all the protobufs, but quite some.

 CMsgDOTACombatLogEntry can be easily retrieved. Please take a look at [the combat log example](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/combatlog/Main.java).

Clarity emits @OnCombatLogEntry for each entry found in the replay. It hands you a CombatLogEntry object with a function hasVisibleRadiant() which returns true if that value was encoded in the replay, and isVisibleRadiant() to retrieve it.

**Comment by yujiaxinlong** [comment]
thank you so much, I think that's what I need!!!

**Comment by yujiaxinlong** [comment]
Hi
I trying to the property "m_iTaggedAsVisibleByTeam" to do the vision thing, I wrote some simple code and it gives me the expect result. 

but it also shows a lot DEBUG messeage which I really cannot understand
like 
`20:38:14.853 [main] DEBUG s.c.processor.runner.ExecutionModel - require processor skadistats.clarity.processor.runner.SimpleRunner
20:38:14.857 [main] DEBUG s.c.processor.runner.ExecutionModel - require processor repvision.Main
20:38:14.882 [main] DEBUG skadistats.clarity.event.UsagePoints - provider found on ClassIndex: skadistats.clarity.processor.modifiers.Modifiers
20:38:14.887 [main] DEBUG skadistats.clarity.event.UsagePoints - provider found on ClassIndex: skadistats.clarity.processor.tempentities.TempEntities
20:38:14.890 [main] DEBUG skadistats.clarity.event.UsagePoints - provider found on ClassIndex: skadistats.clarity.processor.entities.Entities
20:38:14.896 [main] DEBUG skadistats.clarity.event.UsagePoints - provider found on ClassIndex: skadistats.clarity.processor.gameevents.GameEvents
20:38:14.898 [main] DEBUG skadistats.clarity.event.UsagePoints - provider found on ClassIndex: skadistats.clarity.processor.gameevents.CombatLog
20:38:14.899 [main] DEBUG skadistats.clarity.event.UsagePoints - provider found on ClassIndex: skadistats.clarity.processor.sendtables.DTClasses
20:38:14.900 [main] DEBUG skadistats.clarity.event.UsagePoints - provider found on ClassIndex: skadistats.clarity.processor.sendtables.S2DTClassEmitter
20:38:15.248 [main] DEBUG s.c.decoder.s2.S2UnpackerFactory - don't know how to create unpacker for ValueRemapperInputType_t, assuming int.
20:38:15.248 [main] DEBUG s.c.decoder.s2.S2UnpackerFactory - don't know how to create unpacker for ValueRemapperOutputType_t, assuming int.
20:38:15.248 [main] DEBUG s.c.decoder.s2.S2UnpackerFactory - don't know how to create unpacker for ValueRemapperHapticsType_t, assuming int.
20:38:16.478 [main] DEBUG s.c.processor.entities.Entities - entity at index 465 was not found when ordered to delete.
20:38:16.486 [main] DEBUG s.c.processor.entities.Entities - entity at index 909 was not found when ordered to delete.`

this is just part of lines.

It doesn't affect the final result,  and I read the related files in clarity, but really cannot understand why do they appears

my code is here, it's a very simple program modified from clarity-example
https://github.com/yujiaxinlong/Dota2RepParser/blob/master/src/main/java/repvision/Main.java

thanks!

**Comment by yujiaxinlong** [comment]
ok I copied my code to cover one file of clarity-examples, then run this file, these things didn't appear....
I think it's the matter of configuration of maven

**Comment by yujiaxinlong** [comment]
ok I found it, it's because I don't have logback.xml file.

I don't have enough knowledge about maven......

**Comment by spheenik** [comment]
yes, logback.xml is the file that configures the logging. :)

**Comment by yujiaxinlong** [comment]
new question .... maybe the last one, is there way to get name of team? like secret or lgd.
I tried to get it from CDOTATeam but m_szTeamname it's unassigned there...

**Comment by spheenik** [comment]
I don't know. Please try to load the replay with [clarity analyzer](https://github.com/spheenik/clarity-analyzer).

**Comment by yujiaxinlong** [comment]
haha, thank you so much!
actually the program was almost done 
[https://github.com/yujiaxinlong/Dota2RepParser](url)
 just miss the team name.... really cannot find it..

my initial purpose was to prove our Chinese dota team did really bad at vision aspect(which I really thought is true), but the result is....... our vision is ok .... or even could say good

think you again for your help!

**Comment by spheenik** [comment]
There are multiple entities CDOTATeam.
You can use 
ctx.getProcessor(Entities.class).getAllByDtName("CDOTATeam");
This will give you an iterator, which can iterate over all of them. Each has a property m_iTeamNum.

Radiant = 2
Dire = 3

m_szTeamName will contain the name.

(I found it by using clarity analyzer. Took 2 minutes!)

**Comment by spheenik** [comment]
Ah btw. if you're done, feel free to close this.

**Comment by yujiaxinlong** [comment]
actually I've tried  m_szTeamName in CDOTATeam, but it always unassigned...
I find that by directly print an entity, can get all properties of this entity 
any way, I've gotten the result I want, thank you!
