### ISSUE TITLE
Parsing Crash

### ISSUE THREAD

**Issue by KenBeanNet** [skadistats/clarity#77]
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000d72850, pid=15664, tid=12264
> #
> # JRE version: Java(TM) SE Runtime Environment (8.0_74-b02) (build 1.8.0_74-b02)
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.74-b02 mixed mode windows-amd64 compressed oops)
> # Problematic frame:
> # v  ~StubRoutines::jbyte_disjoint_arraycopy
> #
> # Core dump written. Default location: XXX/hs_err_pid15664.mdmp
> #
> # If you would like to submit a bug report, please visit:
> #   http://bugreport.java.com/bugreport/crash.jsp
> #
> 
> ---------------  T H R E A D  ---------------
> 
> Current thread (0x0000000031fa5800):  JavaThread "pool-3-thread-19" [_thread_in_Java, id=12264, stack(0x0000000034c50000,0x0000000034d50000)]
> 
> siginfo: ExceptionCode=0xc0000005, reading address 0x00000007c05a0000
> 
> Registers:
> RAX=0x00000007b83aab9f, RBX=0x00000007bc000af8, RCX=0xfffffffffc3aa2bb, RDX=0xe00000000103ea91
> RSP=0x0000000034d4e5b0, RBP=0x0000000034d4e5b0, RSI=0x00000006c55aa2c0, RDI=0x00000007b83aab94
> R8 =0xfffffffffc3aa2bb, R9 =0x0000000000000001, R10=0x00000007bc0008c0, R11=0x0000000000000014
> R12=0x0000000000000000, R13=0x0000000034d4e628, R14=0x0000000035c5cf98, R15=0x0000000031fa5800
> RIP=0x0000000000d72850, EFLAGS=0x0000000000010292
> 
> Top of Stack: (sp=0x0000000034d4e5b0)
> 0x0000000034d4e5b0:   00000000e1d515d0 000000000156a023
> 0x0000000034d4e5c0:   00000006c9200000 0000000000000002
> 0x0000000034d4e5d0:   00000006928a5740 0000000034d4e5d8
> 0x0000000034d4e5e0:   00000000339b4979 0000000034d4e638
> 0x0000000034d4e5f0:   0000000033a050f0 0000000035af97f0
> 0x0000000034d4e600:   00000000339b49b0 0000000000000000
> 0x0000000034d4e610:   0000000034d4e680 0000000000d27ced
> 0x0000000034d4e620:   0000000000d27ced 00000000e1d515d0
> 0x0000000034d4e630:   00000006c9200000 00000007bc000af8
> 0x0000000034d4e640:   0000000034d4e640 00000000339b534b
> 0x0000000034d4e650:   0000000034d4e6e8 0000000033a050f0
> 0x0000000034d4e660:   0000000035c5cf98 00000000339b54a8
> 0x0000000034d4e670:   0000000034d4e628 0000000034d4e6f0
> 0x0000000034d4e680:   00000000f780012a 0000000001afddd8
> 0x0000000034d4e690:   0000000000000000 0000000000000000
> 0x0000000034d4e6a0:   0000000000000000 00000007bc000c80 
> 
> Instructions: (pc=0x0000000000d72850)
> 0x0000000000d72830:   06 8a 47 08 88 46 08 49 8b f9 49 8b f2 48 33 c0
> 0x0000000000d72840:   c9 c3 66 66 0f 1f 84 00 00 00 00 00 66 66 66 90
> 0x0000000000d72850:   c5 fe 6f 44 d7 c8 c5 fe 7f 44 d6 c8 c5 fe 6f 4c
> 0x0000000000d72860:   d7 e8 c5 fe 7f 4c d6 e8 48 83 c2 08 7e e2 48 83 
> 
> 
> Register to memory mapping:
> 
> RAX=0x00000007b83aab9f is pointing into object: 0x00000007b83aab98
> [I 
>  - klass: {type array int}
>  - length: 6
> RBX=0x00000007bc000af8 is an oop
> skadistats.clarity.decoder.bitstream.UnsafeBitStream64 
>  - klass: 'skadistats/clarity/decoder/bitstream/UnsafeBitStream64'
> RCX=0xfffffffffc3aa2bb is an unknown value
> RDX=0xe00000000103ea91 is an unknown value
> RSP=0x0000000034d4e5b0 is pointing into the stack for thread: 0x0000000031fa5800
> RBP=0x0000000034d4e5b0 is pointing into the stack for thread: 0x0000000031fa5800
> RSI=0x00000006c55aa2c0 is an unknown value
> RDI=0x00000007b83aab94 is pointing into object: 0x00000007b83aab80
> skadistats.clarity.model.FieldPath 
>  - klass: 'skadistats/clarity/model/FieldPath'
> R8 =0xfffffffffc3aa2bb is an unknown value
> R9 =0x0000000000000001 is an unknown value
> R10=0x00000007bc0008c0 is an oop
> [B 
>  - klass: {type array byte}
>  - length: 123
> R11=0x0000000000000014 is an unknown value
> R12=0x0000000000000000 is an unknown value
> R13=0x0000000034d4e628 is pointing into the stack for thread: 0x0000000031fa5800
> R14=0x0000000035c5cf98 is pointing into metadata
> R15=0x0000000031fa5800 is a thread
> 
> 
> Stack: [0x0000000034c50000,0x0000000034d50000],  sp=0x0000000034d4e5b0,  free space=1017k
> Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
> C  0x0000000000d72850
> `

There is more, just not sure its needed.  Could be a corrupted download, but should it really crash the application fully?

**Comment by howardchung** [comment]
Clarity won't handle corrupted replays.  You'll need to catch exceptions in your applications and handle appropriately (retry, etc.)

**Comment by KenBeanNet** [comment]
I have the entire parse inside a catch block.  Until today, I couldnt even find the error until I put on verbose JVM logging.

**Comment by spheenik** [comment]
Good Job on that catch!

As suspected, it's trying to access memory it doesn't own in the unsafe bitstream code...

I suspect it is caused by corrupt data, and clarity then trying to read out of bounds...

I'll see whether range checks could improve the situation.

**Comment by KenBeanNet** [comment]
Correct.  The download was most likely corrupted, but I figure it shouldn't crash the application but just throw an exception.  If you can get it to throw, I am totally fine with handling the issue myself as per HowardChung.  I have plenty more crash logs, all pretty much the same reason though.  If you need them hit me on Steam.

**Comment by spheenik** [comment]
I pushed a new snapshot just now.
If I'm right, it'll throw an IOException before trying to read from the Bitstream containing corrupt data.
Happy testing!

**Comment by KenBeanNet** [comment]
Excellent, I will have an update within a few hours (Or def by morning).

**Comment by spheenik** [comment]
Going horizontal in 10 minutes, but will look tomorrow morning :)

**Comment by spheenik** [comment]
I pushed a new update, since I had a replay which had a valid zero length embedded packet.
Any updates @KenBeanNet?

**Comment by KenBeanNet** [comment]
You defiantly fixed some bugs.  I believe 4 of about 60 have crashed. By now normally ALL would of crashed. I have to find out which server has them.  Ill post bug report.

**Comment by KenBeanNet** [comment]
Looks like the 4 that crashed were due to " There is insufficient memory for the Java Runtime Environment to continue.".  Nothing to do with your release.  So looks good.  Im sure I will find another soon.

**Comment by spheenik** [comment]
Don't you dare!!1! :facepunch:

**Comment by spheenik** [comment]
btw @howardchung how many corrupt replays do you get and how do you fallback?

**Comment by KenBeanNet** [comment]
Our issue is the direct download from the 5-6 China clusters.  They average about 10min per download where every other location is 2-3min per.  I think it just leads to a higher percentage of 1 bad packet in such long downloads * amount.  It does not happen often for us.  Maybe 1 and every 25,000?

**Comment by spheenik** [comment]
Sometimes a bit flips even before it is stored by Valve... So this is probably really normal to occur every 25000.

**Comment by KenBeanNet** [comment]
We often are requesting before Valve has the replay available.  We just throw it away for 1 minute and then retry until successful.  If its not available after 30 days, good bye. (one China cluster DNS record is down, I think its due to that cluster not have enough bandwidth to support, so they dont allow those replays).  

As long as the Java process doesnt crash, I am more than happy to handle exceptions. :)

**Comment by howardchung** [comment]
You can see yasp.co/status for live status.  Currently there looks to be about 13k in delayed state, which means we haven't been able to parse the replay.  We clean them up daily.

I've encountered the same slow China replay blocking the queue problem.  I set a timeout of 180 seconds per parse to get around it (may be the cause of the high number of delayed jobs)

Basically we retry on doubling interval since the replay may not be immediately available and give up after a day.

**Comment by spheenik** [comment]
Ok, but do you encounter hard crashes of the JVM?

**Comment by howardchung** [comment]
I think I've seen a few.  However since all the parse workers are ephemeral (preemptible instances) we generally just eat the crashes.

**Comment by spheenik** [comment]
I see.

So, if you guys get hold of hard crash logs using clarity, don't hesitate to post. It just should not do it.

@KenBeanNet, your choice to leave this open or close.

**Comment by KenBeanNet** [comment]
Pretty sure the issue has been resolved.  I think it can be closed.
