### ISSUE TITLE
Missing GameEvents for some replays 

### ISSUE THREAD

**Issue by fonsleenaars** [skadistats/clarity#78]
I was wondering if it's possible that in some replays the `@OnGameEvent` will not work for all game events.

I used the 'gameevents' example you provided and used `@OnGameEvent("player_disconnect")` to annotate a function that should create a list of all disconnects of a specific player, and then use the last instance as "the moment a player clicked close on the scoreboard". 

This works perfectly for 80-90% of the replays I've tried so far (ran about 200) but for that 10-20% it won't return anything. 

Those replays only return `dota_chase_hero` game events oddly enough.

I checked the replays in Dota itself, and seems to run fine and the disconnect messages all appear on screen as you would expect.

I've been digging into the code and seeing if I could get to even lower level messages myself but I figured it might be easier to ask you first before I got lost in the Proto classes. Huge thanks for the clarity project btw.

Example replay that has this issue: [https://www.dropbox.com/s/7ffmgcdjh573nfr/2110208346.dem?dl=0](https://www.dropbox.com/s/7ffmgcdjh573nfr/2110208346.dem?dl=0)

**Comment by fonsleenaars** [comment]
After checking the output of a function annotated with `OnMessage` and simply logging the `GeneratedMessage` I believe that one of the following outputting messages should correspond to the missing game events:

```
eventid: 9
keys {
  type: 4
  val_short: 3
}
keys {
  type: 4
  val_short: 2
}
keys {
  type: 1
  val_string: "hoi"
}
keys {
  type: 1
  val_string: "[U:1:96422779]"
}

type: CHAT_MESSAGE_DISCONNECT
value: 0
playerid_1: 6
playerid_2: -1
```

Is that helpful at all?

**Comment by spheenik** [comment]
Will look into it tonight

**Comment by spheenik** [comment]
Ok, I had a look.
The raw dump you provided is most certainly from a "player_disconnect" event.
I fail to see where clarity would swallow those... 
Would you be able to supply a replay were it fails? Then I could have a deeper look...

**Comment by fonsleenaars** [comment]
I attached a replay at the bottom of my first comment, for convenience: [ https://www.dropbox.com/s/7ffmgcdjh573nfr/2110208346.dem?dl=0]( https://www.dropbox.com/s/7ffmgcdjh573nfr/2110208346.dem?dl=0)

**Comment by spheenik** [comment]
TL/DR; sry :) 
Will have a look.

**Comment by spheenik** [comment]
Ok, I found some replays that have the same behaviour. 
They contain the correct GameEventDescriptor:

`GameEventDescriptor [eventId=9, name='player_disconnect']`

but there is not a single game event in them with that id.
It's the same with your replay. It just does not seem to be there.

**Comment by fonsleenaars** [comment]
Hm, I see. Is there still an easy way to find those 'disconnect' moments for those replays?

As in, right now I use:

```
private static final String EVENT_DISCONNECT = "player_disconnect";
private static final String PROP_NETWORK_ID = "networkid";

@OnGameEvent
public void onGameEvent(Context ctx, GameEvent event) {
    if (event.getName().equals(EVENT_DISCONNECT) && event.getProperty(PROP_NETWORK_ID).equals(player)) {
        disconnectTicks.add(ctx.getTick());
    }
}
```

Should I annotate `@OnGameEventDescriptor` and check if the name equals `player_disconnect` ?

**Comment by spheenik** [comment]
Code used:
```java
package skadistats.clarity.examples.gameevent;

import skadistats.clarity.model.GameEventDescriptor;
import skadistats.clarity.processor.gameevents.OnGameEventDescriptor;
import skadistats.clarity.processor.reader.OnMessage;
import skadistats.clarity.processor.runner.Context;
import skadistats.clarity.processor.runner.SimpleRunner;
import skadistats.clarity.source.MappedFileSource;
import skadistats.clarity.wire.common.proto.NetworkBaseTypes;

import java.io.File;

public class Main {

    boolean descriptor;
    int c;

    @OnGameEventDescriptor()
    public void onGameEvent(Context ctx, GameEventDescriptor eventDescriptor) {
        if (eventDescriptor.getEventId() == 9) {
            descriptor = true;
        }
    }

    @OnMessage(NetworkBaseTypes.CSVCMsg_GameEvent.class)
    public void onGameEvent(Context ctx, NetworkBaseTypes.CSVCMsg_GameEvent event) {
        if (event.getEventid() == 9) {
            c++;
        }
    }

    void runAll(String[] args) throws Exception {
        File folder = new File("d:/replays_s2");
        File[] listOfFiles = folder.listFiles();
        for (int i = 0; i < listOfFiles.length; i++) {
            if (listOfFiles[i].isFile() && listOfFiles[i].getName().endsWith(".dem")) {
                c = 0; descriptor = false;
                new SimpleRunner(new MappedFileSource(listOfFiles[i].getAbsolutePath())).runWith(this);
                System.out.format("%20s: %s %d\n", listOfFiles[i], descriptor, c);
            }
        }
    }

    public static void main(String[] args) throws Exception {
        new Main().runAll(args);
    }

}

**Comment by fonsleenaars** [comment]
Cheers, let me try that quickly

**Comment by spheenik** [comment]
Most of the replays are from the early Source 2 days, so I would understand if only those had the problem, but there is one (1582611189) that has some. All of them have the descriptor.
It's strange...

Output:

d:\replays_s2\1560289528.dem: true 0
d:\replays_s2\1560294294.dem: true 0
d:\replays_s2\1560315800.dem: true 0
d:\replays_s2\1582611189.dem: true 9
d:\replays_s2\1605340040.dem: true 0
d:\replays_s2\1648457986.dem: true 0
d:\replays_s2\1675488753.dem: true 0
...

**Comment by fonsleenaars** [comment]
All matches within last 60 days:

E:\replays\2110208346.dem: true 0
E:\replays\2110292912.dem: true 11
E:\replays\2110392539.dem: true 10
E:\replays\2110526400.dem: true 0
E:\replays\2111799592.dem: true 10
E:\replays\2112603921.dem: true 0
E:\replays\2112703738.dem: true 10
E:\replays\2112777401.dem: true 10
E:\replays\2112884843.dem: true 0
E:\replays\2113059336.dem: true 8
E:\replays\2113218990.dem: true 10
E:\replays\2113371407.dem: true 0
E:\replays\2113482038.dem: true 0
E:\replays\2113553787.dem: true 0
E:\replays\2113663412.dem: true 10
E:\replays\2116698049.dem: true 10
E:\replays\2116740811.dem: true 10
E:\replays\2116800729.dem: true 10
E:\replays\2116845639.dem: true 10
E:\replays\2116880905.dem: true 10
E:\replays\2116936332.dem: true 10
E:\replays\2117006902.dem: true 10
E:\replays\2117068996.dem: true 10
E:\replays\2118490115.dem: true 12
E:\replays\2118600851.dem: true 9
E:\replays\2118766456.dem: true 10
E:\replays\2118886086.dem: true 10
E:\replays\2119476788.dem: true 10
E:\replays\2119528524.dem: true 11
E:\replays\2119575156.dem: true 10
E:\replays\2119626973.dem: true 10
E:\replays\2119671883.dem: true 9
E:\replays\2119754373.dem: true 11
E:\replays\2119858748.dem: true 10
E:\replays\2119929955.dem: true 10
E:\replays\2120027206.dem: true 12
E:\replays\2120884348.dem: true 0
E:\replays\2121134221.dem: true 0
E:\replays\2121214019.dem: true 10
E:\replays\2121298235.dem: true 0
E:\replays\2121380366.dem: true 0
E:\replays\2121814868.dem: true 10
E:\replays\2121861673.dem: true 10
E:\replays\2121900475.dem: true 10
E:\replays\2121953664.dem: true 10
E:\replays\2121997430.dem: true 10
E:\replays\2122064981.dem: true 10
E:\replays\2122928222.dem: true 10
E:\replays\2124832852.dem: true 10
E:\replays\2124890627.dem: true 10
E:\replays\2124908292.dem: true 11
E:\replays\2124991641.dem: true 10
E:\replays\2124995643.dem: true 0
E:\replays\2125106089.dem: true 10
E:\replays\2125237767.dem: true 8
E:\replays\2126341271.dem: true 10
E:\replays\2126404987.dem: true 10
E:\replays\2126485551.dem: true 10
E:\replays\2126545127.dem: true 10
E:\replays\2126614131.dem: true 10
E:\replays\2127296547.dem: true 0
E:\replays\2127439404.dem: true 9
E:\replays\2127544064.dem: true 10
E:\replays\2127649914.dem: true 9
E:\replays\2127797914.dem: true 0
E:\replays\2127887241.dem: true 10
E:\replays\2128007131.dem: true 0
E:\replays\2129341403.dem: true 10
E:\replays\2129365088.dem: true 10
E:\replays\2129479566.dem: true 0
E:\replays\2129579346.dem: true 10
E:\replays\2129719702.dem: true 11
E:\replays\2131080930.dem: true 11
E:\replays\2131116272.dem: true 10
E:\replays\2131168688.dem: true 10
E:\replays\2131223769.dem: true 0
E:\replays\2132066416.dem: true 0
E:\replays\2132184366.dem: true 10
E:\replays\2132317024.dem: true 0
E:\replays\2132399905.dem: true 9
E:\replays\2132574225.dem: true 0
E:\replays\2132691826.dem: true 0
E:\replays\2135204286.dem: true 0
E:\replays\2135353568.dem: true 10
E:\replays\2135456476.dem: true 10
E:\replays\2135589569.dem: true 9
E:\replays\2135692881.dem: true 0
E:\replays\2135774510.dem: true 10
E:\replays\2137187643.dem: true 10
E:\replays\2137286936.dem: true 11
E:\replays\2137403902.dem: true 10
E:\replays\2137528262.dem: true 10
E:\replays\2137639557.dem: true 0
E:\replays\2137736846.dem: true 0
E:\replays\2137828521.dem: true 10
E:\replays\2137898388.dem: true 13
E:\replays\2141674422.dem: true 10
E:\replays\2141767659.dem: true 10
E:\replays\2141924627.dem: true 11
E:\replays\2142041820.dem: true 11
E:\replays\2142175115.dem: true 9
E:\replays\2142319030.dem: true 0
E:\replays\2151307429.dem: true 9
E:\replays\2151459778.dem: true 10
E:\replays\2151585182.dem: true 10
E:\replays\2151695265.dem: true 0
E:\replays\2151854762.dem: true 11
E:\replays\2151991298.dem: true 0
E:\replays\2154027624.dem: true 11
E:\replays\2154155884.dem: true 10
E:\replays\2154328882.dem: true 0
E:\replays\2154454803.dem: true 0
E:\replays\2156025876.dem: true 0
E:\replays\2156171442.dem: true 10
E:\replays\2156310030.dem: true 9
E:\replays\2156476897.dem: true 0
E:\replays\2156658291.dem: true 10
E:\replays\2160142051.dem: true 11
E:\replays\2160230956.dem: true 10
E:\replays\2160354088.dem: true 10
E:\replays\2160465291.dem: true 6
E:\replays\2160569933.dem: true 9
E:\replays\2160691077.dem: true 0
E:\replays\2160796859.dem: true 10
E:\replays\2160912659.dem: true 0
E:\replays\2162784683.dem: true 9
E:\replays\2162942870.dem: true 11
E:\replays\2163046261.dem: true 10
E:\replays\2163198350.dem: true 11
E:\replays\2209157057.dem: true 10
E:\replays\2209223573.dem: true 0
E:\replays\2209329891.dem: true 10
E:\replays\2209417433.dem: true 11
E:\replays\2209490044.dem: true 10
E:\replays\2209604170.dem: true 0

**Comment by fonsleenaars** [comment]
I guess it's better to listen to `CHAT_MESSAGE_DISCONNECT` which does seem to appear, even in the absence of the `player_disconnect` event.

**Comment by spheenik** [comment]
Really strange... 
I guess it's time for a workaround.
I can image some stuff:

a) you say, the text message is there, so you could look for that one.
b) one could try to find the connection state of a player within the entities. (I guess it's in there somewhere, since they have to show the disconnected icon). You could then try to replicate the SpawnsAndDeaths provider to efficiently check for changes to that property.

Which way is it?

Just before posting, you went a) :+1: 

I'll leave b) here since it would be a nice exercise...

**Comment by fonsleenaars** [comment]
Thanks for your time, hugely appreciated, should I close this or leave it open for b) ?

**Comment by spheenik** [comment]
You're welcome! HF!
