### ISSUE TITLE
Retrieving hero selection on tick returning -1 for whole match on new replays

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#79]
I've been running into an issue with several new matches I've downloaded off of the Dota 2 client. My program analyzes the replay by tick, and for one or more players, their "m_nPossibleHeroSelection" is returning "-1" for the entire match. Older replays run just fine and hero selections are correct, but the new ones I've tried have had this problem. The match IDs that I've tried so far are: 2227501950, 2226961478, and 2226839463. I also checked using the visual analyzer and the problem is consistent there too. Any ideas why this is happening?

**Comment by spheenik** [comment]
No idea, unfortunately.
But if it's named "possible hero selection", this sounds like the server also does not know for sure?
What do you want to know? How long the players hero has been selected?

**Comment by TodorovicF** [comment]
I'm looking to find out each player's final hero selection (so even if a switch happens in-game). But I just figured out that I'm able to do that using the CDOTA_Unit_Hero_X classes' m_iPlayerID instead. The problem with that is if I pick a random tick just to grab that info, I sometimes get duplicates for something like CDOTA_Unit_Hero_PhantomLancer, which are all of it's illusions. I couldn't find any property that can tell me if one is an illusion or not though. And thanks a lot for the great support on your library!

**Comment by spheenik** [comment]
There are CDOTAPLAYER entities for each player. They have m_iPlayerID 
(0..9) to assign them to a slot.
Each of them has m_hAssignedHero which should have what you want.

**Comment by TodorovicF** [comment]
Any way to tell if it's an illusion or not? I'm seeing duplicates of the heroes if they have illusions spawned. Thanks!

**Comment by spheenik** [comment]
m_hAssignedHero should not change and always point to the non illusion hero.

That said, you can find if a hero entity is an illusion by looking at m_hReplicatingOtherHeroModel. If it is 16777215 it means it's the real one, else it's the handle of the entity it's an illusion of.

**Comment by TodorovicF** [comment]
Perfect, thank you so much!
