### ISSUE TITLE
java.io.IOException: given stream does not seem to contain a valid replay

### ISSUE THREAD

**Issue by Jefftopia** [skadistats/clarity#80]
I'm getting a replay via node-steam and node-dota2 api. 

```
var url = "http://replay" + match.cluster + ".valve.net/570/" + match.match_id + "_" + match.replay_salt + ".dem.bz2";

request(url).pipe(fs.createWriteStream(match.match_id + '.dem.bz2'));
```

This seems to be the correct way to read and write a file in node via the API, yet when I run the clarity matchend example via 

```
java -jar target/matchend.one-jar.jar ../dota/2213242172.dem.bz2
```

The title error is thrown: 

```
java.io.IOException: given stream does not seem to contain a valid replay
```

**Comment by howardchung** [comment]
You need to decompress the replay (bz2)

**Comment by Jefftopia** [comment]
@howardchung Thanks, that did the trick, thank you. 

Can you recommend a node library for decompressing? There's so many O_o

**Comment by howardchung** [comment]
We used to use a node library but found that it's much faster to use the bzip utilities already built into Ubuntu.

**Comment by Jefftopia** [comment]
Perfect, I used that just now, thanks.
