### ISSUE TITLE
New Crash 3-23-2016

### ISSUE THREAD

**Issue by KenBeanNet** [skadistats/clarity#81]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006562ea00, pid=6260, tid=8484
#
# JRE version: Java(TM) SE Runtime Environment (8.0_72-b15) (build 1.8.0_72-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.72-b15 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0xaea00]
#
# Core dump written. Default location: C:\XXX\hs_err_pid6260.mdmp
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread (0x000000000196d800):  ConcurrentGCThread [stack: 0x00000000297d0000,0x00000000298d0000] [id=8484]

siginfo: ExceptionCode=0xc0000005, reading address 0x0000000000000070

Registers:
RAX=0x0000000001a15c60, RBX=0x000000061f571738, RCX=0x000000061f571738, RDX=0x0000000000000068
RSP=0x00000000298cf5b8, RBP=0x0000000001a0ea60, RSI=0x00000000308ea250, RDI=0x0000000001a1e090
R8 =0x00000000308ea250, R9 =0x0000000001a1e090, R10=0x0000000001943b30, R11=0x0000000000000000
R12=0x00000007c015b568, R13=0x000000069aa85130, R14=0x00000007c015b308, R15=0x0000000000155555
RIP=0x000000006562ea00, EFLAGS=0x0000000000010202

Top of Stack: (sp=0x00000000298cf5b8)
0x00000000298cf5b8:   0000000065686e4a 000000069aa85150
0x00000000298cf5c8:   0000000000000003 0000000001a0ea60
0x00000000298cf5d8:   00000000656829cf 0000000001a15c60
0x00000000298cf5e8:   0000000030f63f70 000000069aa85150
0x00000000298cf5f8:   0000000000000006 0000000001a0ea60
0x00000000298cf608:   0000000065686eec 000000061f571738
0x00000000298cf618:   00000000308ea250 0000000001a1e090
0x00000000298cf628:   00000000298cf830 0000000001a15c60
0x00000000298cf638:   0000000000000000 0000000001a25f20
0x00000000298cf648:   0000000065686fdc 000000061f571738
0x00000000298cf658:   00000000298cf830 000000069aa85150
0x00000000298cf668:   000000000000000c 0000000001a15c60
0x00000000298cf678:   00000000298cf800 00000007c015b560
0x00000000298cf688:   000000006568a085 000000069aa85144
0x00000000298cf698:   0000000000000000 00000008bd404366
0x00000000298cf6a8:   000000000c24fa70 000000069aa85130 

Instructions: (pc=0x000000006562ea00)
0x000000006562e9e0:   7c a5 1d 00 48 8b 9c 24 d0 00 00 00 48 81 c4 c0
0x000000006562e9f0:   00 00 00 5d c3 cc cc cc cc cc cc cc cc cc cc cc
0x000000006562ea00:   44 8b 42 08 4c 8b ca 45 85 c0 7e 0e 41 f6 c0 01
0x000000006562ea10:   75 57 41 c1 f8 03 41 8b c0 c3 79 4d 80 3d 9e 28 

Register to memory mapping:

RAX=0x0000000001a15c60 is an unknown value
RBX=0x000000061f571738 is pointing into object: 0x000000061f571728
java.util.Collections$UnmodifiableRandomAccessList 
 - klass: 'java/util/Collections$UnmodifiableRandomAccessList'
RCX=0x000000061f571738 is pointing into object: 0x000000061f571728
java.util.Collections$UnmodifiableRandomAccessList 
 - klass: 'java/util/Collections$UnmodifiableRandomAccessList'
RDX=0x0000000000000068 is an unknown value
RSP=0x00000000298cf5b8 is an unknown value
RBP=0x0000000001a0ea60 is an unknown value
RSI=0x00000000308ea250 is an unknown value
RDI=0x0000000001a1e090 is an unknown value
R8 =0x00000000308ea250 is an unknown value
R9 =0x0000000001a1e090 is an unknown value
R10=0x0000000001943b30 is an unknown value
R11=0x0000000000000000 is an unknown value
R12=0x00000007c015b568 is pointing into metadata
R13=0x000000069aa85130 is an oop
skadistats.clarity.processor.runner.ExecutionModel 
 - klass: 'skadistats/clarity/processor/runner/ExecutionModel'
R14=0x00000007c015b308 is pointing into metadata
R15=0x0000000000155555 is an unknown value

Stack: [0x00000000297d0000,0x00000000298d0000],  sp=0x00000000298cf5b8,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0xaea00]

**Comment by ykim** [comment]
Is there a context to it? It'd be helpful to have the replay to debug.

**Comment by KenBeanNet** [comment]
Sorry, no way for me to get which replay I was doing currently.

**Comment by ykim** [comment]
@KenBeanNet: Can you re-open this issue when you have a context than? I don't think this is an easy thing to fix when the bug report doesn't say much.

**Comment by KenBeanNet** [comment]
@ykim Ill wait for spheenik to investigate.  Ill speak with him on Steam, but leave it open until we discuss.

**Comment by ykim** [comment]
Alright, that's fair. Is this possibly related to the previous issue you posted about?

**Comment by spheenik** [comment]
Most certainly same issue. Cannot fix till end of next week, since I am on vacation.

**Comment by KenBeanNet** [comment]
Are you done with your margaritas yet? :)

**Comment by spheenik** [comment]
Back home on Thursday. Cheers!

**Comment by spheenik** [comment]
I have no idea where to look to fix this one. 
Is this all info you got?

**Comment by KenBeanNet** [comment]
I can send you the full dump but its very large.  How do you want me to get it to you?

**Comment by spheenik** [comment]
How big?

**Comment by KenBeanNet** [comment]
1-2MB, Bigger than I can do on like Pastebin.

**Comment by spheenik** [comment]
zip, send to clarity@martin.schrodt.org

**Comment by KenBeanNet** [comment]
Sent.

**Comment by spheenik** [comment]
Got it, trying to make sense of it

**Comment by spheenik** [comment]
Ok, I added checks before accessing memory via the java.misc.Unsafe BitSteam implementations.
It should now crash with RuntimeExceptions instead of core dumps.
