### ISSUE TITLE
Tier 4 tower names in the CombatLog

### ISSUE THREAD

**Issue by jacquesh** [skadistats/clarity#83]
I know this was brought up in way back in #15, but things seem to have changed a bit since then.
I'm trying to track tower deaths and I'm checking TeamBuildingKill in the combat log to do that (because Death apparently doesn't have entries for every tower kill...namely it was missing a tier 4 and an ancient death =/). The result of getTargetName() for other towers is what you would expect:
- dota_goodguys_tower1_top
- dota_goodguys_tower1_mid
- dota_badguys_tower1_bot
- etc

But for tier 4 I just get: "dota_goodguys_tower4"
However if I check the string tables in onEntityDeleted, the string table contains both:
- dota_goodguys_tower4_bot
- dota_goodguys_tower4_top

So surely the data is there and should show up in the combat log? I tried checking in-game but it just says "Tower" which is utterly unhelpful :(

**Comment by spheenik** [comment]
The combat log entry only contains an index into the CombatLogNames-StringTable. All clarity does is look up the string for the index given in the combat log message. 
So I suspect the combat log messages contain the same index for both towers, and the indices for the mentioned correct names are never used.

I suspect this must simply be a bug on Valve's side.

Thad said, tracking the tower entities health state should let you distinguish between them.

**Comment by jacquesh** [comment]
Oh ok, thats unfortunate if its a bug on Valve's side. Is there any way of confirming that though?
In the meantime I just kept the entities for each tier 4 tower as they spawned and checked all the health states as you suggest, which worked perfectly.

**Comment by spheenik** [comment]
I wrote some code to check this a while ago (a while meaning still Source 1). So they made sure to port the bug over...
