### ISSUE TITLE
Problems adding Clarity to my Project

### ISSUE THREAD

**Issue by peemoRoyal** [skadistats/clarity#84]
Hi!

I know this might not be the right place to ask newbie questions like that but i am really getting desperate:
 
I just want to make an own project using clarity. But i fail to add it correctly. I already created a clarity snapshot .jar with maven and i added the dependency and repository to my project's pom file as well as the .jar. Then I did mvn clean.
I used the example code (AllChatProcessor) and imported all the clarity classes from the .jar but now the S2UserMessages are still missing.
Then i added the clartiy-protobuf library as .jar. Now the google Protobuf library is missing.
(Error:(13, 26) java: cannot access com.google.protobuf.MessageOrBuilder
  class file for com.google.protobuf.MessageOrBuilder not found)
I just feel like I am doing something essentially wrong, and it is a huge newbie mistake. And it could be fixed in like 3 minutes if you know what you are doing.
I am trying to get that running for 3 hours already and at this point i just don#t know what to do anymore.
It would be so great if you could help me out here!

Kind regards and thanks for your time.
Peter

**Comment by spheenik** [comment]
Seems your maven installation is working. Maven keeps downloaded dependencies in a local repository. You do not need to create your own.

I'd 

Clone clarity-examples

Do mvn -P matchend package in the root, this will download all dependencies by itself.

This should give you matchend.one-jar.jar in target folder, which can be run with Java -jar target/matchend.one-jar.jar replay.dem

Do you use an IDE?

**Comment by peemoRoyal** [comment]
Hi!

Yes this is working out. I receive the mathend.one-jar.jar. 
I am using IntelliJ IDE. 
If i want to use the whole clarity package, what do i have to do to install it to my project?
I tried copying it into the lib folder and update mvn but that doesnt quite work. An mvn install does compile but i still cannot import the skadistat package...
I wanna build an parser which parses the .dem files as complete as possible (its for a University Project).

Thanks for your help so far I reeaaally appreciate it!!
Peter

**Comment by peemoRoyal** [comment]
I added it, the pom seems to be fine too, but it look like it doesnt install al dependencies clarity needs.
For example the S2UserMessages are not found, and i also get a runtime error:
Error:(3, 17) java: package org.slf4j does not exist
That a Logger and Logger Factory are missing. Am i still fucking something up?

**Comment by spheenik** [comment]
I use IntelliJ myself, and it *just works*

- clone clarity-examples
- create new project from existing sources
- import from maven metamodel
- choose one of the Main.java examples, run it with a path to a replay as a parameter
