### ISSUE TITLE
Inventory slot showing up incorrectly empty for some time

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#85]
I'm having a strange problem where a player's inventory slot (stash in this case) all of a sudden shows up as empty at m_hItems.0006 and m_hItems.0007 for the Phantom Lancer in replay 2257589567. The stash between ticks ~59120 and ~59777 is giving me 16777215, and then goes back to normal. The strange thing is when I checked with the Clarity Analyzer and watching the replay in the Dota 2 client, those two slots still have items in them at those ticks.

This is basically what I do:
`Entity entity = ctx.getProcessor(Entites.class).getByDtName("CDOTA_Unit_Hero_PhantomLancer");`

Then I cycle through the backpack and stash, so at those two locations it would be:
```
int item1 = entity.getProperty("m_hItems.0006");
int item2 = entity.getProperty("m_hItems.0007");
```

item1 and item2 are both getting 16777215 when they should be getting 8192802 and 8258468 respectively. How is the analyzer getting the correct information? Thanks!

**Comment by spheenik** [comment]
Hmmm,
the analyzer is just showing the entity data, nothing more, nothing less.
So if you see it in the analyzer, it's there.

So something must be wrong with your code.
It could be that
`Entity entity = ctx.getProcessor(Entites.class).getByDtName("CDOTA_Unit_Hero_PhantomLancer");`
returns the first entity with that DtName, which, in the case of PL, could well be an illusion?

So maybe the illusion spawns before the stash is filled with new items? Or illusions never have a stash items?

**Comment by TodorovicF** [comment]
What I'm actually doing is grabbing the first instances of CDOTA_Unit_Hero_[name], and storing their Entity indexes. So the first Phantom Lancer that shows up in the game will always be the original, and then I get the Hero's info by index for every other tick. Sorry I didn't clarify that. 

Though I am assuming that as long as an Entity is "alive", it's Entity index will never change, otherwise when it is Deleted, the index can be recycled. So as long as the first CDOTA_Unit_Hero_PhantomLancer exists (which it should for the entirety of the game), it's index should never change, right?

**Comment by spheenik** [comment]
Yes, the index of the real one will never change. I just checked, the illusions have no inventory anyway.
Still, the problem must be somewhere on your side:

```java
import skadistats.clarity.model.Entity;
import skadistats.clarity.model.FieldPath;
import skadistats.clarity.processor.entities.OnEntityUpdated;
import skadistats.clarity.processor.entities.UsesEntities;
import skadistats.clarity.processor.runner.Context;
import skadistats.clarity.processor.runner.SimpleRunner;
import skadistats.clarity.source.MappedFileSource;

@UsesEntities
public class Main {

    @OnEntityUpdated
    public void onUpdated(Context ctx, Entity e, FieldPath[] updatedPaths, int updateCount) {
        if (!e.getDtClass().getDtName().equals("CDOTA_Unit_Hero_PhantomLancer")) return;
        if (e.<Integer>getProperty("m_hReplicatingOtherHeroModel") != 16777215) return;
        for (int i = 0; i < updateCount; i++) {
            FieldPath p = updatedPaths[i];
            // FieldPath for item slots is 38.slotidx
            if (p.last != 1 || p.path[0] != 38 || (p.path[1] != 6 && p.path[1] != 7)) continue;
            System.out.format("Tick %d: Slot %d now %d\n", ctx.getTick(), p.path[1], e.getPropertyForFieldPath(p));
        }
    }

    public static void main(String[] args) throws Exception {
        new SimpleRunner(new MappedFileSource(args[0])).runWith(new Main());
    }
}
```
gives
```
Tick 34462: Slot 6 now 3949503
Tick 34916: Slot 6 now 16777215
Tick 40118: Slot 6 now 3720626
Tick 40122: Slot 6 now 1967541
Tick 40402: Slot 6 now 16777215
Tick 42967: Slot 6 now 16777215
Tick 53675: Slot 6 now 2736909
Tick 54737: Slot 6 now 16777215
Tick 56205: Slot 6 now 8192802
Tick 58051: Slot 7 now 8258468
Tick 60317: Slot 6 now 16777215
Tick 60317: Slot 7 now 16777215
```
So the slots are 8192802 and 8258468  from tick 58051 on, and will stay so until tick 60317.
