### ISSUE TITLE
Get a hero's gold and xp

### ISSUE THREAD

**Issue by peemoRoyal** [skadistats/clarity#91]
Hi guys!

I am working on a project where i need to parse some replaydata to JSON format.
Amongst other things I need to parse out the current Gold (or networth) and XP of my heroes, every time they get updated, so I always have the most recent value. 
Weirdly gold and xp are not in the Hero Entitity, like e.g position data, but in the CDOTA_DataRadiant and CDOTA_DataDire entities like that: m_vecDataTeam.0000.m_iTotalEarnedGold. (I know there are different Gold values, but that is not the problem right now ;) )

The 0000 - 0004 value stands for the heroes in their teams (radiant or dire). The Problem is, they have the same fieldPath value. (1/0/0 in this case).

So I do now have the problem, that if I want to check via if(updatedPaths[i].equals(this.gold)), it checks for the 1/0/0 value and gives me a true for two heroes.  (the 0000 on dire and radiant)

I dont know if it is a huge Problem if I have some double entries in my file but it kind of feels weird. Additionally its a pain in the ass to figure out the matching hero entity to the id fieldpath.

So I am wondering if someone can lighten me up and explain why the gold is stored there, if i can use that for my purpose (stream of data) or if it is just ment to be printed out at the end of the replay like in the example (matchend)

Can you give me any hints to help me understand this?
It would be such a great help!

Thanks alot in advance and kind regards

Peter

P.S.: I hope you understand my problem, my english might not be the best.

**Comment by spheenik** [comment]
You can check for the DTClass beforehand, like in this [example](https://github.com/skadistats/clarity/issues/85#issuecomment-204932849).

**Comment by peemoRoyal** [comment]
I am checking it out, but I do not quite understands how this will help me determine which 1/0/0 fiel path is which? Since they are actually similar Entities but are just called differently (dire/radiant).

For understanding it: Can you explain why the Gold and XP is not stored in the Hero Entity? Im sory if this is a dump question, but I dont have a easy time understanding all this, since i only have a 1 year java programming experience..

**Comment by spheenik** [comment]
But you did say one is a CDOTA_DataRadiant and the other is a CDOTA_DataDire?

**Comment by spheenik** [comment]
And I can't explain that. You got to ask Valve why.

**Comment by peemoRoyal** [comment]
Ok i'll just try it all out tonight. Thanks alot for your time!

**Comment by spheenik** [comment]
Sure no problem. The layout of the data is just a plain dump of what's available in the replay, there is no layer above that lets you query stuff conveniently. Valve certainly have their reasons for doing the layout as it is. 

Ah yea, and you asked if you can use the mentioned values for a stream of data, and the answer is yes.
