### ISSUE TITLE
Getting mouse position for a player (Question)

### ISSUE THREAD

**Issue by niliur** [skadistats/clarity#93]
Hello,

I noticed that going into first person mode in the dota replay viewer will also show you the player's mouse movements and clicks. Just wondering how that data is represented in the replay file. I checked the dump for something resembling coordinates but could not find anything that reflects the mouse.

Any help would be greatly appreciated!

**Comment by spheenik** [comment]
There are CDOTAPlayer entities for each player. They all have properties "m_iCursor.0000" for X, and "m_iCursor.0001" for Y coordinate.

**Comment by niliur** [comment]
cool, as a follow up question, how can I get the timestamp for entities? And is there a manual somewhere that I can read about the different Fieldpath properties?

**Comment by spheenik** [comment]
There is the [serializers example](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/serializers/Main.java), and you can use [clarity analyzer](https://github.com/spheenik/clarity-analyzer) to see all properties of all entities in realtime.

**Comment by niliur** [comment]
Thanks for the reply, it helped me solve the problem!
