### ISSUE TITLE
Hero Skills and Cooldowns

### ISSUE THREAD

**Issue by peemoRoyal** [skadistats/clarity#95]
Hi!

I need to check out which Abilities a Hero has skilled how much, and if it is on CD.
I found this one:
+-------+--------------------------------------------------+----------------------+
| 10/1  | m_hAbilities.0001                                | 15696234             |
+-------+--------------------------------------------------+----------------------+
And then we have the CDOT_Ability Entity. I am just confused how those 2 match. What dies the value 15696234 tell me? Anywhere i can look that up or match it to the Abilitiy Entity?
Maybe ill just go for the Ability Entity and store that somewhere so I know which is updated. But still the m_hAbilities.xxxx bothers me. Anyone know why there aer 16 slots for that?

Regards and thanks in advance
Peter

**Comment by spheenik** [comment]
It's a handle (Properties starting with m_h are handles)

You can get the corresponding ability-entity by using `ctx.getProcessor(Entities.class).getByHandle(theHandle)`

And I think it's 16 slots to allow custom game developers some headroom.

**Comment by peemoRoyal** [comment]
Thanks! That really helped me out alot! Thank you!!!

**Comment by spheenik** [comment]
You're welcome!
