### ISSUE TITLE
how can i get 'm_cellbits' property?

### ISSUE THREAD

**Issue by whoisfpc** [skadistats/clarity#96]
I want to track player's position, so i intend to write a function like coordFromCell in [here](https://github.com/skadistats/skadi/wiki/Mapping-(World-&-Image-Coordinates)), but i cant find new version examples. until now, i can get player hero's position with  #`'CBodyComponent.m_cellX'` and `'CBodyComponent.m_cellY'` properties, i want to covert them to world coordinate.

By the way, where can i find these properties definition? it seems #they are different with dota2 protobuf definition file.

**Comment by spheenik** [comment]
m_cellbits was a constant in Source 1, but still a value in the entity 
properties, which Valve decided to remove in Source 2.
You can safely assume the value to be 7.

**Comment by whoisfpc** [comment]
thanks, and where are these property names come from? in dota protobuf files, i only can find some structures like `CDemoFileInfo `

**Comment by spheenik** [comment]
Entities are not encoded as protobufs, but as a proprietary bit stream. The replay "header" contains a description of the format this bit stream has (the description being called the "send tables", and can change between different versions). This description contains all these names. There is [an example](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/serializers/Main.java) which dumps these.

**Comment by whoisfpc** [comment]
oh, thank you a lot, i think i should read example code more detail first!
