### ISSUE TITLE
map coordinates algorithm

### ISSUE THREAD

**Issue by Raikiree** [skadistats/clarity#97]
Hi, I am wondering how the cell(x,y,z) + offset = real location algorithm works in the code, could you give me some hints? For example, how many cells does the map have and where the (0,0) cell, and offset range and start location within a single cell. Also, about the FieldPath class, what does it do?
Thank you!

**Comment by spheenik** [comment]
Here is a gist for calculation positions in Source 1 which should explain:

https://gist.github.com/spheenik/3766744d47c170f25cf5

Source 2 didn't change much, m_cellbits is not a property anymore, and should be replaced with a constant 7 in Source 2.

A FieldPath is the "index" (unique address) of a property of an entity. Entity properties are submitted over the network as nested tables. Each property has a unique field path. 

For an example, please see the screenshot here: https://github.com/spheenik/clarity-analyzer

The field path for "m_iHealth" is "11", while "CBodyComponent.m_cellX" is "14/0".

**Comment by Raikiree** [comment]
ok, I get it. Also do you know the(x,y) value for the left bottom cell and the top right cell? 
Thanks!

**Comment by mintwzy** [comment]
From my experience, if you minus offset 64 from the (x, y) value from the parser (ward location, player location) then you make the value be within 0-127. The left bottom if (0, 0), top right is (127, 127). Hope this can help you.

**Comment by Raikiree** [comment]
thank you!

**Comment by MrGONG0028** [comment]
May I know what should be used to replace "m_vecOrigin" in Source 2? Is is a fix vector now?
