### ISSUE TITLE
Herogold, which value

### ISSUE THREAD

**Issue by peemoRoyal** [skadistats/clarity#99]
Hi!

There are several values for Hero's Gold:

m_vecDataTeam.0000.m_iTotalEarnedGold
m_vecDataTeam.0000.m_iReliableGold
m_vecDataTeam.0000.m_iUnreliableGold  
m_vecDataTeam.0000.m_iSharedGold
m_vecDataTeam.0000.m_iHeroKillGold
m_vecDataTeam.0000.m_iCreepKillGold
m_vecDataTeam.0000.m_iIncomeGold 

I want to draw a graph where u can see which Hero earned more. I was using the iTotalEarnedGold in my parser. When i tried it out, the Graph was looking pretty weird, since the values jump around alot...

So I was wondering if I am using the correct parameters here?

What is the totalEarnedGold?
Is there something similar to NetWorth? 
Or do I have to calculate something to get a reliable value?

Thanks in advance
Peter

**Comment by Raikiree** [comment]
The totalEarnedGold is all gold a hero got, not the networth

**Comment by spheenik** [comment]
There is an entity of type CDOTA_DataSpectator. It has m_iNetWorth.0000, m_iNetWorth.0001 and so on.

**Comment by peemoRoyal** [comment]
@Raikiree: Yeah but it is still a bit weird, since the values get higher constantly. That means it cant be just the gold, it has to be somehow correlated to the items a hero bought.

<img width="1332" alt="screen shot 2016-07-31 at 18 16 10" src="https://cloud.githubusercontent.com/assets/5907564/17277743/ec7dbb00-574a-11e6-9943-597477b970e4.png">

Maybe I just parsed/ordered the data incorrectly

@spheenik Thanks again! You help me out so much. It also kinda makes sense it is in the spectator entity...
